namespace NSYazilim.Web.Services
{
    public sealed record LocalizationSeedItem(string Source, string English, string Area)
    {
        public LocalizationSeedItem(string source, string english, string german, string arabic, string area)
            : this(source, english, area)
        {
        }
    }

    public static class LocalizationSeedData
    {
        public static readonly IReadOnlyList<LocalizationSeedItem> Items = new LocalizationSeedItem[]
        {
            new("Güvenli dijital teslimat", "Secure digital delivery", "/Shared/Header"),
            new("Destek", "Support", "/Shared/Header"),
            new("İndirmelerim", "My Downloads", "/Shared/Header"),
            new("Lisanslarım", "My Licenses", "/Shared/Header"),
            new("Ana Sayfa", "Home", "/Shared/Header"),
            new("Yazılımlar", "Software", "/Shared/Header"),
            new("NSX Çözümleri", "NSX Solutions", "/Shared/Header"),
            new("İşletmenize uygun yazılımı seçin", "Choose the right software for your business", "/Shared/Header"),
            new("Tüm Yazılımlar", "All Software", "/Shared/Header"),
            new("Ürünleri görüntüle", "View products", "/Shared/Header"),
            new("Videolar", "Videos", "/Shared/Header"),
            new("Rehberler", "Guides", "/Shared/Header"),
            new("NSX Hesabı", "NSX Account", "/Shared/Header"),
            new("Hesap, lisans ve indirme işlemleriniz.", "Your account, licenses and downloads.", "/Shared/Header"),
            new("Hesabım", "My Account", "/Shared/Header"),
            new("Genel bakış ve siparişler", "Overview and orders", "/Shared/Header"),
            new("Aktif ürün lisanslarınız", "Your active product licenses", "/Shared/Header"),
            new("Kurulum ve program dosyaları", "Setup and program files", "/Shared/Header"),
            new("Şifre ve Güvenlik", "Password & Security", "/Shared/Header"),
            new("Hesap erişim ayarları", "Account access settings", "/Shared/Header"),
            new("Çıkış Yap", "Sign Out", "/Shared/Header"),
            new("Oturumu güvenle kapatın", "Sign out securely", "/Shared/Header"),
            new("Hoşgeldiniz", "Welcome", "/Shared/Header"),
            new("Hesabınıza giriş yapın veya ücretsiz üyelik oluşturun.", "Sign in to your account or create a free account.", "/Shared/Header"),
            new("Giriş Yap", "Sign In", "/Shared/Header"),
            new("Lisans ve indirmelerinize ulaşın", "Access your licenses and downloads", "/Shared/Header"),
            new("Ücretsiz Üye Ol", "Create Free Account", "/Shared/Header"),
            new("Yeni NSX hesabı oluşturun", "Create a new NSX account", "/Shared/Header"),
            new("Ana menü", "Main menu", "/Shared/Header"),
            new("NSX Yazılım ana sayfa", "NSX Software home page", "/Shared/Header"),
            new("Ana menüyü aç", "Open main menu", "/Shared/Header"),
            new("Düğün & Organizasyon", "Wedding & Events", "/Shared/Categories"),
            new("Cari & Finans", "Accounts & Finance", "/Shared/Categories"),
            new("Servis Yönetimi", "Service Management", "/Shared/Categories"),
            new("Otomotiv", "Automotive", "/Shared/Categories"),
            new("Klinik & Randevu", "Clinic & Appointments", "/Shared/Categories"),
            new("PC Performans", "PC Performance", "/Shared/Categories"),
            new("Geliştirici Araçları", "Developer Tools", "/Shared/Categories"),
            new("Sigorta & Acenteler", "Insurance & Agencies", "/Shared/Categories"),
            new("Eğitim ve Okul Yönetimi", "Education & School Management", "/Shared/Categories"),
            new("Ücretsiz Veresiye Programı ve İşletme Yazılımları | NSX Yazılım", "Free Receivables Software and Business Software | NSX Software", "/"),
            new("NSX Ücretsiz Veresiye, Barkodlu Satış ve Stok, Kasa Defteri, Sigorta Acente, Security Auditor, cari hesap, teknik servis, otomotiv ve klinik yazılımlarını keşfedin.", "Discover NSX Free Receivables, Barcode Sales & Stock, Cash Book, Insurance Agency, Security Auditor, accounts, technical service, automotive and clinic software.", "/"),
            new("Ücretsiz Veresiye, Barkodlu Satış ve Stok, Kasa Defteri, Sigorta Acente ve Security Auditor dahil profesyonel NSX yazılımlarını keşfedin.", "Discover professional NSX software, including Free Receivables, Barcode Sales & Stock, Cash Book, Insurance Agency and Security Auditor.", "/"),
            new("%100 Ücretsiz · Ömür Boyu Kullanım", "100% Free · Lifetime Use", "/"),
            new("Ücretsiz Veresiye Programı ile", "With Free Receivables Software", "/"),
            new("cari takibinizi", "simplify your", "/"),
            new("kolaylaştırın", "account tracking", "/"),
            new("Cari hesap takibi, tahsilat yönetimi, borç-alacak kontrolü ve günlük kullanım kolaylığı tek pakette. NSX Veresiye Takip Programı, Bulut ve Mobil Yönetim desteğiyle cari hesaplarınıza bilgisayardan ve cep telefonundan erişmenizi sağlar; işletmelerin cari süreçlerini zahmetsizce yönetmesi için ücretsiz sunulur.", "Manage customer accounts, collections, debit-credit balances and daily operations in one simple package. NSX Receivables Tracking gives you secure access from your computer and phone with Cloud and Mobile Management, completely free for effortless account management.", "/"),
            new("Cari hesap, tahsilat ve borç-alacak takibinizi bilgisayar veya cep telefonundan kolayca yönetin. Üstelik tamamen ücretsiz.", "Manage accounts, collections and debit-credit tracking easily from your computer or phone. Completely free.", "/"),
            new("Ücretsiz İndir", "Download Free", "/"),
            new("Tamamen ücretsiz", "Completely free", "/"),
            new("Ürünü İncele", "View Product", "/"),
            new("%100 Ücretsiz", "100% Free", "/"),
            new("Sınırsız kullanım", "Unlimited use", "/"),
            new("Kolay Kullanım", "Easy to Use", "/"),
            new("Hızlı kurulum", "Quick setup", "/"),
            new("Günlük Takip", "Daily Tracking", "/"),
            new("Pratik kullanım", "Practical use", "/"),
            new("Yerli & Güvenli", "Local & Secure", "/"),
            new("Veri güvenliği", "Data security", "/"),
            new("Vadesi Geçen", "Overdue", "/"),
            new("Hesap", "Accounts", "/"),
            new("Tahsilat (Bugün)", "Collections (Today)", "/"),
            new("Toplam Cari", "Total Accounts", "/"),
            new("Toplam İşlem", "Total Transactions", "/"),
            new("Alacak / Borç Dengesi", "Receivable / Payable Balance", "/"),
            new("Dengede", "Balanced", "/"),
            new("Bulut Senkron", "Cloud Sync", "/"),
            new("Mobil Erişim", "Mobile Access", "/"),
            new("NSX Veresiye · Ücretsiz, sade ve hızlı cari takip", "NSX Receivables · Free, simple and fast account tracking", "/"),
            new("NSX YAZILIMLARI", "NSX SOFTWARE", "/"),
            new("Son eklenen profesyonel çözümler.", "Latest professional solutions.", "/"),
            new("Tüm yazılımları incele", "View all software", "/"),
            new("Yeni", "New", "/"),
            new("Başlangıç", "Starting from", "/"),
            new("Kampanyalı fiyat", "Campaign price", "/"),
            new("Daha fazla NSX çözümü", "More NSX solutions", "/"),
            new("Diğer ürünleri göster", "Show more products", "/"),
            new("Kolay başlangıç", "Easy start", "/"),
            new("Keşiften kuruluma,", "From discovery to setup,", "/"),
            new("dört net adım.", "four clear steps.", "/"),
            new("İhtiyacınıza uygun yazılımı bulun, özelliklerini inceleyin, lisanslayın ve NSX desteğiyle güvenle kullanmaya devam edin.", "Find the right software, review its features, license it and keep using it confidently with NSX support.", "/"),
            new("İhtiyacınızı seçin", "Choose Your Need", "/"),
            new("Sektörünüze göre filtreleyin ve size uygun çözümü bulun.", "Filter by industry and find the solution that fits your business.", "/"),
            new("Ortalama 30 saniye", "About 30 seconds", "/"),
            new("İnceleyin ve deneyin", "Review and Try", "/"),
            new("Özellikleri karşılaştırın, uygun ürünlerde ücretsiz sürümü indirip iş akışınızı test edin.", "Compare features and, where available, download the free version to test your workflow.", "/"),
            new("Risksiz ürün deneyimi", "Risk-free product trial", "/"),
            new("Lisanslayın, başlayın", "License and Start", "/"),
            new("Dijital lisansınıza hızlıca erişin; ihtiyaç halinde uzaktan kurulum desteği alın.", "Get fast access to your digital license and remote setup support when needed.", "/"),
            new("NSX ekibi yanınızda", "NSX team by your side", "/"),
            new("Güncel kalın, destek alın", "Stay Updated and Get Support", "/"),
            new("Güncellemeleri takip edin; ihtiyaç duyduğunuzda NSX destek ekibine hızlıca ulaşın.", "Keep up with updates and quickly reach NSX support whenever you need help.", "/"),
            new("Satış sonrası destek", "After-sales support", "/"),
            new("işletme yazılımı", "business software", "/"),
            new("ürün değerlendirmesi", "product rating", "/"),
            new("dijital erişim", "digital access", "/"),
            new("tek noktadan destek", "single-point support", "/"),
            new("NSX Yazılım · Hızlı çözüm", "NSX Software · Fast solutions", "/"),
            new("İşletmenize uygun çözüm", "The right software solution for your business", "/"),
            new("bir tık uzağınızda.", "is one click away.", "/"),
            new("İhtiyacınıza uygun NSX yazılımını inceleyin, lisans seçiminizi netleştirin ve gerektiğinde doğrudan destek alın.", "Explore the NSX software that fits your needs, choose the right license and get direct support when needed.", "/"),
            new("Hızlı lisans erişimi", "Fast license access", "/"),
            new("Kurulum desteği", "Installation support", "/"),
            new("NSX çözümlerini keşfedin", "Explore NSX solutions", "/"),
            new("Çözümleri Hemen İncele", "Explore Solutions Now", "/"),
            new("Doğrudan destek hattı", "Direct support line", "/"),
            new("WhatsApp ile mesaj gönderin", "Send a WhatsApp message", "/"),
            new("Yukarı", "Top", "/"),
            new("Yukarı çık", "Back to top", "/"),
            new("NSX Veresiye avantajları", "NSX Receivables benefits", "/"),
            new("NSX Veresiye Takip Programı tanıtım ekranı", "NSX Receivables Tracking software preview", "/"),
            new("NSX hizmet avantajları", "NSX service benefits", "/"),
            new("WhatsApp üzerinden NSX Yazılım desteğine ulaşın", "Contact NSX Software support via WhatsApp", "/"),
            new("Sayfanın başına dön", "Back to the top of the page", "/"),
            new("Rezervasyon", "Reservations", "/"),
            new("Müşteri takibi", "Customer tracking", "/"),
            new("Tahsilat yönetimi", "Collection management", "/"),
            new("Cari hesaplar", "Customer accounts", "/"),
            new("Borç ve alacak", "Payables and receivables", "/"),
            new("Raporlama", "Reporting", "/"),
            new("Servis kabul", "Service intake", "/"),
            new("İşlem geçmişi", "Transaction history", "/"),
            new("Araç takibi", "Vehicle tracking", "/"),
            new("Müşteri yönetimi", "Customer management", "/"),
            new("Kârlılık raporu", "Profitability report", "/"),
            new("Randevu takibi", "Appointment tracking", "/"),
            new("Hasta yönetimi", "Patient management", "/"),
            new("Bildirimler", "Notifications", "/"),
            new("Sistem optimizasyonu", "System optimization", "/"),
            new("Performans takibi", "Performance tracking", "/"),
            new("Gelişmiş takip", "Advanced tracking", "/"),
            new("Detaylı raporlar", "Detailed reports", "/"),
            // Revenue-critical checkout: reviewed English seeds keep every new language in the normal localization queue.
            new("Ödeme Yöntemi | NSX Yazılım", "Payment Method | NSX Software", "/Public/Checkout"),
            new("Ürüne dön", "Back to product", "/Public/Checkout"),
            new("GÜVENLİ ÖDEME", "SECURE PAYMENT", "/Public/Checkout"),
            new("Ödeme yöntemini seçin", "Choose a payment method", "/Public/Checkout"),
            new("Kartla Shopier üzerinden anında ödeme yapabilir veya Havale / EFT ile devam edebilirsiniz.", "Pay instantly by card through Shopier or continue with bank transfer / EFT.", "/Public/Checkout"),
            new("Ödemeleriniz 256-bit SSL ile koruma altındadır.", "Your payments are protected with 256-bit SSL.", "/Public/Checkout"),
            new("Seçili ürün", "Selected product", "/Public/Checkout"),
            new("Yıllık Lisans", "Annual License", "/Public/Checkout"),
            new("Sınırsız Lisans", "Lifetime License", "/Public/Checkout"),
            new("Tutar", "Amount", "/Public/Checkout"),
            new("ÖNERİLEN", "RECOMMENDED", "/Public/Checkout"),
            new("KARTLA ÖDEME", "CARD PAYMENT", "/Public/Checkout"),
            new("Banka / Kredi Kartı", "Debit / Credit Card", "/Public/Checkout"),
            new("Shopier güvenli ödeme altyapısı üzerinden kartınızla hızlı ve güvenli ödeme yapın.", "Pay quickly and securely by card through Shopier's secure payment infrastructure.", "/Public/Checkout"),
            new("Anında ödeme", "Instant payment", "/Public/Checkout"),
            new("256-bit SSL güvenliği", "256-bit SSL security", "/Public/Checkout"),
            new("Tüm yaygın kartlarla ödeme", "All major cards accepted", "/Public/Checkout"),
            new("Shopier ile Güvenli Öde", "Pay Securely with Shopier", "/Public/Checkout"),
            new("Shopier ekranında lisans seçiminizi doğrulayın.", "Confirm your license selection on the Shopier screen.", "/Public/Checkout"),
            new("Otomatik lisans teslimatı için Shopier'de hesabınızdaki e-posta adresini kullanın:", "For automatic license delivery, use your account email on Shopier:", "/Public/Checkout"),
            new("Bu ürün için kartla ödeme bağlantısı henüz tanımlı değil.", "The card-payment link for this product is not ready yet.", "/Public/Checkout"),
            new("Shopier eşleştirmesi bekleniyor", "Waiting for Shopier matching", "/Public/Checkout"),
            new("BANKA TRANSFERİ", "BANK TRANSFER", "/Public/Checkout"),
            new("Havale / EFT", "Bank Transfer / EFT", "/Public/Checkout"),
            new("Banka hesabımıza havale yaptıktan sonra ödeme bildiriminizi gönderin. Onay sonrası lisansınız hesabınıza tanımlanır.", "Send your payment notification after the bank transfer. Your license is added to your account after approval.", "/Public/Checkout"),
            new("Tüm bankalardan ödeme", "Payments from all banks", "/Public/Checkout"),
            new("Güvenli ve pratik", "Secure and convenient", "/Public/Checkout"),
            new("Onay sonrası hızlı işlem", "Fast processing after approval", "/Public/Checkout"),
            new("Banka bilgilerimizi görüntüleyin", "View our bank details", "/Public/Checkout"),
            new("Havale / EFT için gerekli hesap bilgileri, açıklama ve ödeme sonrası adımlar.", "Account details, transfer note and post-payment steps for bank transfer / EFT.", "/Public/Checkout"),
            new("Banka Bilgilerini Gör", "View Bank Details", "/Public/Checkout"),
            new("Güvenli Ödeme Altyapısı", "Secure Payment Infrastructure", "/Public/Checkout"),
            new("Kart ödemeleri Shopier güvenli ödeme altyapısı üzerinden tamamlanır.", "Card payments are completed through Shopier's secure payment infrastructure.", "/Public/Checkout"),
            new("Havale / EFT ile Ödeme", "Pay by Bank Transfer / EFT", "/Public/Checkout"),
            new("Dijital teslimat", "Digital delivery", "/Public/Checkout"),
            new("Güvenli lisanslama", "Secure licensing", "/Public/Checkout"),
            new("NSX teknik destek", "NSX technical support", "/Public/Checkout"),
            new("Güvenli Dijital Teslimat", "Secure Digital Delivery", "/Shared/Footer"),
            new("Onay sonrası lisans ve indirme erişimi", "License and download access after approval", "/Shared/Footer"),
            new("Hızlı Kurulum", "Fast Setup", "/Shared/Footer"),
            new("Kolay başlangıç ve uzaktan destek", "Easy start and remote support", "/Shared/Footer"),
            new("Yerli Yazılım", "Local Software", "/Shared/Footer"),
            new("Türkiye'deki işletmelere özel çözümler", "Solutions tailored for businesses in Turkey", "/Shared/Footer"),
            new("Satış Sonrası Destek", "After-sales Support", "/Shared/Footer"),
            new("Lisans ve kullanım sürecinde yanınızda", "Support throughout licensing and use", "/Shared/Footer"),
            new("Veresiye ve cari takipten teknik servise, klinikten otomotive kadar işletmeler için modern Windows yazılımları.", "Modern Windows software for businesses, from receivables and accounts to technical service, clinics and automotive management.", "/Shared/Footer"),
            new("Güvenli teslimat", "Secure delivery", "/Shared/Footer"),
            new("Hızlı lisans", "Fast licensing", "/Shared/Footer"),
            new("Yazılım Kategorileri", "Software Categories", "/Shared/Footer"),
            new("Barkodlu Satış & Stok", "Barcode Sales & Stock", "/Shared/Footer"),
            new("Cari & Veresiye Takip", "Accounts & Receivables", "/Shared/Footer"),
            new("Teknik Servis Yönetimi", "Technical Service Management", "/Shared/Footer"),
            new("Otomotiv Yazılımları", "Automotive Software", "/Shared/Footer"),
            new("Klinik & Randevu", "Clinic & Appointments", "/Shared/Footer"),
            new("Sektörel Çözümler", "Industry Solutions", "/Shared/Footer"),
            new("Düğün Salonu Programı", "Wedding Venue Software", "/Shared/Footer"),
            new("Sigorta Acente Programı", "Insurance Agency Software", "/Shared/Footer"),
            new("Klinik Programı", "Clinic Software", "/Shared/Footer"),
            new("Randevu Programı", "Appointment Software", "/Shared/Footer"),
            new("PC Hızlandırma Programı", "PC Performance Software", "/Shared/Footer"),
            new("Komisyonlu Cari Takip", "Commission-based Account Tracking", "/Shared/Footer"),
            new("Yazılım Rehberleri", "Software Guides", "/Shared/Footer"),
            new("Kurumsal & Yasal", "Corporate & Legal", "/Shared/Footer"),
            new("Hakkımızda", "About Us", "/Shared/Footer"),
            new("Sıkça Sorulan Sorular", "Frequently Asked Questions", "/Shared/Footer"),
            new("İade Politikası", "Refund Policy", "/Shared/Footer"),
            new("Gizlilik Politikası", "Privacy Policy", "/Shared/Footer"),
            new("KVKK Aydınlatma Metni", "Personal Data Notice", "/Shared/Footer"),
            new("Tanıtım Videoları", "Product Videos", "/Shared/Footer"),
            new("NSX DESTEK", "NSX SUPPORT", "/Shared/Footer"),
            new("Tek noktadan hızlı destek.", "Fast support from one place.", "/Shared/Footer"),
            new("Telefon", "Phone", "/Shared/Footer"),
            new("E-posta", "Email", "/Shared/Footer"),
            new("Destek Merkezi", "Support Center", "/Shared/Footer"),
            new("Havale / EFT ile güvenli satın alma", "Secure purchase by bank transfer", "/Shared/Footer"),
            new("Ödeme onayından sonra dijital lisansınız hesabınıza tanımlanır.", "Your digital license is added to your account after payment approval.", "/Shared/Footer"),
            new("Bizi takip edin", "Follow us", "/Shared/Footer"),
            new("© 2026 NSX Yazılım. Tüm hakları saklıdır.", "© 2026 NSX Software. All rights reserved.", "/Shared/Footer"),
            new("Gizlilik", "Privacy", "/Shared/Footer"),
            new("KVKK", "Data Protection", "/Shared/Footer"),
            new("Türkiye genelinde işletmeler için güvenilir dijital yazılım çözümleri.", "Reliable digital software solutions for businesses across Turkey.", "/Shared/Footer"),
            new("NSX Yazılım hizmet güvenceleri", "NSX Software service guarantees", "/Shared/Footer"),
            new("Yazılım kategorileri", "Software categories", "/Shared/Footer"),
            new("Sektörel çözümler", "Industry solutions", "/Shared/Footer"),
            new("Kurumsal ve yasal", "Corporate and legal", "/Shared/Footer"),
            new("NSX müşteri desteği", "NSX customer support", "/Shared/Footer"),
            new("NSX Yazılım sosyal medya hesapları", "NSX Software social media accounts", "/Shared/Footer"),
            new("Güvenli Kurulum Rehberi", "Safe Installation Guide", "/Shared/InstallGuide"),
            new("İndirdiğiniz dosya açılmıyorsa aşağıdaki adımlarla engellemeyi kaldırın.", "If the downloaded file will not open, follow the steps below to unblock it.", "/Shared/InstallGuide"),
            new("İndirdiğiniz kurulum dosyasına sağ tıklayın.", "Right-click the setup file you downloaded.", "/Shared/InstallGuide"),
            new("İndirilenler klasöründeki exe kurulum dosyasını bulun.", "Find the exe setup file in your Downloads folder.", "/Shared/InstallGuide"),
            new("Özellikler seçeneğine tıklayın.", "Click Properties.", "/Shared/InstallGuide"),
            new("Açılan menüden Özellikler satırını seçin.", "From the menu that opens, select Properties.", "/Shared/InstallGuide"),
            new("Engellemeyi kaldır kutusunu işaretleyin.", "Tick the Unblock checkbox.", "/Shared/InstallGuide"),
            new("Pencerenin altında Engellemeyi kaldır seçeneğini işaretleyip Tamam düğmesine basın.", "At the bottom of the window, tick Unblock and then press OK.", "/Shared/InstallGuide"),
            new("Dosyayı çift tıklayarak kurulumu başlatın.", "Double-click the file to start installation.", "/Shared/InstallGuide"),
            new("Engelleme kalktıktan sonra kurulum normal şekilde açılır.", "After unblocking, the installer opens normally.", "/Shared/InstallGuide"),
            new("Özellikler penceresi örneği", "Properties window example", "/Shared/InstallGuide"),
            new("Windows Özellikler penceresinde Engellemeyi Kaldır seçeneği", "Unblock option in the Windows Properties window", "/Shared/InstallGuide"),
            new("Windows Özellikler penceresi Genel sekmesi", "Windows Properties window General tab", "/Shared/InstallGuide"),
            new("Gerçek Windows Özellikler penceresi — Engellemeyi Kaldır", "Real Windows Properties window — Unblock", "/Shared/InstallGuide"),
            new("1) Sağ tık → Özellikler", "1) Right-click → Properties", "/Shared/InstallGuide"),
            new("2) Engellemeyi Kaldır → Tamam", "2) Unblock → OK", "/Shared/InstallGuide"),
            new("Özellikler", "Properties", "/Shared/InstallGuide"),
            new("Tür:", "Type:", "/Shared/InstallGuide"),
            new("Uygulama", "Application", "/Shared/InstallGuide"),
            new("Konum:", "Location:", "/Shared/InstallGuide"),
            new("Engellemeyi kaldır", "Unblock", "/Shared/InstallGuide"),
            new("Bu dosya başka bir bilgisayardan geldi. Güvenliği doğrulamak için engellendi.", "This file came from another computer and might be blocked to help protect this computer.", "/Shared/InstallGuide"),
            new("Tamam", "OK", "/Shared/InstallGuide"),
            new("İptal", "Cancel", "/Shared/InstallGuide"),
            new("Kısaca:", "In short:", "/Shared/InstallGuide"),
            new("Sağ tık → Özellikler → Engellemeyi kaldır → Tamam → Dosyayı çalıştır.", "Right-click → Properties → Unblock → OK → Run the file.", "/Shared/InstallGuide"),
            new("%100 Güvenli", "100% Secure", "/Shared/InstallGuide"),
            new("Resmî NSX Yazılım kurulumu", "Official NSX Software installer", "/Shared/InstallGuide"),
            new("Bu pencere", "This window will close in", "/Shared/InstallGuide"),
            new("saniye sonra kapanacaktır.", "seconds.", "/Shared/InstallGuide"),
            new("Bir daha gösterme", "Don't show again", "/Shared/InstallGuide"),
            new("Kapat", "Close", "/Shared/InstallGuide"),
            new("adresinden indirdiğiniz dosyaları kullanın.", "only use files downloaded from this address.", "/Shared/InstallGuide"),
            new("Kurulum rehberini kapat", "Close installation guide", "/Shared/InstallGuide"),
            new("Okullar için ders programı, öğretmen, sınıf, derslik ve nöbet planlamasını kolaylaştıran profesyonel okul yönetim yazılımı.", "Professional school planning software that simplifies timetables, teachers, classes, classrooms and duty scheduling.", "/"),
            new("NSX Kasa Defteri Pro ile kasa hareketleri, döviz kurları, tahsilat ve ödemeler, cari hesaplar, raporlar ve yedekleme işlemlerini kolayca yönetin.", "Easily manage cash transactions, exchange rates, collections and payments, customer accounts, reports and backups with NSX Cash Book Pro.", "/"),
            new("NSX Sigorta Acenta Pro ile müşteri, poliçe, teklif, ödeme ve yenileme süreçlerini yönetin; otomatik hatırlatmalarla poliçe tarihlerini kaçırmayın.", "Manage customers, policies, quotations, payments and renewals with NSX Insurance Agency Pro, and never miss policy dates with automatic reminders.", "/"),
            new("NSX Security Auditor Pro ile projelerinizi güvenlik açıkları, riskli kodlar ve yapılandırma hatalarına karşı tarayın; Yapay Zeka destekli analiz ve profesyonel çözüm önerileri alın.", "Scan your projects for vulnerabilities, risky code and configuration errors with NSX Security Auditor Pro, with AI-assisted analysis and professional remediation guidance.", "/"),
            new("Dil seçimi", "Language selection", "/Shared/Header"),
            new("Dil Seçin", "Choose Language", "/Shared/Header"),
            new("Tercihiniz bu cihazda hatırlanır", "Your preference is remembered on this device", "/Shared/Header"),
        };
    }
}
