namespace NSYazilim.Web.Services
{
    public static class LocalizationEnglishAccountSeedData
    {
        private static LocalizationSeedItem E(string source, string english, string area)
            => new(source, english, area);

        public static readonly IReadOnlyList<LocalizationSeedItem> Items = new LocalizationSeedItem[]
        {
            E("Lisans yönetimi", "License management", "/Account"),
            // Change password
            E("Başka sitelerde kullanmadığınız; harf, rakam ve özel karakter içeren bir şifre seçin.", "Choose a password you do not use on other sites and include letters, numbers and special characters.", "/Account/ChangePassword"),
            E("Göster", "Show", "/Account/ChangePassword"),
            E("Güvenli hesap", "Secure account", "/Account/ChangePassword"),
            E("Güvenli şifre önerisi", "Secure password tip", "/Account/ChangePassword"),
            E("Güçlü parola", "Strong password", "/Account/ChangePassword"),
            E("HESAP GÜVENLİĞİ", "ACCOUNT SECURITY", "/Account/ChangePassword"),
            E("Hesabınızı güçlü ve size özel bir şifreyle koruyun.", "Protect your account with a strong password that is unique to you.", "/Account/ChangePassword"),
            E("Hızlı güncelleme", "Quick update", "/Account/ChangePassword"),
            E("Mevcut şifre", "Current password", "/Account/ChangePassword"),
            E("Mevcut şifreniz", "Your current password", "/Account/ChangePassword"),
            E("PAROLA YÖNETİMİ", "PASSWORD MANAGEMENT", "/Account/ChangePassword"),
            E("Yeni şifre", "New password", "/Account/ChangePassword"),
            E("Yeni şifre tekrarı", "Confirm new password", "/Account/ChangePassword"),
            E("Yeni şifrenizi tekrar yazın", "Enter your new password again", "/Account/ChangePassword"),
            E("güvenli parola", "secure password", "/Account/ChangePassword"),
            E("kontrolünüzde.", "under your control.", "/Account/ChangePassword"),
            E("Şifrenizi değiştirin", "Change your password", "/Account/ChangePassword"),
            E("Şifreyi Güncelle", "Update Password", "/Account/ChangePassword"),

            // Downloads
            E("Bu ürün için program dosyası henüz yüklenmemiş.", "The program file for this product has not been uploaded yet.", "/Account/Downloads"),
            E("DEMO ÜRÜNLER", "DEMO PRODUCTS", "/Account/Downloads"),
            E("Daha önce indirdiklerim", "Previous downloads", "/Account/Downloads"),
            E("Demo dosyası henüz yüklenmemiş.", "The demo file has not been uploaded yet.", "/Account/Downloads"),
            E("Demo erişimi", "Demo access", "/Account/Downloads"),
            E("Demo indirdiğinizde veya lisanslı ürün satın aldığınızda dosyalar burada görünür.", "Files appear here after you download a demo or purchase a licensed product.", "/Account/Downloads"),
            E("Demo kurulum dosyası", "Demo setup file", "/Account/Downloads"),
            E("Demo ürünleri ve aktif lisanslarınıza ait program dosyalarını güvenle indirin.", "Securely download demo products and program files for your active licenses.", "/Account/Downloads"),
            E("DİJİTAL TESLİMAT", "DIGITAL DELIVERY", "/Account/Downloads"),
            E("Güvenli indirme", "Secure download", "/Account/Downloads"),
            E("Henüz indirme kaydınız yok.", "You do not have any download records yet.", "/Account/Downloads"),
            E("Satın aldığım programlar", "Programs I purchased", "/Account/Downloads"),
            E("TAM SÜRÜM", "FULL VERSION", "/Account/Downloads"),
            E("Tam sürüm", "Full version", "/Account/Downloads"),
            E("Tekrar İndir ↓", "Download Again ↓", "/Account/Downloads"),
            E("erişilebilir ürün", "available product", "/Account/Downloads"),
            E("hazır ve güvende.", "ready and secure.", "/Account/Downloads"),
            E("İndir ↓", "Download ↓", "/Account/Downloads"),

            // Forgot password
            E("Bağlantı", "Link", "/Account/ForgotPassword"),
            E("Bir e-posta adresinin sistemde kayıtlı olup olmadığını açıkça göstermeyiz.", "We do not reveal whether an email address is registered in the system.", "/Account/ForgotPassword"),
            E("E-posta adresi", "Email address", "/Account/ForgotPassword"),
            E("Giriş sayfasına dönün", "Return to the sign-in page", "/Account/ForgotPassword"),
            E("Gizli hesap kontrolü", "Private account check", "/Account/ForgotPassword"),
            E("Gizliliğiniz korunur", "Your privacy is protected", "/Account/ForgotPassword"),
            E("Güvenli bağlantı", "Secure link", "/Account/ForgotPassword"),
            E("Güvenli yenileme bağlantısını e-posta kutunuzdan açın.", "Open the secure reset link from your email inbox.", "/Account/ForgotPassword"),
            E("HESAP KURTARMA", "ACCOUNT RECOVERY", "/Account/ForgotPassword"),
            E("Hesabınıza yeniden", "Back to your account", "/Account/ForgotPassword"),
            E("Hesabınızın gizliliğini koruyarak yenileme sürecini başlatır, e-posta bağlantısı üzerinden yeni şifrenizi belirlemenizi sağlarız.", "We start the reset process without exposing your account status and let you set a new password through a secure email link.", "/Account/ForgotPassword"),
            E("Hızlı erişim", "Quick access", "/Account/ForgotPassword"),
            E("Kayıtlı e-posta adresinizi yazın; geçerli hesabınız varsa güvenli şifre yenileme bağlantısını gönderelim.", "Enter your registered email address; if a valid account exists, we will send a secure password reset link.", "/Account/ForgotPassword"),
            E("NSX HESAP GÜVENLİĞİ", "NSX ACCOUNT SECURITY", "/Account/ForgotPassword"),
            E("NSX hesabınızda kullandığınız e-posta adresini girin.", "Enter the email address you use for your NSX account.", "/Account/ForgotPassword"),
            E("Yeni ve güçlü parolanızı belirleyerek hesabınıza dönün.", "Set a new strong password and return to your account.", "/Account/ForgotPassword"),
            E("Yenileme Bağlantısı Gönder", "Send Reset Link", "/Account/ForgotPassword"),
            E("Yenileme bağlantısı güvenlik nedeniyle sınırlı süre geçerlidir.", "For security, the reset link is valid for a limited time.", "/Account/ForgotPassword"),
            E("güvenle erişin.", "access it securely.", "/Account/ForgotPassword"),
            E("Şifre yenileme güvenliği", "Password reset security", "/Account/ForgotPassword"),
            E("Şifremi unuttum", "Forgot my password", "/Account/ForgotPassword"),
            E("Şifrenizi birkaç güvenli adımda yenileyin.", "Reset your password in a few secure steps.", "/Account/ForgotPassword"),
            E("Şifrenizi hatırladınız mı?", "Remembered your password?", "/Account/ForgotPassword"),
            E("ŞİFRE YENİLEME", "PASSWORD RESET", "/Account/ForgotPassword"),

            // Forgot password confirmation
            E("BAĞLANTI GÖNDERİLDİ", "LINK SENT", "/Account/ForgotPasswordConfirmation"),
            E("Bağlantıyı açın", "Open the link", "/Account/ForgotPasswordConfirmation"),
            E("Bağlantıyı zamanında açın", "Open the link before it expires", "/Account/ForgotPasswordConfirmation"),
            E("E-posta kontrol adımları", "Email check steps", "/Account/ForgotPasswordConfirmation"),
            E("E-postadaki bağlantıyı açarak yeni şifrenizi belirleyebilirsiniz. Güvenlik için bağlantının kullanım süresi sınırlıdır.", "Open the link in the email to set a new password. For security, the link is valid for a limited time.", "/Account/ForgotPasswordConfirmation"),
            E("E-postanızı kontrol edin", "Check your email", "/Account/ForgotPasswordConfirmation"),
            E("Gelen kutunuzu ve gerekiyorsa gereksiz/spam klasörünü açın.", "Check your inbox and, if necessary, your junk or spam folder.", "/Account/ForgotPasswordConfirmation"),
            E("Giriş Sayfasına Dön", "Return to Sign In", "/Account/ForgotPasswordConfirmation"),
            E("Hesabınız kayıtlıysa şifre yenileme bağlantısı e-posta adresinize güvenli şekilde gönderildi.", "If your account is registered, a password reset link has been sent securely to your email address.", "/Account/ForgotPasswordConfirmation"),
            E("Mesajı göremiyorsanız spam veya gereksiz klasörünü de kontrol edin. Güvenlik nedeniyle bağlantının geçerlilik süresi sınırlıdır.", "If you cannot see the message, check your spam or junk folder as well. For security, the link is valid for a limited time.", "/Account/ForgotPasswordConfirmation"),
            E("NSX tarafından gönderilen güvenli yenileme bağlantısını kullanın.", "Use the secure reset link sent by NSX.", "/Account/ForgotPasswordConfirmation"),
            E("SONRAKİ ADIM", "NEXT STEP", "/Account/ForgotPasswordConfirmation"),
            E("Spam klasörüne bakın", "Check the spam folder", "/Account/ForgotPasswordConfirmation"),
            E("Tekrar bağlantı iste", "Request another link", "/Account/ForgotPasswordConfirmation"),
            E("Yeni şifrenizi kaydettikten sonra hesabınıza tekrar giriş yapın.", "After saving your new password, sign in to your account again.", "/Account/ForgotPasswordConfirmation"),
            E("Yenileme bağlantısı yalnızca size özel çalışır.", "The reset link is unique to you.", "/Account/ForgotPasswordConfirmation"),
            E("İŞLEM TAMAMLANDI", "PROCESS COMPLETE", "/Account/ForgotPasswordConfirmation"),
            E("Şifre yenileme bağlantısı, hesap erişiminizi korumak için sınırlı süreyle kullanılabilir.", "The password reset link can only be used for a limited time to protect your account access.", "/Account/ForgotPasswordConfirmation"),
            E("Şimdi e-posta kutunuzu", "Now check your inbox", "/Account/ForgotPasswordConfirmation"),

            // Licenses
            E("Aktif, süresi dolan ve sınırsız lisans bilgilerinizi güvenli biçimde yönetin.", "Securely manage your active, expired and lifetime licenses.", "/Account/Licenses"),
            E("Bitiş", "End date", "/Account/Licenses"),
            E("Henüz lisansınız yok.", "You do not have any licenses yet.", "/Account/Licenses"),
            E("Lisans anahtarı", "License key", "/Account/Licenses"),
            E("Lisans durumu", "License status", "/Account/Licenses"),
            E("LİSANS ANAHTARI", "LICENSE KEY", "/Account/Licenses"),
            E("LİSANS MERKEZİ", "LICENSE CENTER", "/Account/Licenses"),
            E("Offline Lisans Dosyası", "Offline License File", "/Account/Licenses"),
            E("Offline kullanım", "Offline use", "/Account/Licenses"),
            E("Offline kullanıma izin verilen ürünlerde lisans anahtarı ve kayıtlı e-posta bilgilerinizle yerel lisans modu kullanılabilir.", "For products that support offline use, you can use local license mode with your license key and registered email address.", "/Account/Licenses"),
            E("Program dosyaları", "Program files", "/Account/Licenses"),
            E("Programı İndir", "Download Program", "/Account/Licenses"),
            E("Satın alma tamamlandığında lisansınız otomatik olarak hesabınıza tanımlanır.", "When your purchase is completed, your license is automatically assigned to your account.", "/Account/Licenses"),
            E("tek merkezde.", "in one place.", "/Account/Licenses"),
            E("toplam lisans", "total licenses", "/Account/Licenses"),
            E("ÜRÜN ERİŞİMİ", "PRODUCT ACCESS", "/Account/Licenses"),
            E("İnternet bağlantısı olmadığında", "When there is no internet connection", "/Account/Licenses"),

            // Login
            E("Aktif lisanslarınızı ve anahtarlarınızı görüntüleyin.", "View your active licenses and license keys.", "/Account/Login"),
            E("Bu cihazda beni 14 gün hatırla", "Remember me on this device for 14 days", "/Account/Login"),
            E("Güvenli oturum", "Secure session", "/Account/Login"),
            E("HESAP MERKEZİ", "ACCOUNT CENTER", "/Account/Login"),
            E("HOŞ GELDİNİZ", "WELCOME", "/Account/Login"),
            E("Henüz hesabınız yok mu?", "Don't have an account yet?", "/Account/Login"),
            E("Hesabıma Giriş Yap", "Sign In to My Account", "/Account/Login"),
            E("Hesabınıza erişmek için bilgilerinizi girin.", "Enter your details to access your account.", "/Account/Login"),
            E("Hesabınıza giriş yaptığınızda satın aldığınız yazılımlar, lisans bilgileri ve indirme haklarınız hazır olur.", "When you sign in, your purchased software, license information and download access are ready in one place.", "/Account/Login"),
            E("Hesap bilgileriniz şifreli bağlantı üzerinden işlenir.", "Your account information is processed over an encrypted connection.", "/Account/Login"),
            E("NSX hesap avantajları", "NSX account benefits", "/Account/Login"),
            E("NSX ÜYE MERKEZİ", "NSX MEMBER CENTER", "/Account/Login"),
            E("Sipariş geçmişinizi ve işlem durumlarını takip edin.", "Track your order history and transaction status.", "/Account/Login"),
            E("Sipariş takibi", "Order tracking", "/Account/Login"),
            E("Siparişler", "Orders", "/Account/Login"),
            E("Siparişlerinizi takip edin, lisans anahtarlarınıza ulaşın ve program dosyalarınızı güvenle indirin.", "Track your orders, access your license keys and securely download your program files.", "/Account/Login"),
            E("Size tanımlanan program dosyalarına kolayca ulaşın.", "Easily access program files assigned to you.", "/Account/Login"),
            E("Tüm NSX işlemlerinizi tek noktadan yönetin.", "Manage all your NSX activity from one place.", "/Account/Login"),
            E("Yazılımlarınız,", "Your software,", "/Account/Login"),
            E("tek güvenli hesapta.", "in one secure account.", "/Account/Login"),
            E("Ücretsiz hesap oluşturun", "Create a free account", "/Account/Login"),
            E("Üye girişi", "Member sign in", "/Account/Login"),
            E("İndirmeler", "Downloads", "/Account/Login"),
            E("Şifrenizi yazın", "Enter your password", "/Account/Login"),

            // My Account
            E("AKTİF LİSANSLAR", "ACTIVE LICENSES", "/Account/MyAccount"),
            E("Detay →", "Details →", "/Account/MyAccount"),
            E("Dosyalarıma git →", "Go to my files →", "/Account/MyAccount"),
            E("Güvenli müşteri hesabı", "Secure customer account", "/Account/MyAccount"),
            E("HESAP E-POSTASI", "ACCOUNT EMAIL", "/Account/MyAccount"),
            E("Henüz lisansınız bulunmuyor.", "You do not have any licenses yet.", "/Account/MyAccount"),
            E("Henüz siparişiniz bulunmuyor.", "You do not have any orders yet.", "/Account/MyAccount"),
            E("Lisanslarıma git", "Go to my licenses", "/Account/MyAccount"),
            E("LİSANSLAR", "LICENSES", "/Account/MyAccount"),
            E("NSX ÜYE PANELİ", "NSX MEMBER PANEL", "/Account/MyAccount"),
            E("SON İŞLEMLER", "RECENT ACTIVITY", "/Account/MyAccount"),
            E("Satın alma tamamlandığında lisans bilgileriniz burada görünür.", "Your license information will appear here after the purchase is completed.", "/Account/MyAccount"),
            E("Siparişlerinizi, lisanslarınızı ve indirme haklarınızı tek merkezden yönetin.", "Manage your orders, licenses and download access from one center.", "/Account/MyAccount"),
            E("Son lisanslar", "Recent licenses", "/Account/MyAccount"),
            E("Son siparişler", "Recent orders", "/Account/MyAccount"),
            E("SİPARİŞLER", "ORDERS", "/Account/MyAccount"),
            E("Tüm siparişleri görüntüle →", "View all orders →", "/Account/MyAccount"),
            E("Tümünü görüntüle", "View all", "/Account/MyAccount"),
            E("İNDİRME HAKKI", "DOWNLOAD ACCESS", "/Account/MyAccount"),
            E("İşletmenize uygun NSX yazılımlarını inceleyerek başlayabilirsiniz.", "Get started by exploring NSX software that fits your business.", "/Account/MyAccount"),

            // Order detail / orders
            E("Lisans henüz oluşturulmamış.", "The license has not been created yet.", "/Account/OrderDetail"),
            E("Lisans teslimatı", "License delivery", "/Account/OrderDetail"),
            E("Lisanslarımı Gör", "View My Licenses", "/Account/OrderDetail"),
            E("Sipariş içeriği, ödeme durumu ve teslim edilen lisans bilgileri.", "Order contents, payment status and delivered license information.", "/Account/OrderDetail"),
            E("Sipariş özeti", "Order summary", "/Account/OrderDetail"),
            E("SİPARİŞ BİLGİLERİ", "ORDER INFORMATION", "/Account/OrderDetail"),
            E("SİPARİŞ DETAYI", "ORDER DETAILS", "/Account/OrderDetail"),
            E("SİPARİŞ İÇERİĞİ", "ORDER CONTENTS", "/Account/OrderDetail"),
            E("sipariş detayı.", "order details.", "/Account/OrderDetail"),
            E("Ödeme", "Payment", "/Account/OrderDetail"),
            E("Ödeme durumu", "Payment status", "/Account/OrderDetail"),
            E("Ödeme onayından sonra lisansınız burada görünecektir.", "Your license will appear here after payment approval.", "/Account/OrderDetail"),
            E("İndirmelerime Git", "Go to My Downloads", "/Account/OrderDetail"),
            E("← Siparişlerime Dön", "← Back to My Orders", "/Account/OrderDetail"),
            E("Henüz siparişiniz yok.", "You do not have any orders yet.", "/Account/Orders"),
            E("SATIŞ GEÇMİŞİ", "PURCHASE HISTORY", "/Account/Orders"),
            E("Satın aldığınız ürünler burada listelenecek.", "Products you purchase will be listed here.", "/Account/Orders"),
            E("Satın alma geçmişinizi, sipariş durumlarını ve teslim edilen ürünleri görüntüleyin.", "View your purchase history, order status and delivered products.", "/Account/Orders"),
            E("Sipariş No", "Order No.", "/Account/Orders"),
            E("Sipariş geçmişi", "Order history", "/Account/Orders"),
            E("Siparişlerim", "My Orders", "/Account/Orders"),
            E("tek ekranda.", "in one place.", "/Account/Orders"),
            E("Tüm siparişler", "All orders", "/Account/Orders"),
            E("Yeni ürün incele", "Explore a new product", "/Account/Orders"),
            E("toplam sipariş", "total orders", "/Account/Orders"),
            E("ÜYE PANELİ", "MEMBER PANEL", "/Account/Orders"),
            E("Ürünler", "Products", "/Account/Orders"),

            // Register
            E("'nı okudum, kabul ediyorum.", " and accept it.", "/Account/Register"),
            E("Ad soyad", "Full name", "/Account/Register"),
            E("Adınız Soyadınız", "Your full name", "/Account/Register"),
            E("Başlamak için", "To get started", "/Account/Register"),
            E("Bilgilerinizi eksiksiz girerek hesabınızı hemen açın.", "Enter your details completely and create your account right away.", "/Account/Register"),
            E("Dosyalarınız", "Your files", "/Account/Register"),
            E("Giriş yapın", "Sign in", "/Account/Register"),
            E("Güvenli üyelik", "Secure membership", "/Account/Register"),
            E("Hesabımı Oluştur", "Create My Account", "/Account/Register"),
            E("Hesabınız", "Your account", "/Account/Register"),
            E("Hesabınız sadece NSX hizmet ve teslimat süreçleri için kullanılır.", "Your account is used only for NSX service and delivery processes.", "/Account/Register"),
            E("Hesabınızı oluşturun, yazılımlarınız hep elinizin altında olsun.", "Create your account and keep your software within easy reach.", "/Account/Register"),
            E("Kayıt sonrasında sipariş, lisans ve indirme süreçlerinizi aynı hesap üzerinden takip edebilirsiniz.", "After registration, you can track orders, licenses and downloads from the same account.", "/Account/Register"),
            E("Lisanslarınız", "Your licenses", "/Account/Register"),
            E("NSX ÜYELİK", "NSX MEMBERSHIP", "/Account/Register"),
            E("NSX üyelik avantajları", "NSX membership benefits", "/Account/Register"),
            E("Satın aldığınız ürünlerin lisans bilgilerine tek yerden erişin.", "Access license information for your purchased products from one place.", "/Account/Register"),
            E("Size tanımlanan indirme dosyalarını güvenli şekilde yönetin.", "Securely manage download files assigned to you.", "/Account/Register"),
            E("Tek hesapla demo indirmelerinizi, satın aldığınız ürünleri ve lisans bilgilerinizi güvenle yönetin.", "Securely manage demo downloads, purchased products and license information with one account.", "/Account/Register"),
            E("Temel bilgilerinizi girerek ücretsiz NSX hesabınızı oluşturun.", "Enter your basic information to create your free NSX account.", "/Account/Register"),
            E("YENİ HESAP", "NEW ACCOUNT", "/Account/Register"),
            E("Zaten hesabınız var mı?", "Already have an account?", "/Account/Register"),
            E("bir dakikanız yeter.", "one minute is enough.", "/Account/Register"),
            E("ve", "and", "/Account/Register"),
            E("ÜCRETSİZ NSX HESABI", "FREE NSX ACCOUNT", "/Account/Register"),
            E("Ücretsiz hesap", "Free account", "/Account/Register"),
            E("Üyelik oluşturun", "Create an account", "/Account/Register"),
            E("Şifre", "Password", "/Account/Register"),
            E("Şifre tekrarı", "Confirm password", "/Account/Register"),

            // Reset password
            E("Başka sitelerde kullandığınız parolayı tekrar kullanmayın.", "Do not reuse a password you use on other websites.", "/Account/ResetPassword"),
            E("En az 6 karakter kullanın. Tahmin edilmesi zor ve başka hesaplarınızda kullanmadığınız bir şifre seçin.", "Use at least 6 characters. Choose a password that is hard to guess and not used on your other accounts.", "/Account/ResetPassword"),
            E("Eski şifreniz geçersiz olur ve hesabınıza yeni şifrenizle giriş yaparsınız.", "Your old password will become invalid and you will sign in with your new password.", "/Account/ResetPassword"),
            E("Farklı bir şifre", "A unique password", "/Account/ResetPassword"),
            E("Gizli kalsın", "Keep it private", "/Account/ResetPassword"),
            E("GÜVENLİK ADIMI", "SECURITY STEP", "/Account/ResetPassword"),
            E("Güvenli saklama", "Secure storage", "/Account/ResetPassword"),
            E("Güçlü olsun", "Make it strong", "/Account/ResetPassword"),
            E("Güçlü şifre önerileri", "Strong password tips", "/Account/ResetPassword"),
            E("Harf ve rakam", "Letters and numbers", "/Account/ResetPassword"),
            E("Harf, rakam ve hatırlayabileceğiniz güvenli bir kombinasyon seçin.", "Choose a secure combination of letters and numbers that you can remember.", "/Account/ResetPassword"),
            E("Kolay tahmin edilmeyen, yalnızca NSX hesabınızda kullandığınız güçlü bir parola seçmeniz hesabınızı daha güvenli tutar.", "Choosing a strong password that is difficult to guess and used only for your NSX account helps keep your account more secure.", "/Account/ResetPassword"),
            E("Yeni ve güçlü bir", "A new and strong", "/Account/ResetPassword"),
            E("Yeni şifre belirleyin", "Set a new password", "/Account/ResetPassword"),
            E("Yeni şifreniz hesabınızın ilk savunma katmanıdır.", "Your new password is the first layer of protection for your account.", "/Account/ResetPassword"),
            E("Yeni şifrenizi iki alana da aynı şekilde girin.", "Enter your new password exactly the same in both fields.", "/Account/ResetPassword"),
            E("Yenileme işlemini iptal etmek mi istiyorsunuz?", "Want to cancel the reset process?", "/Account/ResetPassword"),
            E("Şifre yenilendiğinde", "After the password is reset", "/Account/ResetPassword"),
            E("Şifremi Yenile", "Reset My Password", "/Account/ResetPassword"),
            E("Şifrenizi kimseyle paylaşmayın ve güvenli şekilde saklayın.", "Do not share your password with anyone and keep it secure.", "/Account/ResetPassword"),
            E("Şifrenizi tekrar yazın", "Enter your password again", "/Account/ResetPassword"),
            E("Şifreyi göster", "Show password", "/Account/ResetPassword"),
            E("şifre belirleyin.", "password.", "/Account/ResetPassword"),

            // Account nav
            E("Destek ekibine ulaşın →", "Contact support →", "/Account/Nav"),
            E("Genel Bakış", "Overview", "/Account/Nav"),
            E("Hesap menüsü", "Account menu", "/Account/Nav"),
            E("Yardıma mı ihtiyacınız var?", "Need help?", "/Account/Nav")
        };
    }
}
