namespace NSYazilim.Web.Services
{
    /// <summary>
    /// Strict Arabic overrides. Every visible target is Arabic-script only; product
    /// names, NSX and Pro labels are localized instead of leaking Latin text.
    /// </summary>
    public static class LocalizationArabicStrictSeedData
    {
        public static readonly IReadOnlyList<LocalizationSeedItem> Items = new LocalizationSeedItem[]
        {
            new("Cari hesap takibi, tahsilat yönetimi, borç-alacak kontrolü ve günlük kullanım kolaylığı tek pakette. NSX Veresiye Takip Programı, Bulut ve Mobil Yönetim desteğiyle cari hesaplarınıza bilgisayardan ve cep telefonundan erişmenizi sağlar; işletmelerin cari süreçlerini zahmetsizce yönetmesi için ücretsiz sunulur.", "", "", "متابعة الحسابات الجارية، إدارة التحصيل، مراقبة الديون والائتمان وسهولة الاستخدام اليومية في حزمة واحدة. يتيح برنامج تتبع الائتمان إن إس إكس الوصول إلى حساباتكم الجارية من الكمبيوتر والهاتف المحمول بدعم من الإدارة السحابية والمحمولة؛ ويُقدم مجانًا لتسهيل إدارة الشركات لعملياتها الجارية بدون عناء.", "/"),
            new("Daha fazla NSX çözümü", "", "", "المزيد من حلول إن إس إكس", "/"),
            new("Güncellemeleri takip edin; ihtiyaç duyduğunuzda NSX destek ekibine hızlıca ulaşın.", "", "", "تابع التحديثات؛ تواصل بسرعة مع فريق دعم إن إس إكس عندما تحتاج.", "/"),
            new("NSX Kasa Defteri Pro detay sayfasını aç", "", "", "افتح صفحة تفاصيل دفتر حسابات إن إس إكس", "/"),
            new("NSX Kasa Defteri Pro detaylarını gör", "", "", "عرض تفاصيل دفتر الحسابات إن إس إكس كاسا الاحترافي", "/"),
            new("NSX Kasa Defteri Pro ile kasa hareketleri, döviz kurları, tahsilat ve ödemeler, cari hesaplar, raporlar ve yedekleme işlemlerini kolayca yönetin.", "", "", "قم بإدارة حركات الصندوق، وأسعار الصرف، والتحصيل والمدفوعات، والحسابات المدينة، والتقارير وعملية النسخ الاحتياطي بسهولة باستخدام إن إس إكس دفتر الصندوق الاحترافي.", "/"),
            new("NSX Kasa Defteri Pro ürün görseli", "", "", "صورة المنتج لدفتر حسابات دفتر الصندوق الاحترافي من إن إس إكس", "/"),
            new("NSX Okul Plan Pro detay sayfasını aç", "", "", "صفحة تفاصيل وبين مخطط المدارس الاحترافي من إن إس إكس", "/"),
            new("NSX Okul Plan Pro detaylarını gör", "", "", "شاهد تفاصيل خطة المدرسة إن إس إكس الاحترافي", "/"),
            new("NSX Okul Plan Pro ürün görseli", "", "", "صورة منتج خطة مدرسة إن إس إكس الاحترافي", "/"),
            new("NSX Security Auditor Pro detaylarını gör", "", "", "عرض تفاصيل مدقق الأمان الاحترافي من إن إس إكس", "/"),
            new("NSX Security Auditor Pro ile projelerinizi güvenlik açıkları, riskli kodlar ve yapılandırma hatalarına karşı tarayın; Yapay Zeka destekli analiz ve profesyonel çözüm önerileri alın.", "", "", "قم بفحص مشاريعك مقابل ثغرات الأمان، الأكواد الخطرة وأخطاء التكوين باستخدام مدقق الأمان الاحترافي من إن إس إكس؛ واحصل على تحليل مدعوم بالذكاء الاصطناعي واقتراحات حلول احترافية.", "/"),
            new("NSX Sigorta Acenta Pro ile müşteri, poliçe, teklif, ödeme ve yenileme süreçlerini yönetin; otomatik hatırlatmalarla poliçe tarihlerini kaçırmayın.", "", "", "قم بإدارة عمليات العميل، الوثيقة، العرض، الدفع والتجديد باستخدام إن إس إكس سيجورتا اكينتا الاحترافي؛ لا تفوت مواعيد الوثائق مع التذكيرات التلقائية.", "/"),
            new("NSX Sigorta Acente Pro detay sayfasını aç", "", "", "افتح صفحة تفاصيل وكيل التأمين إن إس إكس الاحترافي", "/"),
            new("NSX Sigorta Acente Pro detaylarını gör", "", "", "عرض تفاصيل وكيل التأمين إن إس إكس الاحترافي", "/"),
            new("NSX Sigorta Acente Pro ürün görseli", "", "", "صورة المنتج لوكيل التأمين إن إس إكس", "/"),
            new("NSX Veresiye Pro program ekranı", "", "", "شاشة برنامج إن إس إكس فيريسييي الاحترافي", "/"),
            new("NSX Veresiye Takip Programı tanıtım ekranı", "", "", "شاشة عرض برنامج تتبع الديون إن إس إكس", "/"),
            new("NSX Veresiye avantajları", "", "", "مزايا الحساب الآجل لنظام إن إس إكس", "/"),
            new("NSX Veresiye · Ücretsiz, sade ve hızlı cari takip", "", "", "ائتمان إن إس إكس · تتبع التيار الحر والبسيط والسريع", "/"),
            new("NSX YAZILIMLARI", "", "", "برمجيات إن إس إكس", "/"),
            new("NSX Yazılım · Hızlı çözüm", "", "", "برمجيات إن إس إكس · حل سريع", "/"),
            new("NSX Yazılım, işletme yazılımları, ücretsiz veresiye programı, cari takip programı, barkodlu satış programı, stok takip programı, kasa defteri programı, gelir gider takip programı, sigorta acente programı, poliçe takip programı, kod güvenlik analizi, kaynak kod güvenlik taraması, okul ders programı, ders programı hazırlama programı, öğretmen nöbet çizelgesi, okul yönetim yazılımı, teknik servis takip programı, oto tamir programı, oto galeri programı, düğün salonu programı, klinik programı, randevu programı, bilgisayar hızlandırma programı, Windows masaüstü programı", "", "", "برنامج إن إس إكس، برامج الأعمال، برنامج الحسابات المجانية، برنامج متابعة العملاء، برنامج المبيعات بالباركود، برنامج متابعة المخزون، برنامج دفتر النقدية، برنامج متابعة الإيرادات والمصروفات، برنامج وكالة التأمين، برنامج متابعة البوليصة، تحليل أمان الأكواد، فحص أمان كود المصدر، برنامج جدول الحصص المدرسية، برنامج إعداد جدول الحصص، جدول المراقبة للمعلمين، برنامج إدارة المدارس، برنامج متابعة الخدمة التقنية، برنامج إصلاح السيارات، برنامج معرض السيارات، برنامج قاعات الأفراح، برنامج العيادة، برنامج المواعيد، برنامج تسريع الحاسوب، برنامج سطح المكتب لنظام ويندوز", "/"),
            new("NSX ekibi yanınızda", "", "", "فريق إن إس إكس معكم", "/"),
            new("NSX hizmet avantajları", "", "", "مزايا خدمة إن إس إكس", "/"),
            new("NSX Ücretsiz Veresiye, Barkodlu Satış ve Stok, Kasa Defteri, Sigorta Acente, Security Auditor, cari hesap, teknik servis, otomotiv ve klinik yazılımlarını keşfedin.", "", "", "اكتشف برامج إن إس إكس المجانية للائتمان، المبيعات بالباركود والمخزون، دفتر النقدية، وكيل التأمين، مدقق الأمان، الحساب الجاري، الخدمة الفنية، برامج السيارات والعيادات.", "/"),
            new("NSX çözümlerini keşfedin", "", "", "اكتشف حلول إن إس إكس", "/"),
            new("WhatsApp üzerinden NSX Yazılım desteğine ulaşın", "", "", "تواصل مع دعم برنامج إن إس إكس عبر واتساب", "/"),
            new("Ücretsiz Veresiye Programı ve İşletme Yazılımları | NSX Yazılım", "", "", "برنامج الآجل المجاني وبرمجيات الأعمال | إن إس إكس للبرمجيات", "/"),
            new("Ücretsiz Veresiye, Barkodlu Satış ve Stok, Kasa Defteri, Sigorta Acente ve Security Auditor dahil profesyonel NSX yazılımlarını keşfedin.", "", "", "اكتشف برامج إن إس إكس الاحترافية بما في ذلك البيع بالتقسيط المجاني، المبيعات والموارد المخزنية بالرموز الشريطية، دفتر الصندوق، وكيل التأمين ومدقق الأمان.", "/"),
            new("İhtiyacınıza uygun NSX yazılımını inceleyin, lisans seçiminizi netleştirin ve gerektiğinde doğrudan destek alın.", "", "", "راجع برنامج إن إس إكس الذي يناسب احتياجاتك، ووضح اختيار رخصتك، واحصل على الدعم المباشر عند الحاجة.", "/"),
            new("İhtiyacınıza uygun yazılımı bulun, özelliklerini inceleyin, lisanslayın ve NSX desteğiyle güvenle kullanmaya devam edin.", "", "", "اعثر على البرنامج المناسب لاحتياجاتك، تحقق من ميزاته، رخصه واستمر في استخدامه بأمان بدعم إن إس إكس.", "/"),
            new("Şifre ve Güvenlik | NSX Yazılım", "", "", "كلمة المرور والأمان | برنامج إن إس إكس", "/Account/ChangePassword"),
            new("DEMO ÜRÜNLER", "", "", "المنتجات التجريبية", "/Account/Downloads"),
            new("Demo kurulum dosyası", "", "", "ملف تثبيت تجريبي", "/Account/Downloads"),
            new("DİJİTAL TESLİMAT", "", "", "التسليم الرقمي", "/Account/Downloads"),
            new("NSX Yazılım; ücretsiz veresiye, teknik servis, oto tamir, oto galeri, servis live, bilgisayar hızlandırma, klinik ve randevu programı çözümleri sunar.", "", "", "برنامج إن إس إكس يقدم حلولاً مجانية للائتمان، الخدمة التقنية، إصلاح السيارات، معرض السيارات، خدمة مباشرة، تسريع الكمبيوتر، العيادات وبرامج المواعيد.", "/Account/Downloads"),
            new("TAM SÜRÜM", "", "", "النسخة الكاملة", "/Account/Downloads"),
            new("İndirmelerim | NSX Yazılım", "", "", "تنزيلاتي | برنامج إن إس إكس", "/Account/Downloads"),
            new("Bağlantı", "", "", "رابط", "/Account/ForgotPassword"),
            new("NSX HESAP GÜVENLİĞİ", "", "", "أمان حساب إن إس إكس", "/Account/ForgotPassword"),
            new("Yenileme Bağlantısı Gönder", "", "", "إرسال رابط التجديد", "/Account/ForgotPassword"),
            new("Şifremi Unuttum | NSX Yazılım", "", "", "نسيت كلمة المرور الخاصة بي | برنامج إن إس إكس", "/Account/ForgotPassword"),
            new("ŞİFRE YENİLEME", "", "", "تحديث كلمة المرور", "/Account/ForgotPassword"),
            new("E-postanızı Kontrol Edin | NSX Yazılım", "", "", "تحقق من بريدك الإلكتروني | برنامج إن إس إكس", "/Account/ForgotPasswordConfirmation"),
            new("SONRAKİ ADIM", "", "", "الخطوة التالية", "/Account/ForgotPasswordConfirmation"),
            new("Eşleşti", "", "", "مطابقة", "/Account/Licenses"),
            new("Lisanslarım | NSX Yazılım", "", "", "تراخيصي | برامج إن إس إكس", "/Account/Licenses"),
            new("LİSANS ANAHTARI", "", "", "مفتاح الترخيص", "/Account/Licenses"),
            new("NSX Yazılım hesabınıza giriş yaparak siparişlerinize, lisanslarınıza ve indirme dosyalarınıza ulaşın.", "", "", "قم بتسجيل الدخول إلى حساب برنامج إن إس إكس للوصول إلى طلباتك ورخصك وملفات التنزيل الخاصة بك.", "/Account/Login"),
            new("NSX ÜYE MERKEZİ", "", "", "مركز أعضاء إن إس إكس", "/Account/Login"),
            new("Üye Girişi | NSX Yazılım", "", "", "تسجيل الدخول للأعضاء | برمجيات إن إس إكس", "/Account/Login"),
            new("AKTİF LİSANS", "", "", "رخصة نشطة", "/Account/MyAccount"),
            new("AKTİF LİSANSLAR", "", "", "التراخيص النشطة", "/Account/MyAccount"),
            new("HESAP E-POSTASI", "", "", "بريد الحساب الإلكتروني", "/Account/MyAccount"),
            new("Hesabım | NSX Yazılım", "", "", "حسابي | برمجيات إن إس إكس", "/Account/MyAccount"),
            new("LİSANSLAR", "", "", "التراخيص", "/Account/MyAccount"),
            new("NSX ÜYE PANELİ", "", "", "لوحة أعضاء إن إس إكس", "/Account/MyAccount"),
            new("İşletmenize uygun NSX yazılımlarını inceleyerek başlayabilirsiniz.", "", "", "يمكنك أن تبدأ بفحص برامج إن إس إكس المناسبة لشركتك.", "/Account/MyAccount"),
            new("SİPARİŞ DETAYI", "", "", "تفاصيل الطلب", "/Account/OrderDetail"),
            new("Siparişlerim | NSX Yazılım", "", "", "طلباتي | برنامج إن إس إكس", "/Account/Orders"),
            new("ÜYE PANELİ", "", "", "لجنة الأعضاء", "/Account/Orders"),
            new("Hesabınız sadece NSX hizmet ve teslimat süreçleri için kullanılır.", "", "", "يُستخدم حسابك فقط لعمليات خدمة وتسليم إن إس إكس.", "/Account/Register"),
            new("NSX Yazılım hesabı oluşturun; sipariş, lisans ve program indirmelerinizi tek yerden yönetin.", "", "", "قم بإنشاء حساب برنامج إن إس إكس؛ قم بإدارة طلباتك والتراخيص وتنزيلات البرنامج من مكان واحد.", "/Account/Register"),
            new("NSX ÜYELİK", "", "", "عضوية إن إس إكس", "/Account/Register"),
            new("Ücretsiz Üyelik | NSX Yazılım", "", "", "اشتراك مجاني | برنامج إن إس إكس", "/Account/Register"),
            new("BANKA BİLGİLERİ", "", "", "معلومات البنك", "/BankTransfer"),
            new("SINIRSIZ LİSANS", "", "", "رخصة غير محدودة", "/BankTransfer"),
            new("Satın Alma Bildirimini Gönder", "", "", "إرسال إشعار الشراء", "/BankTransfer"),
            new("NSX Güvenli Satın Alma", "", "", "شراء إن إس إكس الآمن", "/BankTransfer/Success"),
            new("Ödemeniz kontrol edildikten sonra lisansınız ve indirme erişiminiz NSX hesabınıza tanımlanacaktır.", "", "", "بعد التحقق من دفعتك، سيتم ربط ترخيصك ووصولك للتنزيل بحساب إن إس إكس الخاص بك.", "/BankTransfer/Success"),
            new("Bayi Girişi - NSX Bayi", "", "", "دخول الوكيل - وكيل إن إس إكس", "/Bayi/Giris"),
            new("Bu sırada NSX yazılımlarını inceleyebilirsiniz.", "", "", "في هذه الأثناء، يمكنك مراجعة برامج إن إس إكس.", "/Blog"),
            new("NSX Bilgi Merkezi", "", "", "مركز معلومات إن إس إكس", "/Blog"),
            new("Evet. Program ücretsiz kullanım için sunulur; güncel v1.0.5 sürümünde masaüstü cari takibe ek olarak Bulut ve Mobil Yönetim özellikleri bulunur.", "", "", "نعم. يُقدّم البرنامج للاستخدام المجاني؛ وفي الإصدار الحالي الإصدار 1.0.5، بالإضافة إلى متابعة الحسابات على سطح المكتب، تتوفر ميزات الإدارة السحابية والمحمولة.", "/Blog/Detail"),
            new("Kurulum Videosu + Güncel Sürüm", "", "", "فيديو التثبيت + الإصدار الحالي", "/Blog/Detail"),
            new("NSX Veresiye Programı Ürün Sayfası", "", "", "صفحة منتج برنامج إن إس إكس بالتقسيط", "/Blog/Detail"),
            new("NSX Veresiye Takip Pro Kurulum ve Kullanım Videosu", "", "", "فيديو تثبيت واستخدام برنامج متابعة الائتمان إن إس إكس", "/Blog/Detail"),
            new("NSX Veresiye Takip Pro ücretsiz mi?", "", "", "هل برنامج تتبع الديون الاحترافي من إن إس إكس مجاني؟", "/Blog/Detail"),
            new("NSX Veresiye v1.0.5 yaklaşımı", "", "", "نهج إن إس إكس فيريسييي الإصدار 1.0.5", "/Blog/Detail"),
            new("NSX Yazılım Rehberi", "", "", "دليل برمجيات إن إس إكس", "/Blog/Detail"),
            new("NSX Yazılım yaklaşımı", "", "", "نهج برمجيات إن إس إكس", "/Blog/Detail"),
            new("NSX Yazılım; hızlı kullanım, sade arayüz, güvenli dijital teslimat, güncelleme desteği ve destek odaklı çözümler geliştirmeyi hedefler.", "", "", "برنامج إن إس إكس يهدف إلى تطوير حلول تركز على الاستخدام السريع، واجهة بسيطة، التسليم الرقمي الآمن، دعم التحديثات والدعم.", "/Blog/Detail"),
            new("Videoda masaüstü programının kurulum ve temel kullanım adımlarını izleyebilirsiniz. Güncel v1.0.5 sürümünde bunlara ek olarak QR ile Bulut ve Mobil Yönetim, canlı senkronizasyon, mobil müşteri arama, cari hareket, borç ve tahsilat özellikleri bulunur.", "", "", "يمكنك متابعة خطوات تثبيت واستخدام البرنامج المكتبي الأساسية في الفيديو. بالإضافة إلى ذلك، في الإصدار الحالي الإصدار 1.0.5 تتوفر ميزات مثل الإدارة السحابية والجوال عبر رمز الاستجابة السريع، والمزامنة الحية، والبحث عن العملاء عبر الجوال، وحركة الحسابات، والديون والتحصيل.", "/Blog/Detail"),
            new("İşini daha düzenli takip etmek, lisanslı veya ücretsiz yazılım kullanmak ve süreçlerini dijitalleştirmek isteyen işletmeler için uygundur.", "", "", "مناسب للشركات التي ترغب في متابعة عملها بشكل أكثر انتظامًا، واستخدام البرامج المرخصة أو المجانية، ورقمنة عملياتها.", "/Blog/Detail"),
            new("Bayi Kodu", "", "", "رمز التاجر", "/Dealer"),
            new("Bildirimi Admin Onayına Gönder", "", "", "إرسال الإشعار لموافقة الإدارة", "/Dealer"),
            new("Bu bildirim satışı otomatik onaylamaz. Son onay NSX admin tarafından verilir.", "", "", "هذا الإشعار لا يوافق على البيع تلقائيًا. يتم منح الموافقة النهائية من قبل مسؤول إن إس إكس.", "/Dealer"),
            new("Gönderen Adı / Firma", "", "", "اسم المرسل / الشركة", "/Dealer"),
            new("Gönderen Banka", "", "", "البنك المرسل", "/Dealer"),
            new("Havale Bekliyor", "", "", "في انتظار التحويل", "/Dealer"),
            new("Kâr Modeli", "", "", "نموذج الربح", "/Dealer"),
            new("NSX Yazılım Sitesi", "", "", "موقع برمجيات إن إس إكس", "/Dealer"),
            new("Reddedildi", "", "", "مرفوض", "/Dealer"),
            new("ADMIN ONAYINA GONDER", "", "", "أرسل لطلب موافقة المسؤول", "/Dealer/BankTransfer"),
            new("NSX Havale Bilgileri", "", "", "معلومات التحويل البنكي لـ إن إس إكس", "/Dealer/BankTransfer"),
            new("Bayi Girişi", "", "", "دخول الوكيل", "/Dealer/Login"),
            new("Kullanıcı Girişi", "", "", "تسجيل الدخول", "/Dealer/Login"),
            new("NSX BAYI KANALI", "", "", "قناة وكلاء إن إس إكس", "/Dealer/Login"),
            new("Satışı Oluştur ve Havaleye Geç", "", "", "إنشاء البيع وانتقل إلى التحويل", "/Dealer/NewSale"),
            new("/ Bitiş:", "", "", "/ النهاية:", "/Dealer/SaleDetail"),
            new("Gönderen", "", "", "المرسل", "/Dealer/SaleDetail"),
            new("Havale / Admin Onayı", "", "", "الموافقة على النقل / الإدارة", "/Dealer/SaleDetail"),
            new("Havale Bildirimi Yap", "", "", "أرسل إشعار التحويل", "/Dealer/SaleDetail"),
            new("SATIS KONTROLU", "", "", "التحكم في المبيعات", "/Dealer/SaleDetail"),
            new("BAYI HAREKETLERI", "", "", "حركات الجنين", "/Dealer/Sales"),
            new("NSX YAZILIM", "", "", "برمجيات إن إس إكس", "/Home/About"),
            new("NSX Yazılım; veresiye ve cari takipten teknik servise, oto tamir ve galeri yönetiminden klinik, randevu ve düğün salonu süreçlerine kadar farklı sektörlerin günlük çalışma düzenine uygun çözümler sunar.", "", "", "إن إس إكس للبرمجيات؛ تقدم حلولا مناسبة لنظام العمل اليومي في قطاعات مختلفة، من تتبع الائتمان والتحديثات إلى الخدمات التقنية، ومن إصلاح السيارات وإدارة المعارض إلى عمليات العيادات والمواعيد وقاعات الزفاف.", "/Home/About"),
            new("Kullandığınız NSX ürününün adı", "", "", "اسم منتج إن إس إكس الذي تستخدمه", "/Home/Contact"),
            new("NSX Destek Merkezi", "", "", "مركز دعم إن إس إكس", "/Home/Contact"),
            new("ornek@firma.com", "", "", "ورنيك@فيرما.كوم", "/Home/Contact"),
            new("NSX yazılımları hangi işletim sisteminde çalışır?", "", "", "ما هو نظام التشغيل الذي تعمل عليه برامج إن إس إكس؟", "/Home/FAQ"),
            new("6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamında NSX Yazılım, internet sitesi ve sunduğu hizmetlerle bağlantılı olarak elde edilen kişisel veriler bakımından veri sorumlusu sıfatıyla hareket eder.", "", "", "في إطار قانون حماية البيانات الشخصية رقم 6698، تتصرف شركة إن إس إكس للبرمجيات بصفتها مسؤولة عن البيانات بالنسبة للبيانات الشخصية التي تم الحصول عليها فيما يتعلق بموقعها على الإنترنت والخدمات التي تقدمها.", "/Home/Kvkk"),
            new("KVKK'nın 11. maddesi kapsamında verilerinizin işlenip işlenmediğini öğrenme, bilgi talep etme, amacına uygun kullanılıp kullanılmadığını öğrenme, aktarılan tarafları bilme, eksik veya yanlış verilerin düzeltilmesini ve şartları oluştuğunda silinmesini isteme haklarına sahipsiniz.", "", "", "لديكم الحق في معرفة ما إذا كانت بياناتكم تتم معالجتها وفقًا للمادة 11 من قانون حماية البيانات الشخصية (كفكك)، وطلب المعلومات، ومعرفة ما إذا كانت تُستخدم وفقًا لغرضها، ومعرفة الأطراف التي تم نقل البيانات إليها، والمطالبة بتصحيح البيانات الناقصة أو غير الصحيحة، والمطالبة بحذفها عند توافر الشروط.", "/Home/Kvkk"),
            new("En çok kullanılan NSX bölümlerine tek tıkla ulaşabilirsiniz.", "", "", "يمكنك الوصول إلى أقسام إن إس إكس الأكثر استخدامًا بنقرة واحدة.", "/Home/NotFound"),
            new("NSX destek", "", "", "دعم إن إس إكس", "/Home/NotFound"),
            new("Sayfa taşınmış, kaldırılmış veya bağlantı adresi değişmiş olabilir. Doğru bölüme hızlıca devam edebilirsiniz.", "", "", "قد تكون الصفحة قد نُقلت أو أُزيلت أو تغيّر عنوان الرابط. يمكنك متابعة القسم الصحيح بسرعة.", "/Home/NotFound"),
            new("Ad, soyad, e-posta, telefon, fatura ve sipariş bilgileri; hesap, lisans ve destek kayıtları ile IP adresi, tarayıcı, cihaz ve sayfa erişimi gibi teknik bilgiler işlenebilir.", "", "", "يمكن معالجة الاسم، اللقب، البريد الإلكتروني، رقم الهاتف، معلومات الفاتورة والطلب؛ سجلات الحساب والرخصة والدعم، بالإضافة إلى المعلومات التقنية مثل عنوان يب، المتصفح، الجهاز والوصول إلى الصفحة.", "/Home/Privacy"),
            new("Bu politika, NSX Yazılım internet sitesini ziyaret ettiğinizde, hesap oluşturduğunuzda, sipariş verdiğinizde veya destek talebi ilettiğinizde oluşabilecek bilgi işleme faaliyetlerini açıklar.", "", "", "تصف هذه السياسة أنشطة معالجة المعلومات التي قد تحدث عند زيارة موقع برمجيات إن إس إكس، أو إنشاء حساب، أو تقديم طلب، أو تقديم طلب دعم.", "/Home/Privacy"),
            new("3. İade kapsamı dışındaki durumlar", "", "", "3. الحالات خارج نطاق الاسترجاع", "/Home/Returns"),
            new("Bu politika, NSX Yazılım internet sitesi üzerinden satın alınan dijital yazılım, lisans anahtarı ve bunlarla bağlantılı dijital teslimatlar için geçerlidir.", "", "", "تنطبق هذه السياسة على البرامج الرقمية ومفتاح الترخيص والتسليمات الرقمية المرتبطة بها التي تم شراؤها عبر موقع برمجيات إن إس إكس على الإنترنت.", "/Home/Returns"),
            new("NSX Barkodlu Satış Cari Stok Takip", "", "", "متابعة المخزون والعملاء مع مبيعات الباركود إن إس إكس", "/Products"),
            new("NSX Barkodlu Satış Pro", "", "", "إن إس إكس المبيعات بالباركود برو", "/Products"),
            new("NSX Barkodlu Satış Pro ile barkodlu satış, ürün, stok, kasa, cari hesap, veresiye, tahsilat ve tedarikçi işlemlerini tek programdan yönetin.", "", "", "أدر المبيعات بالباركود والمنتجات والمخزون والصندوق والحسابات الجارية والمبيعات الآجلة والتحصيلات والموردين من برنامج واحد باستخدام إن إس إكس المبيعات بالباركود برو.", "/Products"),
            new("NSX Barkodlu Satış, Cari ve Stok Takibi", "", "", "إن إس إكس المبيعات مع الباركود، تتبع الحسابات والمخزون", "/Products"),
            new("NSX Cari Takip", "", "", "متابعة الحسابات الجارية إن إس إكس", "/Products"),
            new("NSX Cari Takip Pro", "", "", "إن إس إكس متابعة الحسابات برو", "/Products"),
            new("NSX Cari Takip Pro ile firma ve müşteri carilerini, borç, alacak, tahsilat, ödeme, hatırlatma ve raporlama süreçlerini tek merkezden yönetin.", "", "", "قم بإدارة حسابات الشركات والعملاء والديون والمستحقات والتحصيلات والمدفوعات والتذكيرات وعمليات إعداد التقارير من مركز واحد باستخدام تتبع الحسابات الاحترافي من إن إس إكس.", "/Products"),
            new("NSX Düğün Salonu Pro", "", "", "إن إس إكس قاعة الأفراح برو", "/Products"),
            new("NSX Düğün Salonu Pro ile rezervasyon, etkinlik, müşteri, salon, sözleşme, ödeme ve tahsilat süreçlerini tek merkezden planlayıp takip edin.", "", "", "خطط وتابع الحجوزات والفعاليات والعملاء والقاعات والعقود والمدفوعات والتحصيلات من مركز واحد باستخدام إن إس إكس قاعة الأفراح برو.", "/Products"),
            new("NSX Kasa Defteri Pro", "", "", "إن إس إكس دفتر الصندوق برو", "/Products"),
            new("NSX Kasa Defteri Pro ile gelir, gider, tahsilat, ödeme, çoklu kasa, döviz kasası ve cari hesap hareketlerini tek merkezden güvenle yönetin.", "", "", "أدر الإيرادات والمصروفات والتحصيلات والمدفوعات والصناديق المتعددة وصناديق العملات الأجنبية وحركات الحسابات بأمان من مركز واحد باستخدام إن إس إكس دفتر الصندوق برو.", "/Products"),
            new("NSX Klinik ve Randevu Takip", "", "", "متابعة العيادة والمواعيد إن إس إكس", "/Products"),
            new("NSX Klinik ve Randevu Takip Programı", "", "", "برنامج إن إس إكس للعيادات ومتابعة المواعيد", "/Products"),
            new("NSX Klinik ve Randevu Takip Programı ile hasta, doktor, randevu, muayene, ödeme ve klinik iş akışını tek merkezden düzenli biçimde yönetin.", "", "", "قم بإدارة المرضى والأطباء والمواعيد والفحوصات والمدفوعات وسير العمل في العيادة بشكل منظم من مركز واحد باستخدام برنامج إن إس إكس للعيادات وتتبع المواعيد.", "/Products"),
            new("NSX Komisyonlu Cari Takip", "", "", "متابعة الحساب الجاري بعمولة إن إس إكس", "/Products"),
            new("NSX Komisyonlu Cari Takip Pro", "", "", "إن إس إكس متابعة الحسابات والعمولات برو", "/Products"),
            new("NSX Komisyonlu Cari Takip Pro ile cari hesap, borç, tahsilat, komisyon ve raporlama süreçlerini Server Client yapısıyla merkezi olarak yönetin.", "", "", "أدر الحسابات والديون والتحصيلات والعمولات والتقارير مركزيًا باستخدام بنية الخادم والعميل مع إن إس إكس متابعة الحسابات والعمولات برو.", "/Products"),
            new("NSX Okul Plan Pro", "", "", "إن إس إكس مخطط المدرسة برو", "/Products"),
            new("NSX Okul Plan Pro ile öğretmen, sınıf, derslik, haftalık ders programı ve nöbet çizelgesini tek merkezden düzenleyin, raporlayın ve PDF olarak paylaşın.", "", "", "نظّم المعلمين والفصول والقاعات والجداول الأسبوعية وجداول المناوبات من مركز واحد باستخدام إن إس إكس مخطط المدرسة برو، وأنشئ التقارير وشاركها بصيغة PDF.", "/Products"),
            new("NSX Oto Galeri Pro", "", "", "إن إس إكس معرض السيارات برو", "/Products"),
            new("NSX Oto Galeri Pro ile araç stoklarını, müşteri görüşmelerini, ilan, alış, satış, ödeme ve tahsilat süreçlerini tek merkezden düzenli takip edin.", "", "", "تابع مخزون المركبات وتواصل العملاء والإعلانات والشراء والبيع والمدفوعات والتحصيلات من مركز واحد باستخدام إن إس إكس معرض السيارات برو.", "/Products"),
            new("NSX Oto Tamir Servis Pro", "", "", "إن إس إكس خدمة إصلاح السيارات برو", "/Products"),
            new("NSX Oto Tamir Servis Pro ile araç kabul, müşteri, iş emri, yedek parça, bakım, onarım, ödeme ve teslimat süreçlerini tek programdan yönetin.", "", "", "أدر استلام المركبات والعملاء وأوامر العمل وقطع الغيار والصيانة والإصلاح والمدفوعات والتسليم من برنامج واحد باستخدام إن إس إكس خدمة إصلاح السيارات برو.", "/Products"),
            new("NSX Performance Pro", "", "", "إن إس إكس الأداء برو", "/Products"),
            new("NSX Salon Takip", "", "", "متابعة صالون إن إس إكس", "/Products"),
            new("NSX Security Auditor", "", "", "مدقق أمان إن إس إكس", "/Products"),
            new("NSX Security Auditor Pro", "", "", "إن إس إكس مدقق الأمان برو", "/Products"),
            new("NSX Security Auditor Pro ile kaynak kod, API, bağımlılık ve yayın çıktılarındaki güvenlik risklerini, gizli anahtarları ve riskli kod akışlarını analiz edin.", "", "", "حلّل مخاطر الأمان والمفاتيح السرية المكشوفة ومسارات الشيفرة الخطرة في الشفرة المصدرية وواجهات برمجة التطبيقات والاعتماديات ومخرجات النشر باستخدام إن إس إكس مدقق الأمان برو.", "/Products"),
            new("NSX Servis Pro", "", "", "إن إس إكس خدمة الصيانة برو", "/Products"),
            new("NSX Servis Pro Live", "", "", "إن إس إكس سيرفيس برو لايف", "/Products"),
            new("NSX Servis Pro Live ile QR kodlu canlı servis durumunu, cihaz kabulünü, müşteri bilgilendirmesini, iş emrini ve teslimat akışını tek sistemden yönetin.", "", "", "أدر حالة الصيانة المباشرة عبر رمز كيو آر واستلام الأجهزة وإشعارات العملاء وأوامر العمل ومسار التسليم من نظام واحد باستخدام إن إس إكس سيرفيس برو لايف.", "/Products"),
            new("NSX Sigorta Acenta Pro", "", "", "إن إس إكس وكالة التأمين برو", "/Products"),
            new("NSX Sigorta Acente Pro", "", "", "إن إس إكس وكالة التأمين برو", "/Products"),
            new("NSX Sigorta Acente Pro ile müşteri, poliçe, teklif, tahsilat, komisyon ve yenileme süreçlerini tek merkezden yönetin; yaklaşan poliçeleri zamanında takip edin.", "", "", "قم بإدارة العملاء، وثائق التأمين، العروض، التحصيل، العمولات، وعمليات التجديد من مركز واحد باستخدام وكالة التأمين الاحترافية من إن إس إكس؛ وتتبع الوثائق القادمة في الوقت المناسب.", "/Products"),
            new("NSX Teknik Servis Pro", "", "", "إن إس إكس الخدمة الفنية برو", "/Products"),
            new("NSX Teknik Servis Pro ile müşteri, cihaz kabul, arıza, servis kaydı, işlem geçmişi, ödeme ve teslimat süreçlerini tek merkezden düzenli yönetin.", "", "", "أدر العملاء واستلام الأجهزة والأعطال وسجلات الصيانة وسجل العمليات والمدفوعات والتسليم من مركز واحد باستخدام إن إس إكس الخدمة الفنية برو.", "/Products"),
            new("NSX Teknik Servis Takip", "", "", "متابعة خدمة الصيانة الفنية لنظام إن إس إكس", "/Products"),
            new("NSX Turbo Performans Pro", "", "", "إن إس إكس تيربو للأداء برو", "/Products"),
            new("NSX Turbo Performans Programı", "", "", "برنامج أداء توربو إن إس إكس", "/Products"),
            new("NSX Turbo ile Windows bakımını ve oyun performansını iyileştirin; gereksiz yükleri azaltın, gecikmeyi düşürün ve daha akıcı bir bilgisayar deneyimi elde edin.", "", "", "حسّن صيانة ويندوز وأداء الألعاب باستخدام إن إس إكس تيربو؛ قلّل الأحمال غير الضرورية وخفّض التأخير للحصول على تجربة حاسوب أكثر سلاسة.", "/Products"),
            new("NSX Veresiye Free", "", "", "إن إس إكس الحسابات الآجلة فري", "/Products"),
            new("NSX Veresiye Pro", "", "", "إن إس إكس الحسابات الآجلة برو", "/Products"),
            new("NSX Veresiye Takip Pro", "", "", "إن إس إكس متابعة الحسابات الآجلة برو", "/Products"),
            new("NSX Veresiye Takip Pro ile müşteri cari hesaplarını, borç, tahsilat ve açık bakiyeleri masaüstü ve cep telefonundan Bulut sistemiyle ücretsiz yönetin.", "", "", "أدر حسابات العملاء والديون والتحصيلات والأرصدة المفتوحة مجانًا من الكمبيوتر والهاتف عبر النظام السحابي باستخدام إن إس إكس متابعة الحسابات الآجلة برو.", "/Products"),
            new("NSX Veresiye Takip Programı", "", "", "برنامج متابعة الديون لنظام إن إس إكس", "/Products"),
            new("NSX Veresiye Takip Programı Ücretsiz", "", "", "برنامج تتبع الائتمان في إن إس إكس مجاني", "/Products"),
            new("NSX Ücretsiz Veresiye Pro", "", "", "إن إس إكس متابعة الحسابات الآجلة المجانية برو", "/Products"),
            new("NSX Ücretsiz Veresiye Takip", "", "", "متابعة الديون المجانية إن إس إكس", "/Products"),
            new("QR canlı takip", "", "", "التتبع المباشر عن طريق رمز الاستجابة السريعة", "/Products"),
            new("SMS bildirim", "", "", "إشعار الرسائل القصيرة", "/Products"),
            new("NSX ORİJİNAL YAZILIM", "", "", "برنامج إن إس إكس الأصلي", "/Products/Detail"),
            new("NSX destek ekibi yanınızda", "", "", "فريق دعم إن إس إكس بجانبك", "/Products/Detail"),
            new("NSX güvencesiyle.", "", "", "بضمان إن إس إكس.", "/Products/Detail"),
            new("NSX masaüstü yazılımları Windows ortamında çalışır. Ürün özel gereksinimleri destek ekibinden doğrulanabilir.", "", "", "يعمل برنامج سطح مكتب إن إس إكس في بيئة ويندوز. يمكن التحقق من متطلبات المنتج الخاصة من قبل فريق الدعم.", "/Products/Detail"),
            new("NSX teknik destek", "", "", "دعم إن إس إكس الفني", "/Products/Detail"),
            new("NSX ürün galerisi", "", "", "معرض منتجات إن إس إكس", "/Products/Detail"),
            new("SMS bilgilendirme", "", "", "إشعار الرسائل القصيرة", "/Products/Detail"),
            new("WhatsApp ile bilgi alın", "", "", "احصل على المعلومات عبر واتساب", "/Products/Detail"),
            new("Windows bir uyarı mı gösterdi?", "", "", "هل ظهر ويندوز تحذير؟", "/Products/Detail"),
            new("Windows masaüstü", "", "", "سطح مكتب ويندوز", "/Products/Detail"),
            new("Windows masaüstü yazılımı", "", "", "برنامج سطح مكتب ويندوز", "/Products/Detail"),
            new("Windows uyumu", "", "", "التوافق مع ويندوز", "/Products/Detail"),
            new("Blog / Rehberler", "", "", "المدونة / الأدلة", "/Shared"),
            new("NSX Yazılım", "", "", "برنامج إن إس إكس", "/Shared/Brand"),
            new("AKTİF KAMPANYA", "", "", "الحملة النشطة", "/Shared/Campaign"),
            new("Ürünleri İncele", "", "", "انظر إلى المنتجات", "/Shared/Campaign"),
            new("ANA SAYFA", "", "", "الصفحة الرئيسية", "/Shared/Client"),
            new("NSX Yazılım Destek Merkezi", "", "", "مركز دعم برامج إن إس إكس", "/Shared/Client"),
            new("NSX Yazılım Facebook hesabı", "", "", "حساب فيسبوك لشركة إن إس إكس للبرمجيات", "/Shared/Client"),
            new("NSX Yazılım Instagram hesabı", "", "", "حساب إنستغرام لنظام إن إس إكس البرمجي", "/Shared/Client"),
            new("NSX Yazılım TikTok hesabı", "", "", "حساب تيك توك الخاص ببرنامج إن إس إكس", "/Shared/Client"),
            new("NSX Yazılım WhatsApp destek hattı", "", "", "خط دعم واتساب لبرنامج إن إس إكس", "/Shared/Client"),
            new("NSX Yazılım X hesabı", "", "", "حساب إن إس إكس للبرمجيات كس", "/Shared/Client"),
            new("NSX Yazılım YouTube kanalı", "", "", "قناة برمجيات إن إس إكس على يوتيوب", "/Shared/Client"),
            new("NSX Yazılım; işletmelerin satış, servis ve performans süreçleri için modern, güvenilir ve kullanıcı dostu dijital çözümler geliştirir.", "", "", "برنامج إن إس إكس؛ يطور حلولًا رقمية حديثة وموثوقة وسهلة الاستخدام لعمليات المبيعات والخدمات والأداء لدى المؤسسات.", "/Shared/Client"),
            new("NSX'e Hoş Geldiniz...", "", "", "مرحبًا بكم في إن إس إكس...", "/Shared/Client"),
            new("© @DateTime.Now.Year NSX Yazılım. Tüm hakları saklıdır.", "", "", "© @داتيتيمي.نوو.ييار برمجيات إن إس إكس. جميع الحقوق محفوظة.", "/Shared/Client"),
            new("Ücretsiz PC Hızlandırma", "", "", "تسريع الكمبيوتر مجانًا", "/Shared/Client"),
            new("KURUMSAL MENÜ", "", "", "القائمة المؤسسية", "/Shared/Corporate"),
            new("NSX DESTEK", "", "", "دعم إن إس إكس", "/Shared/Footer"),
            new("NSX Yazılım hizmet güvenceleri", "", "", "ضمانات خدمات برامج إن إس إكس", "/Shared/Footer"),
            new("NSX Yazılım sosyal medya hesapları", "", "", "حسابات وسائل التواصل الاجتماعي لشركة إن إس إكس للبرمجيات", "/Shared/Footer"),
            new("NSX müşteri desteği", "", "", "دعم العملاء إن إس إكس", "/Shared/Footer"),
            new("Veresiye ve cari takipten teknik servise, klinikten otomotive kadar işletmeler için modern Windows yazılımları.", "", "", "برمجيات ويندوز الحديثة للشركات، من متابعة الحسابات والدين وحتى الخدمة الفنية، ومن العيادة إلى السيارات.", "/Shared/Footer"),
            new("© 2026 NSX Yazılım. Tüm hakları saklıdır.", "", "", "© 2026 إن إس إكس للبرمجيات. جميع الحقوق محفوظة.", "/Shared/Footer"),
            new("NSX Hesabı", "", "", "حساب إن إس إكس", "/Shared/Header"),
            new("NSX Yazılım ana sayfa", "", "", "الصفحة الرئيسية لبرنامج إن إس إكس", "/Shared/Header"),
            new("NSX Çözümleri", "", "", "حلول إن إس إكس", "/Shared/Header"),
            new("Yeni NSX hesabı oluşturun", "", "", "إنشاء حساب إن إس إكس جديد", "/Shared/Header"),
            new("İndirdiğiniz dosya açılmıyorsa aşağıdaki adımlarla engellemeyi kaldırın.", "", "", "إذا لم يفتح الملف الذي نزّلته، أزل الحظر باتباع الخطوات التالية.", "/Shared/InstallGuide"),
            new("İndirdiğiniz kurulum dosyasına sağ tıklayın.", "", "", "انقر بزر الماوس الأيمن على ملف التثبيت الذي نزّلته.", "/Shared/InstallGuide"),
            new("İndirilenler klasöründeki exe kurulum dosyasını bulun.", "", "", "ابحث عن ملف التثبيت exe في مجلد التنزيلات.", "/Shared/InstallGuide"),
            new("Özellikler seçeneğine tıklayın.", "", "", "انقر على خصائص.", "/Shared/InstallGuide"),
            new("Açılan menüden Özellikler satırını seçin.", "", "", "من القائمة التي تفتح، اختر خصائص.", "/Shared/InstallGuide"),
            new("Engellemeyi kaldır kutusunu işaretleyin.", "", "", "حدد خانة إزالة الحظر.", "/Shared/InstallGuide"),
            new("Pencerenin altında Engellemeyi kaldır seçeneğini işaretleyip Tamam düğmesine basın.", "", "", "في أسفل النافذة، حدد إزالة الحظر ثم اضغط موافق.", "/Shared/InstallGuide"),
            new("Dosyayı çift tıklayarak kurulumu başlatın.", "", "", "انقر نقراً مزدوجاً على الملف لبدء التثبيت.", "/Shared/InstallGuide"),
            new("Engelleme kalktıktan sonra kurulum normal şekilde açılır.", "", "", "بعد إزالة الحظر يفتح المثبت بشكل طبيعي.", "/Shared/InstallGuide"),
            new("Özellikler penceresi örneği", "", "", "مثال نافذة الخصائص", "/Shared/InstallGuide"),
            new("Özellikler", "", "", "خصائص", "/Shared/InstallGuide"),
            new("Tür:", "", "", "النوع:", "/Shared/InstallGuide"),
            new("Uygulama", "", "", "تطبيق", "/Shared/InstallGuide"),
            new("Konum:", "", "", "الموقع:", "/Shared/InstallGuide"),
            new("Engellemeyi kaldır", "", "", "إزالة الحظر", "/Shared/InstallGuide"),
            new("Bu dosya başka bir bilgisayardan geldi. Güvenliği doğrulamak için engellendi.", "", "", "جاء هذا الملف من جهاز آخر وتم حظره للتحقق من الأمان.", "/Shared/InstallGuide"),
            new("Tamam", "", "", "موافق", "/Shared/InstallGuide"),
            new("İptal", "", "", "إلغاء", "/Shared/InstallGuide"),
            new("Kısaca:", "", "", "باختصار:", "/Shared/InstallGuide"),
            new("Sağ tık → Özellikler → Engellemeyi kaldır → Tamam → Dosyayı çalıştır.", "", "", "زر أيمن ← خصائص ← إزالة الحظر ← موافق ← شغّل الملف.", "/Shared/InstallGuide"),
            new("Resmî NSX Yazılım kurulumu", "", "", "تثبيت برنامج إن إس إكس الرسمي", "/Shared/InstallGuide"),
            new("YAZILIM", "", "", "البرمجيات", "/Shared/InstallGuide"),
            new("Kullanım videoları", "", "", "فيديوهات الاستخدام", "/Videos"),
            new("Kurulum, kullanım ve tanıtım videolarıyla NSX yazılımlarının çalışma mantığını kısa ve anlaşılır videolarla inceleyin.", "", "", "استعرضوا طريقة عمل برامج إن إس إكس من خلال مقاطع فيديو قصيرة وواضحة تتناول التثبيت والاستخدام والعرض التقديمي.", "/Videos"),
            new("NSX Video Kütüphanesi", "", "", "مكتبة فيديو إن إس إكس", "/Videos"),
            new("Video sayfası özellikleri", "", "", "خصائص صفحة الفيديو", "/Videos"),
            new("Bu kurulum videosu temel masaüstü kullanımını gösterir. Güncel programda ayrıca Cloud Bağlantısı üzerinden QR ile mobil erişim, Toplam Borç / Toplam Tahsilat / Açık Bakiye özeti, müşteri arama, cari hareket görüntüleme, borç-tahsilat girişi ve canlı senkronizasyon bulunur.", "", "", "يوضح هذا الفيديو التعليمي الاستخدام الأساسي لسطح المكتب. في البرنامج المحدث، هناك أيضًا إمكانية الوصول عبر الهاتف المحمول باستخدام رمز كيو آر من خلال الاتصال السحابي، وملخص لإجمالي المديونية / إجمالي التحصيل / الرصيد المفتوح، والبحث عن العملاء، وعرض الحركات الحسابية، وإدخال المديونية والتحصيل والمزامنة الحية.", "/Videos/Detail"),
            new("Tüm ürün özelliklerini incele →", "", "", "عرض جميع ميزات المنتج →", "/Videos/Detail"),
            new("Bakkal Veresiye Defteri Nasıl Tutulur? rehberini oku", "", "", "اقرأ دليل كيفية الاحتفاظ بدفتر ديون البقال", "/blog"),
            new("Bakkal veresiye defterini dijitalleştirin; müşteri borç, tahsilat ve açık bakiyeyi masaüstü ve cep telefonundan Bulut sistemiyle takip edin.", "", "", "حوّل دفتر الديون في البقالة إلى الرقمي؛ تابع ديون العملاء والتحصيل والأرصدة المفتوحة من خلال النظام السحابي على الكمبيوتر المكتبي والهاتف المحمول.", "/blog"),
            new("Bilgisayar Hızlandırma Programı için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لتسريع الكمبيوتر", "/blog"),
            new("Borç Alacak Takip Programı Ücretsiz rehberini oku", "", "", "اقرأ الدليل المجاني لبرنامج تتبع الديون والذمم المالية", "/blog"),
            new("Cari Hesap Takibi Nasıl Yapılır? rehberini oku", "", "", "كيف يتم متابعة الحساب الجاري؟ اقرأ الدليل", "/blog"),
            new("Cari ve Veresiye", "", "", "النقدي والآجل", "/blog"),
            new("Cari ve Veresiye · 27.06.2026", "", "", "الحالي والدائن · 27.06.2026", "/blog"),
            new("Düğün Salonu Yönetim Programı: Rezervasyondan Tahsilata Tek Sistem", "", "", "برنامج إدارة صالة الأفراح: من الحجز إلى التحصيل بنظام واحد", "/blog"),
            new("Düğün Salonu Yönetim Programı: Rezervasyondan Tahsilata Tek Sistem için NSX Yazılım ürün görseli", "", "", "برنامج إدارة قاعة الزفاف: صورة منتج برنامج إن إس إكس لنظام واحد من الحجز حتى التحصيل", "/blog"),
            new("Düğün Salonu Yönetim Programı: Rezervasyondan Tahsilata Tek Sistem rehberini oku", "", "", "برنامج إدارة قاعة الأفراح: اقرأ دليل النظام الواحد من الحجز حتى التحصيل", "/blog"),
            new("Esnaflar için ücretsiz veresiye takip programı: müşteri cari, borç, tahsilat ve açık bakiyeyi masaüstü ve cep telefonundan yönetin.", "", "", "برنامج مجاني لتتبع الحسابات المدينة للتجار: إدارة حسابات العملاء، الديون، التحصيل والرصيد المفتوح من سطح المكتب والهاتف المحمول.", "/blog"),
            new("Esnaflar İçin Veresiye Takip Programı", "", "", "برنامج متابعة الديون لأصحاب المتاجر", "/blog"),
            new("Esnaflar İçin Veresiye Takip Programı rehberini oku", "", "", "اقرأ دليل برنامج متابعة الديون لأصحاب المتاجر", "/blog"),
            new("Excel Yerine Veresiye Takip Programı Kullanmanın Avantajları", "", "", "مزايا استخدام برنامج متابعة الديون بدلاً من إكسل", "/blog"),
            new("Excel Yerine Veresiye Takip Programı Kullanmanın Avantajları rehberini oku", "", "", "اقرأ دليل مزايا استخدام برنامج متابعة الديون بدلاً من إكسل", "/blog"),
            new("Klinik ve Randevu Takip Programı ile Hasta Süreçlerini Düzenleyin", "", "", "نظم عمليات المرضى باستخدام برنامج متابعة العيادة والمواعيد", "/blog"),
            new("Klinik ve Randevu Takip Programı ile Hasta Süreçlerini Düzenleyin için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لتنظيم عمليات المرضى بواسطة برنامج متابعة العيادات والمواعيد", "/blog"),
            new("Klinik ve Randevu Takip Programı ile Hasta Süreçlerini Düzenleyin rehberini oku", "", "", "اقرأ دليل تبسيط عمليات المرضى مع برنامج تتبع العيادة والمواعيد", "/blog"),
            new("NSX Barkodlu Satış, Cari ve Stok Takip Pro ile Satıştan Stoğa Tam Kontrol", "", "", "إن إس إكس المبيعات بالباركود، متابعة الحسابات والمخزون مع الاحترافي، التحكم الكامل من المبيعات إلى المخزون", "/blog"),
            new("NSX Barkodlu Satış, Cari ve Stok Takip Pro ile Satıştan Stoğa Tam Kontrol için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس للتحكم الكامل من المبيعات إلى المخزون مع إن إس إكس لباقات المبيعات والرقم التسلسلي وتتبع العملاء والمخزون", "/blog"),
            new("NSX Barkodlu Satış, Cari ve Stok Takip Pro ile Satıştan Stoğa Tam Kontrol rehberini oku", "", "", "اقرأ دليل التحكم الكامل من المبيعات إلى المخزون مع إن إس إكس باركود المبيعات، وتتبع المخزون الحالي والمخزون الاحترافي", "/blog"),
            new("NSX Barkodlu Satış, Cari ve Stok Takip Pro ile barkodlu satış, stok, müşteri carisi, kasa, tedarikçi ve raporlama işlemlerini tek merkezden yönetin.", "", "", "إدارة عمليات مبيعات الباركود، والمخزون، وبيانات العملاء، والنقد، والموردين، وعمليات التقارير من مركز واحد باستخدام إن إس إكس باركودي ساليس، وكوررينت وستوكك تراككينج الاحترافي.", "/blog"),
            new("NSX Cari Takip Pro ile Müşteri ve Firma Hesaplarını Düzenleyin", "", "", "نظّم حسابات العملاء والشركات مع تتبع الحسابات الاحترافي من إن إس إكس", "/blog"),
            new("NSX Cari Takip Pro ile Müşteri ve Firma Hesaplarını Düzenleyin için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لتنظيم حسابات العملاء والشركات مع تتبع الحسابات الاحترافي من إن إس إكس", "/blog"),
            new("NSX Cari Takip Pro ile Müşteri ve Firma Hesaplarını Düzenleyin rehberini oku", "", "", "اقرأ دليل تنظيم حسابات العملاء والشركات مع إن إس إكس متابعة الحسابات الاحترافي", "/blog"),
            new("NSX Cari Takip Pro ile müşteri ve firma carilerini, borç-alacak hareketlerini, tahsilatları, ödemeleri, hatırlatmaları ve raporları yönetin.", "", "", "قم بإدارة حسابات العملاء والشركات، وحركات الديون والائتمان، والتحصيلات، والمدفوعات، والتذكيرات، والتقارير باستخدام تتبع الحسابات الاحترافي من إن إس إكس.", "/blog"),
            new("NSX Kasa Defteri Pro ile Gelir Gider ve Kasa Takibini Düzenli Yönetin", "", "", "نظم إدارة تتبع الإيرادات والمصروفات والصندوق بانتظام باستخدام دفتر صندوق إن إس إكس الاحترافي", "/blog"),
            new("NSX Kasa Defteri Pro ile Gelir Gider ve Kasa Takibini Düzenli Yönetin için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لتنظيم متابعة الإيرادات والنفقات والصندوق بشكل منتظم مع دفتر الصندوق الاحترافي من إن إس إكس", "/blog"),
            new("NSX Kasa Defteri Pro ile Gelir Gider ve Kasa Takibini Düzenli Yönetin rehberini oku", "", "", "اقرأ دليل إدارة الإيرادات والمصروفات وتتبع الخزانة بانتظام مع إن إس إكس دفتر الخزانة الاحترافي", "/blog"),
            new("NSX Kasa Defteri Pro ile günlük gelir-gider, tahsilat, ödeme, çoklu kasa, döviz kasaları, cari hesap, kasa transferleri, rapor ve yedek süreçlerini düzenli yönetin.", "", "", "قم بإدارة الإيرادات والمصروفات اليومية، والتحصيل، والدفع، والصندوق المتعدد، وصناديق العملات الأجنبية، والحسابات الجارية، والتحويلات الصندوقية، والتقارير وعمليات النسخ الاحتياطي بشكل منظم باستخدام دفتر الصندوق الاحترافي من إن إس إكس.", "/blog"),
            new("NSX Komisyonlu Cari Takip Pro ile cari hesap, tahsilat, komisyon ve raporlama süreçlerini Server Client yapısıyla merkezi yönetin.", "", "", "مع إن إس إكس كومميسسيون كوررينت تراككينج الاحترافي، قم بإدارة عمليات الحساب الجاري والتحصيل والعمولة والتقارير بشكل مركزي باستخدام هيكل عميل الخادم.", "/blog"),
            new("NSX Komisyonlu Cari Takip Pro için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لمتابعة الحسابات بكوميسيون إن إس إكس", "/blog"),
            new("NSX Okul Plan Pro ile Ders ve Nöbet Planlamasını Tek Merkezde Yönetin", "", "", "قم بإدارة تخطيط الدروس والورديات في مكان واحد باستخدام مخطط المدارس الاحترافي من إن إس إكس", "/blog"),
            new("NSX Okul Plan Pro ile Ders ve Nöbet Planlamasını Tek Merkezde Yönetin için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لإدارة تخطيط الدروس والغيابات في مركز واحد مع مخطط المدارس الاحترافي من إن إس إكس", "/blog"),
            new("NSX Okul Plan Pro ile Ders ve Nöbet Planlamasını Tek Merkezde Yönetin rehberini oku", "", "", "اقرأ دليل إدارة الدروس وجدول الحراسة في مركز واحد باستخدام مخطط المدارس الاحترافي من إن إس إكس", "/blog"),
            new("NSX Okul Plan Pro ile öğretmen, sınıf, derslik, ders programı, atama ve nöbet planlama süreçlerini tek merkezden profesyonelce yönetin.", "", "", "قم بإدارة عمليات المعلمين والفصول الدراسية والصفوف وبرامج الدروس والتعيينات وخطط المراقبة بشكل احترافي من مركز واحد باستخدام مخطط المدارس الاحترافي من إن إس إكس.", "/blog"),
            new("NSX Okul Plan Pro, Kasa Defteri Pro, Security Auditor Pro, ücretsiz veresiye ve barkodlu satış başta olmak üzere eğitim, kasa, cari hesap, teknik servis, otomotiv ve işletme yazılımları için kapsamlı NSX rehberleri.", "", "", "مخطط المدارس الاحترافي من إن إس إكس، كاسه ليدجير الاحترافي، مدقق الأمان الاحترافي، بما في ذلك البيع بالتقسيط المجاني والمبيعات باستخدام الباركود، بالإضافة إلى برامج التدريب، الصندوق، الحسابات الجارية، الخدمة الفنية، السيارات وإدارة الأعمال، مع أدلة إن إس إكس الشاملة.", "/blog"),
            new("NSX Security Auditor Pro ile Kodunuzu Yayına Çıkmadan Önce Denetleyin için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لتدقيق الأمان مع مدقق الأمان الاحترافي من إن إس إكس لمراجعة كودك قبل نشره", "/blog"),
            new("NSX Security Auditor Pro ile kaynak kod, API, web, masaüstü ve publish çıktılarındaki güvenlik risklerini; gizli anahtarları ve bağımlılık açıklarını yayından önce analiz edin.", "", "", "قم بتحليل مخاطر الأمان في الكود المصدري وواجهة برمجة التطبيقات والويب وسطح المكتب والمخرجات المنشورة؛ والمفاتيح السرية ونقاط ضعف الاعتماد قبل النشر باستخدام مدقق الأمان الاحترافي من إن إس إكس.", "/blog"),
            new("NSX ServisPro Live ile servis kayıtlarını, SMS bildirimlerini, QR canlı takibi, müşteri onaylarını ve cari işlemleri tek merkezden yönetin.", "", "", "قم بإدارة سجلات الخدمة، الإشعارات عبر الرسائل القصيرة، تتبع كيو آر المباشر، موافقات العملاء والمعاملات الجارية من مركز واحد باستخدام خدمة الصيانة المباشرة من إن إس إكس.", "/blog"),
            new("NSX ServisPro Live: QR Kodlu Teknik Servis Takip Programı", "", "", "إن إس إكس سيرفيسبرو لايف: برنامج تتبع الخدمة الفنية برمز الاستجابة السريعة (كيو آر)", "/blog"),
            new("NSX ServisPro Live: QR Kodlu Teknik Servis Takip Programı için NSX Yazılım ürün görseli", "", "", "خدمة الصيانة المباشرة من إن إس إكس: صورة منتج برنامج تتبع الخدمة الفنية برمز كيو آر من إن إس إكس للبرمجيات", "/blog"),
            new("NSX ServisPro Live: QR Kodlu Teknik Servis Takip Programı rehberini oku", "", "", "اقرأ دليل برنامج تتبع الخدمة التقنية بكود كيو آر خدمة الصيانة المباشرة من إن إس إكس", "/blog"),
            new("NSX Sigorta Acente Pro ile Poliçe ve Acente Yönetimini Tek Merkezde Toplayın", "", "", "جمع إدارة البوليصة والوكيل في مركز واحد مع وكالة التأمين الاحترافية من إن إس إكس", "/blog"),
            new("NSX Sigorta Acente Pro ile Poliçe ve Acente Yönetimini Tek Merkezde Toplayın için NSX Yazılım ürün görseli", "", "", "وكالة التأمين الاحترافية من إن إس إكس مع واجهة برنامج إن إس إكس لجمع إدارة البوليصات والوكلاء في مركز واحد", "/blog"),
            new("NSX Sigorta Acente Pro ile Poliçe ve Acente Yönetimini Tek Merkezde Toplayın rehberini oku", "", "", "اقرأ دليل جمع إدارة البوليصة والوكالة في مركز واحد مع وكالة التأمين الاحترافية من إن إس إكس", "/blog"),
            new("NSX Sigorta Acente Pro ile müşteri, poliçe, teklif, tahsilat, kasa, komisyon ve poliçe yenileme süreçlerini tek merkezden yönetin.", "", "", "قم بإدارة عمليات العميل والبوليصات والعروض والتحصيل والصندوق والعمولات وتجديد البوليصة من مركز واحد باستخدام وكالة التأمين الاحترافية من إن إس إكس.", "/blog"),
            new("NSX Teknik Servis Pro ile Servis Kayıtlarını Tek Merkezde Yönetin", "", "", "قم بإدارة سجلات الخدمة في مكان واحد باستخدام إدارة الصيانة الاحترافية من إن إس إكس", "/blog"),
            new("NSX Teknik Servis Pro ile Servis Kayıtlarını Tek Merkezde Yönetin için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لإدارة سجلات الخدمة بمركز واحد باستخدام إدارة الصيانة الاحترافية من إن إس إكس", "/blog"),
            new("NSX Teknik Servis Pro ile Servis Kayıtlarını Tek Merkezde Yönetin rehberini oku", "", "", "اقرأ دليل إدارة سجلات الخدمة في مكان واحد باستخدام إدارة الصيانة الاحترافية من إن إس إكس", "/blog"),
            new("NSX Teknik Servis Pro ile müşteri, cihaz kabul, arıza, servis durumu, ödeme, teslimat, geçmiş kayıt ve raporlama süreçlerini yönetin.", "", "", "قم بإدارة عمليات قبول الجهاز والخلل وحالة الخدمة والدفع والتسليم والسجلات السابقة والتقارير مع إدارة الصيانة الاحترافية من إن إس إكس.", "/blog"),
            new("NSX Veresiye Takip Pro v1.0.5 ile Cari Hesapları Her Yerden Yönetin", "", "", "إدارة الحسابات الجارية من أي مكان باستخدام إن إس إكس كريديت تراككينج الاحترافي الإصدار 1.0.5", "/blog"),
            new("NSX Veresiye Takip Pro v1.0.5 ile Cari Hesapları Her Yerden Yönetin rehberini oku", "", "", "اقرأ دليل إدارة الحسابات الجارية من أي مكان باستخدام تتبع الديون الاحترافي من إن إس إكس الإصدار 1.0.5", "/blog"),
            new("NSX Veresiye Takip Pro v1.0.5 ile müşteri cari hesaplarını, borç ve tahsilatları masaüstü ve cep telefonundan Bulut sistemiyle canlı yönetin.", "", "", "قم بإدارة حسابات العملاء والديون والتحصيلات مباشرةً من سطح المكتب والهاتف المحمول عبر النظام السحابي باستخدام تتبع الديون الاحترافي من إن إس إكس الإصدار 1.0.5.", "/blog"),
            new("NSX Yazılım Blog | İşletme ve Yazılım Rehberleri", "", "", "مدونة برمجيات إن إس إكس | أدلة الأعمال والبرمجيات", "/blog"),
            new("NSX Yazılım işletme ve yazılım rehberleri", "", "", "برمجيات إن إس إكس وأدلة تشغيل البرمجيات", "/blog"),
            new("NSX Yazılım, işletme yazılımları, ücretsiz veresiye programı, cari takip programı, barkodlu satış programı, stok takip programı, kasa defteri programı, gelir gider takip programı, sigorta acente programı, poliçe takip programı, kod güvenlik analizi, kaynak kod güvenlik taraması, okul ders programı, ders programı hazırlama programı, öğretmen nöbet çizelgesi, okul yönetim yazılımı, teknik servis takip programı, oto tamir programı, oto galeri programı, düğün salonu programı, klinik programı, randevu programı, bilgisayar hızlandırma programı, Windows masaüstü programı, yazılım rehberleri, işletme yazılımı rehberi, program kullanım rehberi", "", "", "برنامج إن إس إكس، برامج الأعمال، برنامج السلاسل المجانية، برنامج متابعة الحسابات، برنامج المبيعات بالباركود، برنامج متابعة المخزون، برنامج دفتر الصندوق، برنامج متابعة الإيرادات والمصروفات، برنامج وكيل التأمين، متابعة البوليصة، تحليل أمان الكود، فحص أمان كود المصدر، برنامج جدول الدروس المدرسية، برنامج إعداد جدول الدروس، جدول الدوريات للمعلمين، برنامج إدارة المدرسة، برنامج متابعة الخدمة الفنية، برنامج صيانة السيارات، برنامج معرض السيارات، برنامج قاعة الأفراح، برنامج العيادة، برنامج المواعيد، برنامج تسريع الكمبيوتر، برنامج سطح المكتب لنظام ويندوز، أدلة البرامج، دليل برامج الأعمال، دليل استخدام البرنامج", "/blog"),
            new("Oto Galeri Programı ile Araç Stok ve Satış Süreçlerini Yönetin", "", "", "قم بإدارة عمليات مخزون وبيع السيارات بواسطة برنامج معرض السيارات", "/blog"),
            new("Oto Galeri Programı ile Araç Stok ve Satış Süreçlerini Yönetin için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لإدارة مخزون السيارات وعمليات البيع مع برنامج معرض السيارات", "/blog"),
            new("Oto Galeri Programı ile Araç Stok ve Satış Süreçlerini Yönetin rehberini oku", "", "", "اقرأ دليل إدارة مخزون السيارات وعمليات البيع باستخدام برنامج معرض السيارات", "/blog"),
            new("Oto Tamir Servis Programı ile Araç Kabulden Teslimata Tam Takip", "", "", "متابعة كاملة للمركبة من القبول حتى التسليم مع برنامج خدمة صيانة السيارات", "/blog"),
            new("Oto Tamir Servis Programı ile Araç Kabulden Teslimata Tam Takip için NSX Yazılım ürün görseli", "", "", "صورة منتج برمجيات إن إس إكس للتتبع الكامل من قبول المركبة إلى التسليم مع برنامج خدمة إصلاح السيارات", "/blog"),
            new("Oyun Hızlandırma ve FPS Artırma Programı için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لتسريع الألعاب وزيادة معدل الإطارات", "/blog"),
            new("Oyun Hızlandırma ve FPS Artırma Programı rehberini oku", "", "", "اقرأ دليل تعزيز الألعاب وزيادة معدل الإطارات", "/blog"),
            new("Teknik Servis Takip Programı için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لبرنامج تتبع خدمة الصيانة", "/blog"),
            new("Teknik Servis Takip Programı rehberini oku", "", "", "اقرأ دليل برنامج متابعة الخدمة الفنية", "/blog"),
            new("Veresiye Defteri Programı", "", "", "برنامج دفتر الحسابات الآجلة", "/blog"),
            new("Veresiye Defteri Programı rehberini oku", "", "", "اقرأ دليل برنامج دفتر الحسابات الآجلة", "/blog"),
            new("Veresiye programı nedir? Bulut ve mobil cari takip, QR bağlantısı, canlı senkronizasyon, borç, tahsilat ve açık bakiye yönetimini keşfedin.", "", "", "ما هو برنامج الآجل؟ اكتشف متابعة الحسابات على السحابة والجوال، ووصلة كيو آر، والمزامنة الحية، وإدارة الديون والتحصيل والرصيد المتبقي.", "/blog"),
            new("Ücretsiz Cari Hesap Programı", "", "", "برنامج الحساب الجاري المجاني", "/blog"),
            new("Ücretsiz Cari Hesap Programı rehberini oku", "", "", "اقرأ دليل برنامج الحساب الجاري المجاني", "/blog"),
            new("Ücretsiz Cari Takip Programı", "", "", "برنامج متابعة الحسابات مجانًا", "/blog"),
            new("Ücretsiz veresiye programı NSX Veresiye Takip Pro", "", "", "برنامج الحسابات المجانية تتبع الديون الاحترافي من إن إس إكس", "/blog"),
            new("Ücretsiz veresiye programı nedir? NSX Veresiye Takip Pro ile cari hesap, borç ve tahsilatları masaüstü ve telefondan nasıl yöneteceğinizi öğrenin.", "", "", "ما هو برنامج الحسابات المجاني بالتقسيط؟ تعلّم كيفية إدارة الحسابات الجارية والديون والتحصيلات من خلال سطح المكتب والهاتف باستخدام تتبع الديون الاحترافي من إن إس إكس.", "/blog"),
            new("Bir kasadan diğerine para aktarıldığında transfer işlemini kullanarak iki kasa arasındaki hareketi kayıt altına alın. Bu yöntem manuel bakiye düzeltmeleri yerine daha izlenebilir bir çalışma düzeni sağlar.", "", "", "عند تحويل الأموال من صندوق إلى آخر، استخدم عملية التحويل لتسجيل الحركة بين الصندوقين. توفر هذه الطريقة نظام عمل أكثر قابلية للتتبع بدلاً من التصحيحات اليدوية للرصيد.", "/blog/nsx-kasa-defteri-pro-programi"),
            new("Cari hesap yapısı sayesinde müşteri veya firma bazlı tahsilat ve ödeme hareketleri finansal kayıtlarla ilişkilendirilebilir. Kasa hareketleri, gelir-gider dengesi ve mevcut bakiyeler raporlar üzerinden kontrol edilerek işletmenin finansal görünümü daha net izlenebilir. Düzenli yedekleme ise kasa ve cari kayıtlarının güvenliğini destekler. NSX Kasa Defteri Pro, günlük finans takibini sadeleştirirken kayıt disiplinini korumak isteyen esnaf ve işletmeler için pratik bir Windows masaüstü çözümüdür.", "", "", "بفضل هيكل الحساب الجاري، يمكن ربط تحركات التحصيل والدفع على أساس العميل أو الشركة بالسجلات المالية. يمكن مراقبة حركة الصندوق وتوازن الإيرادات والمصروفات والأرصدة الحالية عبر التقارير، مما يسمح بمشاهدة صورة مالية أوضح للشركة. أما النسخ الاحتياطي المنتظم فيدعم أمان سجلات الصندوق والحساب الجاري. دفتر الصندوق الاحترافي من إن إس إكس هو حل عملي على سطح المكتب في نظام ويندوز لتبسيط متابعة المالية اليومية مع الحفاظ على الانضباط في التسجيل، موجه للتجار والشركات.", "/blog/nsx-kasa-defteri-pro-programi"),
            new("Demo İndir", "", "", "تحميل العرض التجريبي", "/blog/nsx-kasa-defteri-pro-programi"),
            new("Gün içinde tüm para giriş ve çıkışlarını aynı gün kaydedip gün sonunda kasa bakiyelerini ve gelir-gider hareketlerini raporlarla karşılaştırmak düzenli kullanım için iyi bir yöntemdir.", "", "", "تسجيل جميع عمليات الدخول والخروج للأموال خلال اليوم نفسه ومقارنة أرصدة الصندوق وحركات الإيرادات والمصروفات في نهاية اليوم مع التقارير هو طريقة جيدة للاستخدام المنتظم.", "/blog/nsx-kasa-defteri-pro-programi"),
            new("NSX Kasa Defteri Pro ile Gelir Gider ve Kasa Takibini", "", "", "متابعة الإيرادات والمصروفات والصندوق مع دفتر الصندوق إن إس إكس", "/blog/nsx-kasa-defteri-pro-programi"),
            new("NSX Kasa Defteri Pro | Gelir Gider, Kasa ve Cari Takip Rehberi", "", "", "دليل دفتر الصندوق إن إس إكس الاحترافي | الدخل والمصروفات، متابعة الصندوق والعملاء", "/blog/nsx-kasa-defteri-pro-programi"),
            new("NSX Kasa Defteri Pro, kasa defteri programı, gelir gider takip programı, kasa takip programı, tahsilat takip programı, ödeme takip programı, çoklu kasa programı, döviz kasa takibi, cari hesap takip programı, kasalar arası transfer, işletme gelir gider programı, Windows kasa defteri programı, NSX Yazılım", "", "", "إن إس إكس دفتر الصندوق الاحترافي، برنامج دفتر الصندوق، برنامج متابعة الإيرادات والمصروفات، برنامج متابعة الصندوق، برنامج متابعة التحصيل، برنامج متابعة الدفع، برنامج الصندوق المتعدد، متابعة صندوق العملات الأجنبية، برنامج متابعة الحسابات المدينة، التحويل بين الصناديق، برنامج الإيرادات والمصروفات للشركة، برنامج دفتر الصندوق لنظام ويندوز، برمجيات إن إس إكس", "/blog/nsx-kasa-defteri-pro-programi"),
            new("NSX Kasa Defteri Pro; işletmenin günlük para giriş ve çıkışlarını, kasa bakiyelerini, tahsilat ve ödemelerini tek merkezde düzenli takip etmek için hazırlanmış profesyonel bir kasa defteri programıdır. Kağıt defter, dağınık not veya farklı Excel dosyaları yerine her finansal hareket ilgili kasa üzerinden kayıt altına alınır; böylece işletmenin güncel nakit durumu daha anlaşılır hale gelir.", "", "", "إن إس إكس دفتر الخزينة الاحترافي؛ هو برنامج دفتر خزانة احترافي تم إعداده لمتابعة المداخيل والمصروفات اليومية والأرصدة والتحصيلات والمدفوعات للشركة بشكل منظم في مركز واحد. بدلاً من الدفاتر الورقية أو الملاحظات المبعثرة أو ملفات إكسل المختلفة، يتم تسجيل كل حركة مالية عبر الخزينة المعنية؛ وبذلك يصبح وضع النقد الحالي للشركة أكثر وضوحاً.", "/blog/nsx-kasa-defteri-pro-programi"),
            new("NSX Veresiye Takip Pro ile müşteri cari hesaplarını, borç ve tahsilatları masaüstü ve cep telefonundan Bulut sistemiyle ücretsiz yönetin.", "", "", "قم بإدارة حسابات العملاء والديون والتحصيلات الخاصة بهم مجانًا عبر النظام السحابي باستخدام تتبع الديون الاحترافي من إن إس إكس من سطح المكتب والهاتف المحمول.", "/blog/nsx-kasa-defteri-pro-programi"),
            new("Oto galeri programı ile araç stok, müşteri, satış, ödeme ve galeri süreçlerini tek merkezden daha düzenli takip edin.", "", "", "تابع مخزون السيارات والعملاء والمبيعات والدفع وعمليات المعرض بشكل أكثر تنظيمًا من مركز واحد باستخدام برنامج معرض السيارات.", "/blog/nsx-kasa-defteri-pro-programi"),
            new("https://www.nsxyazilim.com/blog/nsx-kasa-defteri-pro-programi", "", "", "هتتبس://ووو.إن إس إكسيازيليم.كوم/بلوج/إن إس إكس-كاسا-ديفتيري-الاحترافي-الاحترافيجرامي", "/blog/nsx-kasa-defteri-pro-programi"),
            new("NSX Yazılım internet sitesi gizlilik politikası; toplanan bilgiler, kullanım amaçları, çerezler ve veri güvenliği hakkında bilgiler.", "", "", "سياسة خصوصية موقع إن إس إكس للبرمجيات؛ معلومات حول البيانات التي يتم جمعها، أغراض الاستخدام، ملفات تعريف الارتباط وأمن البيانات.", "/gizlilik-politikasi"),
            new("Hakkımızda | NSX Yazılım", "", "", "من نحن | إن إس إكس للبرمجيات", "/hakkimizda"),
            new("NSX Yazılım'ın işletmelere yönelik masaüstü yazılım çözümlerini, çalışma yaklaşımını ve destek anlayışını tanıyın.", "", "", "تعرّف على حلول البرامج المكتبية لشركة برمجيات إن إس إكس الموجهة للأعمال، ونهجها في العمل وفهمها للدعم.", "/hakkimizda"),
            new("https://www.nsxyazilim.com/hakkimizda", "", "", "هتتبس://ووو.إن إس إكسيازيليم.كوم/هاككيميزدا", "/hakkimizda"),
            new("NSX Yazılım dijital ürün ve lisans siparişleri için iade koşulları, başvuru adımları ve değerlendirme süreci.", "", "", "شروط الإرجاع لطلبات المنتجات الرقمية والتراخيص من برمجيات إن إس إكس، وخطوات التقديم وعملية التقييم.", "/iade-politikasi"),
            new("https://www.nsxyazilim.com/iade-politikasi", "", "", "هتتبس://ووو.إن إس إكسيازيليم.كوم/يادي-بوليتيكاسي", "/iade-politikasi"),
            new("İade Politikası | NSX Yazılım", "", "", "سياسة الاسترجاع | برمجيات إن إس إكس", "/iade-politikasi"),
            new("NSX Yazılım satış, ürün seçimi, kurulum, lisans ve teknik destek sorularınız için iletişim kanalları.", "", "", "قنوات الاتصال لأسئلتكم حول مبيعات برنامج إن إس إكس، اختيار المنتج، التثبيت، الترخيص والدعم الفني.", "/iletisim"),
            new("İletişim ve Destek | NSX Yazılım", "", "", "الاتصال والدعم | برنامج إن إس إكس", "/iletisim"),
            new("Klinik Programı için NSX Yazılım ürün görseli", "", "", "الصورة البصرية لمنتج برنامج إن إس إكس لبرنامج العيادة", "/klinik-programi"),
            new("https://www.nsxyazilim.com/klinik-programi", "", "", "هتتبس://ووو.إن إس إكسيازيليم.كوم/كلينيك-الاحترافيجرامي", "/klinik-programi"),
            new("klinik programı, hasta takip programı, doktor takip programı, klinik takip programı, NSX Yazılım", "", "", "برنامج العيادة، برنامج متابعة المرضى، برنامج متابعة الأطباء، برنامج متابعة العيادة، برنامج إن إس إكس", "/klinik-programi"),
            new("KVKK Aydınlatma Metni | NSX Yazılım", "", "", "نص التوضيح لقانون حماية البيانات الشخصية | برمجيات إن إس إكس", "/kvkk"),
            new("NSX Yazılım kişisel verilerin işlenmesi, korunması ve KVKK kapsamındaki başvuru hakları hakkında aydınlatma metni.", "", "", "نص توضيحي من إن إس إكس للبرمجيات حول معالجة البيانات الشخصية وحمايتها وحقوق التقديم بموجب قانون حماية البيانات الشخصية (كفكك).", "/kvkk"),
            new("Oto Galeri Programı için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لبرنامج معرض السيارات", "/oto-galeri-programi"),
            new("Oto Galeri Programı | Araç Stok, Müşteri ve Satış Takibi", "", "", "برنامج صالة عرض السيارات | تتبع مخزون السيارة والعملاء والمبيعات", "/oto-galeri-programi"),
            new("Oto galeri programı; araç stoklarını, müşteri görüşmelerini, satış süreçlerini, ödeme durumlarını ve galeri içi takip ihtiyaçlarını daha düzenli yönetmek için geliştirilir. NSX Yazılım yaklaşımı, oto galeri işletmelerinin araç bilgilerini, müşteri kayıtlarını ve satış süreçlerini sade ve anlaşılır bir sistemde takip etmesini hedefler.", "", "", "برنامج معرض السيارات؛ يتم تطويره لإدارة مخزون السيارات، ومحادثات العملاء، وعمليات البيع، وحالات الدفع، واحتياجات المتابعة داخل المعرض بشكل أكثر انتظامًا. يهدف نهج برمجيات إن إس إكس إلى تمكين شركات معارض السيارات من متابعة معلومات السيارات، وسجلات العملاء، وعمليات البيع في نظام بسيط وواضح.", "/oto-galeri-programi"),
            new("https://www.nsxyazilim.com/oto-galeri-programi", "", "", "هتتبس://ووو.إن إس إكسيازيليم.كوم/برنامج-معرض-السيارات", "/oto-galeri-programi"),
            new("oto galeri programı, galeri programı, araç takip programı, araç satış takip programı, NSX Yazılım", "", "", "برنامج معرض السيارات، برنامج المعرض، برنامج تتبع المركبات، برنامج تتبع مبيعات المركبات، إن إس إكس للبرمجيات", "/oto-galeri-programi"),
            new("Oto Tamir Programı için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لبرنامج تصليح السيارات", "/oto-tamir-programi"),
            new("Oto Tamir Programı | Araç Kabul, Servis ve Müşteri Takibi", "", "", "برنامج إصلاح السيارات | قبول المركبات، الخدمة، وتتبع العملاء", "/oto-tamir-programi"),
            new("Oto tamir programı; araç kabul, müşteri bilgisi, plaka ve araç kaydı, servis işlemleri, ödeme takibi ve teslimat süreçlerini daha düzenli yönetmek isteyen oto servis işletmeleri için hazırlanır. NSX Yazılım çözümleri, oto tamir servislerinde günlük iş akışını sadeleştirmeyi, kayıtların kaybolmasını önlemeyi ve servis durumunu daha anlaşılır takip etmeyi hedefler.", "", "", "برنامج إصلاح السيارات؛ يتم إعداده لمؤسسات صيانة السيارات التي ترغب في إدارة قبول السيارات، معلومات العملاء، تسجيل اللوحات والمركبات، عمليات الخدمة، متابعة المدفوعات وعمليات التسليم بشكل أكثر تنظيمًا. تهدف حلول إن إس إكس للبرمجيات إلى تبسيط سير العمل اليومي في ورش إصلاح السيارات، منع فقدان السجلات، ومتابعة حالة الخدمة بشكل أكثر وضوحًا.", "/oto-tamir-programi"),
            new("https://www.nsxyazilim.com/oto-tamir-programi", "", "", "هتتبس://ووو.إن إس إكسيازيليم.كوم/برنامج-تصليح-السيارات", "/oto-tamir-programi"),
            new("oto tamir programı, oto tamir servis programı, oto servis programı, araç servis takip programı, NSX Yazılım", "", "", "برنامج إصلاح السيارات، برنامج خدمة إصلاح السيارات، برنامج خدمة السيارات، برنامج تتبع خدمة المركبات، برنامج إن إس إكس", "/oto-tamir-programi"),
            new("Randevu Programı için NSX Yazılım ürün görseli", "", "", "الصورة البصرية لمنتج برنامج إن إس إكس لجدولة المواعيد", "/randevu-programi"),
            new("Randevu programı; doktor, personel, müşteri veya hasta randevularını günlük, haftalık ve aylık düzende takip etmek isteyen işletmeler için geliştirilir. Klinik randevu programı, güzellik merkezi randevu takibi veya servis randevu yönetimi gibi alanlarda çakışmaları azaltmaya ve planlamayı düzenli tutmaya yardımcı olur. NSX Yazılım çözümleri, sade ekranlar ve hızlı arama yapısıyla randevu takibini kolaylaştırmayı hedefler.", "", "", "برنامج المواعيد؛ يتم تطويره للشركات التي ترغب في متابعة مواعيد الأطباء، الموظفين، العملاء أو المرضى بشكل يومي، أسبوعي وشهري. يساعد برنامج مواعيد العيادات، متابعة مواعيد مراكز التجميل أو إدارة مواعيد الخدمات على تقليل التداخلات والحفاظ على تنظيم التخطيط. تهدف حلول برامج إن إس إكس إلى تسهيل متابعة المواعيد من خلال شاشات بسيطة وميزة البحث السريع.", "/randevu-programi"),
            new("https://www.nsxyazilim.com/randevu-programi", "", "", "هتتبس://ووو.إن إس إكسيازيليم.كوم/رانديفو-الاحترافيجرامي", "/randevu-programi"),
            new("randevu programı, klinik randevu programı, hasta randevu programı, randevu takip programı, NSX Yazılım", "", "", "برنامج المواعيد، برنامج المواعيد العيادي، برنامج مواعيد المرضى، برنامج متابعة المواعيد، برمجيات إن إس إكس", "/randevu-programi"),
            new("Servis Live Programı için NSX Yazılım ürün görseli", "", "", "الصورة البصرية لمنتج برنامج إن إس إكس لبرنامج الخدمة المباشرة", "/servis-live-programi"),
            new("Servis Live Programı | Canlı Servis ve İş Takibi | NSX Yazılım", "", "", "برنامج الخدمة المباشرة | الخدمة المباشرة وتتبع الأعمال | برنامج إن إس إكس", "/servis-live-programi"),
            new("Servis Live programı; servis işletmelerinde iş emri, durum takibi, müşteri bilgilendirme, teslimat süreci ve günlük servis akışını daha canlı ve düzenli takip etmek için hazırlanır. NSX Yazılım çözümleri, servis kayıtlarının daha hızlı görülmesini ve işletme içinde takip kolaylığı sağlamayı hedefler.", "", "", "برنامج سيرفيس مباشر؛ يُعد لمتابعة أوامر العمل، تتبع الحالة، إبلاغ العملاء، عملية التسليم والتدفق اليومي للخدمة في مؤسسات الخدمة بطريقة أكثر حيوية وتنظيمًا. تهدف حلول إن إس إكس للبرمجيات إلى رؤية سجلات الخدمة بشكل أسرع وتسهيل المتابعة داخل المؤسسة.", "/servis-live-programi"),
            new("https://www.nsxyazilim.com/servis-live-programi", "", "", "هتتبس://ووو.إن إس إكسيازيليم.كوم/سيرفيس-مباشر-الاحترافيجرامي", "/servis-live-programi"),
            new("servis live programı, oto servis live programı, canlı servis takip programı, servis takip programı, NSX Yazılım", "", "", "برنامج الخدمة الحية، برنامج الخدمة التلقائية المباشر، برنامج تتبع الخدمة المباشرة، برنامج تتبع الخدمة، برنامج إن إس إكس", "/servis-live-programi"),
            new("NSX yazılımlarının kurulumu, lisansı, teslimatı, desteği ve iade süreci hakkında sık sorulan soruların yanıtları.", "", "", "إجابات الأسئلة المتكررة حول تثبيت برامج إن إس إكس، والترخيص، والتسليم، والدعم، وعملية الإرجاع.", "/sikca-sorulan-sorular"),
            new("Sıkça Sorulan Sorular | NSX Yazılım", "", "", "الأسئلة المتكررة | برنامج إن إس إكس", "/sikca-sorulan-sorular"),
            new("Cari hesaptan teknik servise, otomotivden klinik ve organizasyona kadar işletmeniz için geliştirilen NSX çözümlerini tek ekranda karşılaştırın.", "", "", "قارن حلول إن إس إكس المطورة لشركتك، من الحساب الجاري إلى الخدمة الفنية، ومن السيارات إلى العيادة والتنظيم، على شاشة واحدة.", "/store"),
            new("Kategoriye göre filtreleyin, ürünleri karşılaştırın ve ihtiyacınıza en uygun NSX yazılımının detaylarını inceleyin.", "", "", "قم بالتصفية حسب الفئة، قارن المنتجات واستعرض تفاصيل برنامج إن إس إكس الأنسب لاحتياجاتك.", "/store"),
            new("NSX Kasa Defteri, Sigorta Acente ve Security Auditor Pro ile ücretsiz veresiye, barkodlu satış, cari takip, teknik servis, otomotiv ve klinik yazılımlarını inceleyin.", "", "", "استعرض دفتر حسابات إن إس إكس، ووكلاء التأمين ومدقق الأمان الاحترافي مع برامج مجانية للبيع الآجل، والبيع بالباركود، ومتابعة الحسابات، والخدمة الفنية، وبرامج السيارات والعيادات.", "/store"),
            new("NSX Yazılım Kütüphanesi", "", "", "مكتبة برامج إن إس إكس", "/store"),
            new("NSX Yazılımları", "", "", "برمجيات إن إس إكس", "/store"),
            new("NSX desteği", "", "", "دعم إن إس إكس", "/store"),
            new("NSX işletme yazılımları", "", "", "برمجيات تشغيل إن إس إكس", "/store"),
            new("NSX yazılım avantajları", "", "", "مزايا برنامج إن إس إكس", "/store"),
            new("NSX İşletme Yazılımları | Satış, Finans, Servis ve Güvenlik", "", "", "برمجيات الأعمال إن إس إكس | المبيعات والمالية والخدمة والأمن", "/store"),
            new("Profesyonel NSX çözümleri", "", "", "حلول إن إس إكس المهنية", "/store"),
            new("Windows uyumlu", "", "", "متوافق مع ويندوز", "/store"),
            new("https://www.nsxyazilim.com/ucretsiz-bilgisayar-hizlandirma-programi", "", "", "هتتبس://ووو.إن إس إكسيازيليم.كوم/برنامج-تسريع-الكمبيوتر-المجاني", "/ucretsiz-bilgisayar-hizlandirma-programi"),
            new("Ücretsiz Bilgisayar Hızlandırma Programı için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لتسريع الكمبيوتر المجاني", "/ucretsiz-bilgisayar-hizlandirma-programi"),
            new("Ücretsiz bilgisayar hızlandırma programı; Windows performansını daha akıcı hale getirmek, gereksiz yükleri azaltmak, oyun performansını desteklemek ve FPS artırma odaklı pratik bakım yapmak isteyen kullanıcılar için hazırlanır. NSX Turbo; bilgisayar hızlandırma, oyun hızlandırma, başlangıç yüklerini azaltma ve sistem optimizasyonu gibi işlemleri daha sade bir kullanım deneyimiyle sunmayı hedefler.", "", "", "برنامج تسريع الكمبيوتر المجاني؛ يتم إعداده للمستخدمين الذين يرغبون في جعل أداء ويندوز أكثر سلاسة، تقليل الأحمال غير الضرورية، دعم أداء الألعاب وإجراء صيانة عملية تركز على زيادة معدل الإطارات في الثانية (فبس). يهدف إن إس إكس توربو إلى تقديم عمليات مثل تسريع الكمبيوتر، تسريع الألعاب، تقليل أعباء بدء التشغيل وتحسين النظام بطريقة تجربة استخدام أبسط.", "/ucretsiz-bilgisayar-hizlandirma-programi"),
            new("https://www.nsxyazilim.com/ucretsiz-teknik-servis-programi", "", "", "هتتبس://ووو.إن إس إكسيازيليم.كوم/وكريتسيز-تيكنيك-سيرفيس-الاحترافيجرامي", "/ucretsiz-teknik-servis-programi"),
            new("Ücretsiz Teknik Servis Programı için NSX Yazılım ürün görseli", "", "", "صورة منتج برنامج إن إس إكس لبرنامج الخدمة الفنية المجاني", "/ucretsiz-teknik-servis-programi"),
            new("Ücretsiz Teknik Servis Programı | Servis ve Cihaz Takibi", "", "", "برنامج الخدمة الفنية المجانية | متابعة الخدمة والأجهزة", "/ucretsiz-teknik-servis-programi"),
            new("ücretsiz teknik servis programı, teknik servis takip programı, servis takip programı, cihaz takip programı, NSX Yazılım", "", "", "برنامج خدمة فنية مجاني، برنامج متابعة الخدمة الفنية، برنامج متابعة الخدمة، برنامج متابعة الأجهزة، برنامج إن إس إكس للبرمجيات", "/ucretsiz-teknik-servis-programi"),
            new("Cloud Bağlantısı ekranından oluşturulan güvenli QR kod telefonla okutularak işletmeye ait mobil panele bağlanılır. Mobil ana ekranda Toplam Borç, Toplam Tahsilat ve Açık Bakiye özetleri görüntülenir. Alt bölümde müşteri adına göre canlı arama yapılabilir; müşteri seçildiğinde cari hareketleri açılır ve geçmiş borç ile tahsilat kayıtları tek ekranda görülebilir.", "", "", "من خلال شاشة الاتصال السحابي، يتم إنشاء رمز كيو آر آمن ويتم مسحه بواسطة الهاتف للاتصال باللوحة المتنقلة الخاصة بالمؤسسة. في الشاشة الرئيسية للجوّال، يتم عرض ملخصات إجمالي الدين، وإجمالي التحصيل، والرصيد المفتوح. في الجزء السفلي، يمكن إجراء مكالمات مباشرة حسب اسم العميل؛ وعند اختيار العميل، تُفتح حركات الحساب ويمكن الاطلاع على سجلات الديون والتحصيل السابقة في شاشة واحدة.", "/ucretsiz-veresiye-programi"),
            new("Evet. NSX Veresiye Takip Pro ücretsiz kullanım için sunulur; masaüstü cari takibin yanında güncel v1.0.5 sürümünde Bulut ve Mobil Yönetim özellikleri de bulunur.", "", "", "نعم. برنامج إن إس إكس كريديت تراككينج الاحترافي متاح للاستخدام المجاني؛ بالإضافة إلى تتبع التيار على سطح المكتب، يتضمن إصدار الإصدار 1.0.5 الحالي أيضا ميزات إدارة السحابة والهواتف المحمولة.", "/ucretsiz-veresiye-programi"),
            new("Güncel sürümde masaüstü programına Bulut ve Mobil Yönetim Sistemi eklenmiştir. QR bağlantısı ile yetkilendirilen telefon üzerinden müşteri arama, cari hareket görüntüleme, borç ve tahsilat girişi yapılabilir.", "", "", "في النسخة الحالية، تمت إضافة نظام إدارة السحابة والهاتف المحمول إلى برنامج سطح المكتب. يمكن إجراء البحث عن العملاء، وعرض المعاملات الحالية، وإدخال الديون والتحصيل عبر الهاتف المصرح به عبر رابط كيو آر.", "/ucretsiz-veresiye-programi"),
            new("Mevcut firma, müşteri, borç ve tahsilat kayıtları korunarak güncel sürüme geçilebilir. Masaüstü çalışma düzeni devam ederken Bulut ve Mobil erişim, veresiye takibini daha erişilebilir ve pratik hale getirir.", "", "", "يمكن الانتقال إلى الإصدار الحالي مع الحفاظ على سجلات الشركة والعملاء والديون والتحصيل الموجودة. بينما يستمر ترتيب العمل المكتبي، تجعل الوصول عبر السحابة والهاتف المحمول تتبع الديون الآجلة أكثر سهولة وفاعلية.", "/ucretsiz-veresiye-programi"),
            new("NSX Veresiye Takip Pro; müşteri cari hesaplarını, borçları, tahsilatları, açık bakiyeleri ve işlem geçmişini düzenli takip etmek isteyen esnaf ve işletmeler için geliştirilmiş ücretsiz bir veresiye takip programıdır. Masaüstü programı hızlı günlük kullanım için çalışırken v1.0.5 ile eklenen Bulut ve Mobil Yönetim Sistemi, temel cari işlemleri cep telefonuna taşır.", "", "", "برنامج إن إس إكس لمتابعة الديون بالتقسيط؛ هو برنامج مجاني لمتابعة الديون صُمم للحرفيين والشركات الذين يرغبون في متابعة حسابات العملاء، الديون، التحصيلات، الأرصدة المفتوحة وسجل المعاملات بشكل منتظم. يعمل البرنامج المكتبي للاستخدام اليومي السريع، بينما يقوم نظام الإدارة السحابية والمتحركة الذي تمت إضافته في الإصدار الإصدار 1.0.5 بنقل المعاملات الأساسية إلى الهاتف المحمول.", "/ucretsiz-veresiye-programi"),
            new("NSX Veresiye Takip Pro’yu ücretsiz indirin; v1.0.5 Bulut ve Mobil Yönetim özelliklerini kullanmaya başlayın.", "", "", "قم بتنزيل تتبع الديون الاحترافي من إن إس إكس مجانًا؛ ابدأ باستخدام ميزات الإدارة السحابية والمتحركة في الإصدار الإصدار 1.0.5.", "/ucretsiz-veresiye-programi"),
            new("NSX Yazılım Çözümü", "", "", "حل برمجيات إن إس إكس", "/ucretsiz-veresiye-programi"),
            new("Programı", "", "", "البرنامج", "/ucretsiz-veresiye-programi"),
            new("https://www.nsxyazilim.com/ucretsiz-veresiye-programi", "", "", "هتتبس://ووو.إن إس إكسيازيليم.كوم/برنامج-الدَين-المجاني", "/ucretsiz-veresiye-programi"),
            new("v1.0.5 Bulut ve Mobil Yönetim", "", "", "الإصدار 1.0.5 إدارة السحابة والهاتف المحمول", "/ucretsiz-veresiye-programi"),
            new("Ücretsiz Veresiye", "", "", "دين مجاني", "/ucretsiz-veresiye-programi"),
            new("Ücretsiz Veresiye Programı | Bulut ve Mobil Cari Takip", "", "", "برنامج الحسابات المجاني | متابعة الحسابات على السحابة والجوال", "/ucretsiz-veresiye-programi"),
            new("ücretsiz veresiye programı", "", "", "برنامج الحسابات المجانية", "/ucretsiz-veresiye-programi"),
            new("ücretsiz veresiye programı, bulut veresiye programı, mobil veresiye programı, telefondan veresiye takibi, cari takip programı, borç alacak takip programı, tahsilat takip programı, QR ile cari takip, canlı senkronizasyon, NSX Veresiye Takip Pro, NSX Yazılım", "", "", "برنامج الائتمان المجاني، برنامج الائتمان السحابي، برنامج الائتمان عبر الهاتف المحمول، تتبع الائتمان من الهاتف، برنامج التتبع الحالي، برنامج تتبع الديون المستحقة، برنامج تتبع التحصيل، التتبع الحالي مع كيو آر، المزامنة الحية، إن إس إكس كريديت تراككينج الاحترافي، برمجيات إن إس إكس", "/ucretsiz-veresiye-programi"),
            new(", eğitim kurumlarının ders programı hazırlama, öğretmen ve sınıf planlama, derslik yönetimi, nöbet organizasyonu, analiz ve kurumsal çıktı süreçlerini tek merkezden yönetebilmesi için geliştirilmiş kapsamlı ve profesyonel bir okul planlama yazılımıdır. Karmaşık ders programlarını daha hızlı, düzenli ve kontrollü biçimde oluşturmayı hedefleyen sistem; öğretmen, sınıf, ders, derslik ve çalışma yılı verilerini birbiriyle ilişkili şekilde yönetir.", "", "", "هو برنامج تخطيط مدرسي شامل واحترافي تم تطويره لتمكين المؤسسات التعليمية من إدارة إعداد جداول الدروس، وتخطيط المعلمين والفصول، وإدارة الفصول الدراسية، وتنظيم المناوبات، وعمليات التحليل والمخرجات المؤسسية من مركز واحد. يهدف النظام الذي يسعى لإنشاء جداول دراسية معقدة بشكل أسرع ومنظم ومتحكم فيه؛ إلى إدارة بيانات المعلمين والفصول والدروس والفصول الدراسية وسنة الدراسة بشكل مترابط.", "/urun/nsx-okul-plan-pro"),
            new("3. görseli göster", "", "", "عرض الصورة الثالثة", "/urun/nsx-okul-plan-pro"),
            new("7. görseli göster", "", "", "عرض الصورة السابعة", "/urun/nsx-okul-plan-pro"),
            new("; ders programı hazırlamayı yalnızca bir tablo oluşturma işlemi olmaktan çıkararak öğretmen, sınıf, ders, derslik, nöbet, analiz, raporlama ve yedekleme süreçlerini aynı sistem içerisinde bir araya getirir. Özellikle yoğun öğretmen ve sınıf yapısına sahip kurumlarda planlama süresini azaltmaya, olası çakışmaları önceden görmeye ve daha düzenli bir çalışma sistemi oluşturmaya yardımcı olur.", "", "", "من خلال إخراج إعداد برنامج الدروس من كونه مجرد عملية إنشاء جدول، يجمع المعلم، الصف، الدرس، الفصول، الورديات، التحليل، التقرير وعملية النسخ الاحتياطي ضمن نفس النظام. يساعد بشكل خاص في المؤسسات التي تمتلك هيكلًا كثيفًا من المعلمين والصفوف على تقليل وقت التخطيط، ورؤية التعارضات المحتملة مسبقًا، وإنشاء نظام عمل أكثر تنظيمًا.", "/urun/nsx-okul-plan-pro"),
            new("A4 Uyumlu Kurumsal Çıktılar:", "", "", "المخرجات المؤسسية المتوافقة مع ا4:", "/urun/nsx-okul-plan-pro"),
            new("Dersliğe Göre Program:", "", "", "البرنامج حسب الفصل:", "/urun/nsx-okul-plan-pro"),
            new("Hazırlanan çizelge ve raporların PDF olarak kaydedilebilmesi veya doğrudan yazdırılabilmesi.", "", "", "تمكين حفظ الجداول والتقارير المعدة بصيغة بي دي إف أو طباعتها مباشرة.", "/urun/nsx-okul-plan-pro"),
            new("Her öğretmen için haftalık ders çizelgesinin ayrı görüntülenebilmesi.", "", "", "تمكين عرض جدول الدروس الأسبوعي بشكل منفصل لكل معلم.", "/urun/nsx-okul-plan-pro"),
            new("Kaydedilmemiş Değişiklik Koruması:", "", "", "حماية التغييرات غير المحفوظة:", "/urun/nsx-okul-plan-pro"),
            new("NSX Okul Plan Pro büyük ürün görseli", "", "", "صورة المنتج الكبير مخطط المدارس الاحترافي من إن إس إكس", "/urun/nsx-okul-plan-pro"),
            new("NSX Okul Plan Pro görselini büyüt", "", "", "تكبير صورة خطة مدرسة إن إس إكس الاحترافي", "/urun/nsx-okul-plan-pro"),
            new("NSX Okul Plan Pro program ekranı ve ürün görseli", "", "", "شاشة برنامج مخطط المدارس الاحترافي من إن إس إكس وصورة المنتج", "/urun/nsx-okul-plan-pro"),
            new("NSX Okul Plan Pro | Ders Programı ve Nöbet Planlama", "", "", "إن إس إكس خطة المدرسة الاحترافي | جدول الدروس وتخطيط المناوبة", "/urun/nsx-okul-plan-pro"),
            new("NSX Okul Plan Pro – Profesyonel Ders Programı ve Okul Planlama Yazılımı", "", "", "إن إس إكس خطة المدرسة الاحترافي – برنامج الدروس الاحترافي وبرمجيات تخطيط المدرسة", "/urun/nsx-okul-plan-pro"),
            new("NSX Okul Plan Pro, okul ders programı, ders programı hazırlama programı, öğretmen ders programı, nöbet planlama programı, öğretmen nöbet çizelgesi, okul yönetim yazılımı, NSX Yazılım", "", "", "إن إس إكس برنامج خطة المدرسة، برنامج جدول الدروس للمدرسة، برنامج إعداد جدول الدروس، جدول حصص المعلم، برنامج تخطيط الحراسة، جدول الحراسة للمعلم، برنامج إدارة المدرسة، برنامج إن إس إكس", "/urun/nsx-okul-plan-pro"),
            new("NSX Yazılım · Eğitim ve Okul Yönetimi", "", "", "برمجيات إن إس إكس · التعليم وإدارة المدارس", "/urun/nsx-okul-plan-pro"),
            new("Oluşturulan programın genel yapısının ve planlama durumunun kontrol edilebilmesi.", "", "", "قدرة التحقق من الهيكل العام للبرنامج الذي تم إنشاؤه وحالة التخطيط.", "/urun/nsx-okul-plan-pro"),
            new("Otomatik Ders Programı Oluşturma:", "", "", "إنشاء جدول دراسي تلقائي:", "/urun/nsx-okul-plan-pro"),
            new("PDF ve Yazdırma Desteği:", "", "", "دعم بي دي إف والطباعة:", "/urun/nsx-okul-plan-pro"),
            new("Program Sağlığı Analizi:", "", "", "تحليل صحة البرنامج:", "/urun/nsx-okul-plan-pro"),
            new("Programa yerleşemeyen derslerin ve yerleşmeme nedenlerinin incelenebilmesi.", "", "", "تمكين دراسة المواد الدراسية التي لم يتم إدراجها في الجدول وأسباب عدم إدراجها.", "/urun/nsx-okul-plan-pro"),
            new("https://www.nsxyazilim.com/urun/nsx-okul-plan-pro", "", "", "هتتبس://ووو.إن إس إكسيازيليم.كوم/ورون/إن إس إكس-وكول-بلان-الاحترافي", "/urun/nsx-okul-plan-pro"),
            new("Öğretmen, sınıf, derslik ve nöbet çizelgelerinin düzenli ve profesyonel A4 tasarımlarla hazırlanması.", "", "", "إعداد جداول المعلمين والفصول وقاعات الدروس والجداول الدورية بشكل منظم وباحترافية بتصاميم ا4.", "/urun/nsx-okul-plan-pro"),
            new("Öğretmene Göre Program:", "", "", "البرنامج وفقًا للمعلم:", "/urun/nsx-okul-plan-pro"),
            new("; küçük, orta ve büyüyen işletmelerin veresiye ve cari hesap süreçlerini dijital ortama taşıyarak işletme kontrolünü güçlendirir. Masaüstü kullanımının gücünü Bulut ve Mobil erişim kolaylığıyla birleştirerek, işletmenizi yalnızca iş yerinizden değil, ihtiyaç duyduğunuz her yerden yönetebilmenizi sağlar.", "", "", "; يعزز السيطرة على الأعمال من خلال نقل عمليات الحسابات الآجلة والحسابات الجارية للشركات الصغيرة والمتوسطة والكبيرة إلى البيئة الرقمية. من خلال الجمع بين قوة الاستخدام المكتبي وسهولة الوصول عبر السحابة والجوال، يتيح لك إدارة عملك ليس فقط من مكان عملك، بل من أي مكان تحتاجه.", "/urun/nsx-veresiye-takip-pro-free"),
            new("A4, PDF ve yazdırma seçenekleriyle kurumsal çıktılar oluşturun.", "", "", "قم بإنشاء مخرجات مؤسسية بخيارات ا4 وبي دي إف والطباعة.", "/urun/nsx-veresiye-takip-pro-free"),
            new("Cari Hareket Geçmişi:", "", "", "تاريخ الحركات الحالية:", "/urun/nsx-veresiye-takip-pro-free"),
            new("Excel kullanıyor, çok zorlanıyordum böyle bir program arıyor ve bulamamıştım, hayatımda gördüğüm en kapsamlı ve güzel bir program borç, alacak, tahsilat, cari takip, raporlar, yazdırma, pdf, kullanımı çok basit ve güvenli işimi o kadar rahatlattı ki. Bunların yanında otomatik yedekleme özelliğide çok başarılı. Gelmiş geçmiş en iyi program. Tavsiye ederim...", "", "", "كنت أستخدم إكسل، وكنت أعاني كثيرًا، كنت أبحث عن مثل هذا البرنامج ولم أتمكن من العثور عليه، إنه أوسع وأجمل برنامج رأيته في حياتي، الديون، المستحقات، التحصيل، متابعة الحسابات، التقارير، الطباعة، بي دي إف، استخدامه سهل جدًا وآمن وقد سهّل عملي كثيرًا. بجانب ذلك، ميزة النسخ الاحتياطي التلقائي أيضًا ناجحة جدًا. إنه أفضل برنامج على الإطلاق. أنصح به...", "/urun/nsx-veresiye-takip-pro-free"),
            new("NSX Cloud ve Mobil Yönetim Sistemi", "", "", "نظام إدارة السحابة والنقل إن إس إكس", "/urun/nsx-veresiye-takip-pro-free"),
            new("NSX Veresiye Takip Pro V1.0.5 ile cari hesap ve veresiye yönetimini her yerden kontrol edin.", "", "", "تحكم في الحسابات المدينة وإدارة الحسابات بالتقسيط من أي مكان باستخدام تتبع الديون الاحترافي من إن إس إكس الإصدار 1.0.5.", "/urun/nsx-veresiye-takip-pro-free"),
            new("NSX Veresiye Takip Pro, işletmelerin müşteri cari hesaplarını, veresiye işlemlerini, borç ve tahsilat süreçlerini hızlı, güvenli ve profesyonel şekilde yönetebilmesi için geliştirilmiş modern bir", "", "", "تتبع الديون الاحترافي من إن إس إكس، هو نظام حديث تم تطويره لتمكين الشركات من إدارة حسابات العملاء الآجلة، والمعاملات الآجلة، وعمليات الديون والتحصيل بطريقة سريعة وآمنة واحترافية", "/urun/nsx-veresiye-takip-pro-free"),
            new("NSX Veresiye Takip Programı ile müşteri, borç, alacak, ödeme ve tahsilat işlemlerinizi kolayca yönetin; programı ömür boyu ücretsiz kullanın.", "", "", "قم بإدارة عمليات العملاء والديون والقبض والدفع الخاصة بك بسهولة باستخدام برنامج إن إس إكس لمتابعة الحسابات بالآجل؛ استخدم البرنامج مجانًا مدى الحياة.", "/urun/nsx-veresiye-takip-pro-free"),
            new("NSX Yazılım tarafından Türkiye'de geliştirilmektedir.", "", "", "يتم تطويره في تركيا بواسطة برنامج إن إس إكس.", "/urun/nsx-veresiye-takip-pro-free"),
            new("QR Kod ile Hızlı Bağlantı:", "", "", "الاتصال السريع عبر رمز الاستجابة السريعة:", "/urun/nsx-veresiye-takip-pro-free"),
            new("NSX Program Videoları | Kurulum, Kullanım ve Tanıtım", "", "", "فيديوهات برنامج إن إس إكس | التثبيت، الاستخدام والتعريف", "/videolar"),
            new("NSX Yazılım programlarının kurulum, kullanım, eğitim ve tanıtım videolarını izleyin. İlgili programı inceleyin, ücretsiz indirin veya satın alın.", "", "", "شاهد مقاطع الفيديو الخاصة بتثبيت واستخدام وتدريب وعرض برامج إن إس إكس. اطلع على البرنامج المعني، قم بتنزيله مجانًا أو اشتريه.", "/videolar"),
            new("NSX program videoları, yazılım kurulum videoları, program kullanım videoları, NSX Yazılım", "", "", "فيديوهات برنامج إن إس إكس، فيديوهات تثبيت البرنامج، فيديوهات استخدام البرنامج، برنامج إن إس إكس", "/videolar"),
            new("Kullanım Videosu", "", "", "فيديو الاستخدام", "/videolar/nsx-veresiye-takip-pro-free-tanitim"),
            new("NSX Turbo Performans Programı Tanıtım Videosu", "", "", "فيديو تعريف برنامج أداء إن إس إكس توربو", "/videolar/nsx-veresiye-takip-pro-free-tanitim"),
            new("NSX Veresiye Takip Pro v1.0.5 Kurulum ve", "", "", "تثبيت تتبع الديون الاحترافي من إن إس إكس الإصدار 1.0.5 و", "/videolar/nsx-veresiye-takip-pro-free-tanitim"),
            new("NSX Veresiye Takip Pro v1.0.5 Kurulum ve Kullanım Videosu", "", "", "فيديو تثبيت واستخدام تتبع الديون الاحترافي من إن إس إكس الإصدار 1.0.5", "/videolar/nsx-veresiye-takip-pro-free-tanitim"),
            new("NSX Veresiye Takip Pro v1.0.5 Kurulum ve Kullanım Videosu video kapağı", "", "", "غلاف فيديو تثبيت واستخدام تتبع الديون الاحترافي من إن إس إكس الإصدار 1.0.5", "/videolar/nsx-veresiye-takip-pro-free-tanitim"),
            new("NSX Veresiye Takip Pro v1.0.5 Kurulum ve Kullanım Videosu videosunu izlemeye geç", "", "", "انتقل لمشاهدة فيديو تثبيت واستخدام تتبع الديون الاحترافي من إن إس إكس الإصدار 1.0.5", "/videolar/nsx-veresiye-takip-pro-free-tanitim"),
            new("NSX Veresiye Takip Pro v1.0.5 Kurulum ve Kullanım Videosu videosunu izleyin. NSX Veresiye Takip Pro v1.0.5 artık QR ile Bulut ve Mobil Yönetim, canlı senkronizasyon, mobil müşteri arama, cari hareket, borç ve tahsilat özelliklerini de içerir.", "", "", "شاهد فيديو تثبيت واستخدام إن إس إكس كريديت تراككينج الاحترافي الإصدار 1.0.5. يشمل إن إس إكس كريديت تراككينج الاحترافي الإصدار 1.0.5 الآن أيضا إدارة السحابة والهواتف المحمولة مع كيو آر، والمزامنة الحية، والبحث عن العملاء عبر الجوال، والحركة الحالية، والخصم، والتحصيل.", "/videolar/nsx-veresiye-takip-pro-free-tanitim"),
            new("NSX Veresiye Takip Pro v1.0.5 Kurulum ve Kullanım Videosu | NSX Yazılım", "", "", "فيديو تثبيت واستخدام برنامج تتبع الديون الاحترافي من إن إس إكس الإصدار 1.0.5 | برمجيات إن إس إكس", "/videolar/nsx-veresiye-takip-pro-free-tanitim"),
            new("NSX Veresiye Takip Pro v1.0.5: Cari, borç, tahsilat ve bakiye yönetimi; QR kod ile mobil erişim ve anlık bulut senkronizasyonu.", "", "", "إن إس إكس كريديت تراككينج برو v1.0.5: إدارة الحساب الجاري والديون والتحصيل والرصيد؛ وصول عبر الهاتف المحمول ومزامنة سحابية فورية باستخدام رمز QR.", "/videolar/nsx-veresiye-takip-pro-free-tanitim"),
            new("NSX Veresiye Takip Programı Ücretsiz, ücretsiz veresiye programı, veresiye takip programı, veresiye defteri, borç alacak takip programı, cari takip programı, müşteri bakiye takip programı, NSX Veresiye Takip Programı Ücretsiz indir, NSX Veresiye Takip Programı Ücretsiz fiyat, NSX Yazılım, Kurulum videosu, program kurulum videosu, program kullanım videosu", "", "", "برنامج متابعة الديون إن إس إكس مجاني، برنامج الديون المجاني، برنامج متابعة الديون، دفتر الديون، برنامج متابعة المدفوعات والمستحقات، برنامج متابعة الحسابات، برنامج متابعة رصيد العملاء، تحميل برنامج متابعة الديون إن إس إكس مجاني، سعر برنامج متابعة الديون إن إس إكس مجاني، برنامج إن إس إكس، فيديو التثبيت، فيديو تثبيت البرنامج، فيديو استخدام البرنامج", "/videolar/nsx-veresiye-takip-pro-free-tanitim"),
        };
    }
}
