namespace NSYazilim.Web.Services
{
    /// <summary>Final reviewed literals shared by public, account and dealer screens.</summary>
    public static class LocalizationFinalSeedData
    {
        public static readonly IReadOnlyList<LocalizationSeedItem> Items = new LocalizationSeedItem[]
        {
            new("Arayüz dili", "Interface language", "/Admin"),
            new("Admin giriş dili", "Admin login language", "/Admin/Login"),
            new("Yönetim paneli dili", "Admin panel language", "/Admin"),
            new("NSX Admin Giriş", "NSX Admin Login", "/Admin/Login"),
            new("BAYI KANALI", "DEALER CHANNEL", "/Dealer"),
            new("Cari hesap", "Current account", "/Dealer"),
            new("Cihaz durumu", "Device status", "/Account"),
            new("Cihaz kabul", "Device approval", "/Account"),
            new("Copyright © 2026 Nevzat SÜRÜCÜ", "Copyright © 2026 Nevzat SÜRÜCÜ", "/"),
            new("Dil / Language", "Language", "/"),
            new("Durum", "Status", "/"),
            new("Durum takibi", "Status tracking", "/Account"),
            new("E-postanızı Kontrol Edin", "Check Your Email", "/Account"),
            new("Eşleşmedi", "Not matched", "/Account"),
            new("Havale", "Bank transfer", "/BankTransfer"),
            new("Havale / EFT", "Bank Transfer / EFT", "/BankTransfer"),
            new("Hemen İncele", "Review Now", "/"),
            new("Info", "Info", "/"),
            new("Kapalı", "Closed", "/"),
            new("Lifetime", "Lifetime", "/Account"),
            new("NSX Bayi", "NSX Dealer", "/Dealer"),
            new("PASİF", "INACTIVE", "/Account"),
            new("PASİF LİSANS", "INACTIVE LICENSE", "/Account"),
            new("Pasif lisans", "Inactive license", "/Account"),
            new("Pending", "Pending", "/Account"),
            new("Program dosyası", "Program file", "/Account"),
            new("Satın Al", "Buy Now", "/"),
            new("Satın Alma Bildirimi Alındı", "Purchase Notification Received", "/BankTransfer"),
            new("Sipariş Detayı", "Order Details", "/Account"),
            new("Sınırsız Lisans", "Lifetime License", "/Account"),
            new("Tarih", "Date", "/"),
            new("Warning", "Warning", "/"),
            new("Yeni Bayi Satışı", "New Dealer Sale", "/Dealer"),
            new("Yeni Şifre Belirle", "Set a New Password", "/Account"),
            new("Yıllık / Sınırsız", "Annual / Lifetime", "/Account"),
            new("Yıllık Lisans", "Annual License", "/Account"),
            new("anasayfa", "home page", "/"),
            new("toplam lisans →", "total licenses →", "/Account"),
            new("videosunu izlemeye geç", "watch the video", "/videolar"),
            new("© NSX Yazılım. Tüm hakları saklıdır.", "© NSX Software. All rights reserved.", "/"),
            new("Ücretsiz Üyelik", "Free Membership", "/Account"),

            // TR+EN SEO recovery and free-download conversion flow.
            new("NSX Veresiye Takip Pro Free", "NSX Veresiye Takip Pro Free", "/Products"),
            new("NSX Veresiye Takip Pro", "NSX Veresiye Takip Pro", "/Products"),
            new("Uğur SÜRÜCÜ", "Uğur SÜRÜCÜ", "/Products"),

            // English is the only global target now, so the flagship free-product page must
            // never fall back to the old literal machine translations of cari/veresiye.
            new("; küçük, orta ve büyüyen işletmelerin veresiye ve cari hesap süreçlerini dijital ortama taşıyarak işletme kontrolünü güçlendirir. Masaüstü kullanımının gücünü Bulut ve Mobil erişim kolaylığıyla birleştirerek, işletmenizi yalnızca iş yerinizden değil, ihtiyaç duyduğunuz her yerden yönetebilmenizi sağlar.", "; helps small, medium and growing businesses strengthen control by moving receivables and customer account processes into a digital system. By combining the power of desktop software with convenient Cloud and Mobile access, it lets you manage your business wherever you need to work, not only from the workplace.", "/Products/VeresiyeFree"),
            new("A4, PDF ve yazdırma seçenekleriyle kurumsal çıktılar oluşturun.", "Create professional A4, PDF and printed reports.", "/Products/VeresiyeFree"),
            new("Anlık Bakiye Kontrolü:", "Real-Time Balance Check:", "/Products/VeresiyeFree"),
            new("Borç ve Tahsilat Yönetimi:", "Debt and Collection Management:", "/Products/VeresiyeFree"),
            new("Cari Hareket Geçmişi:", "Account Activity History:", "/Products/VeresiyeFree"),
            new("Çok iyi beğendim tavsiye ederim.", "Very good. I liked it and recommend it.", "/Products/VeresiyeFree"),
            new("Çok sayıda müşteri arasından aradığınız cari hesaba anında ulaşın.", "Instantly find the customer account you need among many customers.", "/Products/VeresiyeFree"),
            new("Excel kullanıyor, çok zorlanıyordum böyle bir program arıyor ve bulamamıştım, hayatımda gördüğüm en kapsamlı ve güzel bir program borç, alacak, tahsilat, cari takip, raporlar, yazdırma, pdf, kullanımı çok basit ve güvenli işimi o kadar rahatlattı ki. Bunların yanında otomatik yedekleme özelliğide çok başarılı. Gelmiş geçmiş en iyi program. Tavsiye ederim...", "I had been struggling with Excel and could not find a program like this. It is one of the most comprehensive programs I have used: debt, receivables, collections, customer accounts, reports, printing and PDF are all easy and secure to manage. It has made my work much easier, and the automatic backup feature is excellent as well. I recommend it.", "/Products/VeresiyeFree"),
            new("Giriş başarılı. Hesabına hoş geldin.", "Sign-in successful. Welcome to your account.", "/Products/VeresiyeFree"),
            new("Kullanıcı hesaplarını ve erişim yetkilerini kontrollü şekilde yönetin.", "Manage user accounts and access permissions in a controlled manner.", "/Products/VeresiyeFree"),
            new("Masaüstü programı ile Bulut sistemi arasında çalışan otomatik senkronizasyon altyapısı sayesinde yapılan işlemler güncel tutulur. Böylece işletmenizin başında olmasanız bile müşteri hesaplarını ve tahsilat süreçlerini mobil cihazınız üzerinden kontrol etmeye devam edebilirsiniz.", "Automatic synchronization between the desktop application and Cloud system keeps transactions up to date. Even when you are away from the workplace, you can continue checking customer accounts and collection activity from your mobile device.", "/Products/VeresiyeFree"),
            new("masaüstü, Bulut ve Mobil cari takip sistemidir.", "desktop, Cloud and Mobile customer account tracking system.", "/Products/VeresiyeFree"),
            new("Müşteri Cari Takibi:", "Customer Account Tracking:", "/Products/VeresiyeFree"),
            new("Müşteri ve işlem süreçlerini barkod desteğiyle hızlandırın.", "Speed up customer and transaction workflows with barcode support.", "/Products/VeresiyeFree"),
            new("Müşteriye ait geçmiş borç ve tahsilat hareketlerini tek ekrandan görüntüleyin.", "View a customer's previous debt and collection activity on a single screen.", "/Products/VeresiyeFree"),
            new("NSX Veresiye Takip Pro V1.0.5 ile cari hesap ve veresiye yönetimini her yerden kontrol edin.", "Manage customer accounts and receivables from anywhere with NSX Veresiye Takip Pro V1.0.5.", "/Products/VeresiyeFree"),
            new("NSX Veresiye Takip Pro, işletmelerin müşteri cari hesaplarını, veresiye işlemlerini, borç ve tahsilat süreçlerini hızlı, güvenli ve profesyonel şekilde yönetebilmesi için geliştirilmiş modern bir", "NSX Veresiye Takip Pro is a modern solution designed to help businesses manage customer accounts, sales on account, debt and collection processes quickly, securely and professionally; it is a", "/Products/VeresiyeFree"),
            new("NSX Veresiye Takip Programı ile müşteri, borç, alacak, ödeme ve tahsilat işlemlerinizi kolayca yönetin; programı ömür boyu ücretsiz kullanın.", "Manage customers, debt, receivables, payments and collections easily with NSX Veresiye Takip Pro, and use the software free for life.", "/Products/VeresiyeFree"),
            new("Profesyonel Çıktılar:", "Professional Reports and Printouts:", "/Products/VeresiyeFree"),
            new("QR Kod ile Hızlı Bağlantı:", "Quick Connection by QR Code:", "/Products/VeresiyeFree"),
            new("sayesinde işletmenizin cari hesaplarına yalnızca bilgisayarınızdan değil, cep telefonunuzdan da güvenli şekilde erişebilirsiniz. QR kod ile kolayca bağlantı kurabilir; müşterilerinizi görüntüleyebilir, cari hareketlerini inceleyebilir, yeni borç ve tahsilat işlemleri oluşturabilir ve güncel bakiyeleri anlık olarak takip edebilirsiniz.", "lets you securely access your business customer accounts not only from your computer but also from your phone. Connect easily by QR code, view customers, review account activity, record new debt and collection transactions, and monitor current balances in real time.", "/Products/VeresiyeFree"),
            new("Toplam borç, toplam tahsilat ve açık bakiyeyi kolayca takip edin.", "Easily track total debt, total collections and outstanding balance.", "/Products/VeresiyeFree"),
            new("Yeni borç ve tahsilat işlemlerini saniyeler içinde kaydedin.", "Record new debt and collection transactions in seconds.", "/Products/VeresiyeFree"),

            new("NSX Yazılım | İşletmeler İçin Profesyonel Windows Yazılımları", "NSX Software | Professional Windows Software for Businesses", "/"),
            new("NSX Yazılım ile cari takip, satış ve stok, teknik servis, sigorta, okul, otomotiv, klinik ve veri kurtarma çözümlerini keşfedin.", "Discover NSX solutions for accounts, sales and inventory, technical service, insurance, schools, automotive, clinics, and data recovery.", "/"),
            new("İşletmenize uygun cari, satış, servis, sigorta, eğitim, otomotiv ve veri kurtarma yazılımlarını NSX güvencesiyle keşfedin.", "Discover NSX software for accounts, sales, service, insurance, education, automotive, and data recovery.", "/"),
            new("NSX YAZILIM · İŞLETME ÇÖZÜMLERİ", "NSX SOFTWARE · BUSINESS SOLUTIONS", "/"),
            new("İşletmeniz için modern Windows", "Modern Windows software for your business", "/"),
            new("yazılımları", "software", "/"),
            new("Cari takip, satış ve stok, teknik servis, sigorta, okul, otomotiv ve veri kurtarma gibi iş süreçleri için geliştirilen NSX çözümlerini tek merkezden keşfedin. Öne çıkan NSX Veresiye Takip Pro Free ile cari hesaplarınızı Windows, Bulut ve Mobil üzerinden ücretsiz yönetin.", "Discover NSX solutions for accounts, sales and inventory, technical service, insurance, schools, automotive, and data recovery in one place. Manage your accounts for free on Windows, Cloud, and Mobile with the featured NSX Veresiye Takip Pro Free.", "/"),
            new("İşletmeniz için modern NSX yazılımlarını keşfedin. Öne çıkan NSX Veresiye Takip Pro Free tamamen ücretsiz.", "Discover modern NSX software for your business. The featured NSX Veresiye Takip Pro Free is completely free.", "/"),
            new("Ücretsiz lisans ve güvenli indirme erişimi", "Free license and secure download access", "/Shared/Footer"),
            new("Ömür boyu ücretsiz lisans", "Lifetime free license", "/Shared/Footer"),
            new("Ödeme veya kart bilgisi gerekmez; ücretsiz lisans hesabınıza otomatik tanımlanır.", "No payment or card details are required; the free license is added to your account automatically.", "/Shared/Footer"),
            new("ÜCRETSİZ İNDİRME", "FREE DOWNLOAD", "/Store/FreeDownloadStart"),
            new("İndirmeniz hazırlanıyor.", "Your download is being prepared.", "/Store/FreeDownloadStart"),
            new("için güvenli indirme birkaç saniye içinde otomatik başlayacak.", "secure download will start automatically in a few seconds.", "/Store/FreeDownloadStart"),
            new("Ücretsiz indirme güvenceleri", "Free download assurances", "/Store/FreeDownloadStart"),
            new("Ödeme yok", "No payment", "/Store/FreeDownloadStart"),
            new("Kart bilgisi yok", "No card details", "/Store/FreeDownloadStart"),
            new("Ücretsiz lisans", "Free license", "/Store/FreeDownloadStart"),
            new("Kurulum dosyası hazırlanıyor...", "Preparing the installer...", "/Store/FreeDownloadStart"),
            new("İndirmeyi yeniden başlat", "Restart download", "/Store/FreeDownloadStart"),
            new("Ürün sayfasına dön", "Return to product page", "/Store/FreeDownloadStart"),
            new("Tarayıcınız dosyayı engellerse yukarıdaki indirme düğmesine bir kez tıklayın. NSX ücretsiz lisansı hesabınıza otomatik tanımlanır.", "If your browser blocks the file, click the download button above once. Your NSX free license is added to your account automatically.", "/Store/FreeDownloadStart"),
            new("NSX ücretsiz indirme", "NSX free download", "/Store/FreeDownloadStart"),
            new("İndirme başladı. Dosyanız tarayıcınıza gönderildi.", "Download started. The file has been sent to your browser.", "/Store/FreeDownloadStart"),
            new("KURULUM VE KULLANIM", "SETUP AND USAGE", "/Products"),
            new("NSX Veresiye Takip Pro Free'yi yakından görün.", "See NSX Veresiye Takip Pro Free in action.", "/Products"),
            new("Kurulum ve temel kullanım videosunu izleyin; ardından ücretsiz lisansınızla güvenli indirmeyi başlatın.", "Watch the setup and basic usage video, then start the secure download with your free license.", "/Products"),
            new("NSX Veresiye Takip Pro Free kurulum ve kullanım videosu", "NSX Veresiye Takip Pro Free setup and usage video", "/Products"),
            new("NSX Veresiye Takip Pro Free Kurulum ve Kullanım", "NSX Veresiye Takip Pro Free Setup and Usage", "/Products"),
            new("NSX Veresiye Takip Pro Free kurulum ve temel kullanım videosu.", "NSX Veresiye Takip Pro Free setup and basic usage video.", "/Products")
        };
    }
}
