namespace NSYazilim.Web.Services
{
    /// <summary>Reviewed English coverage for the dealer portal.</summary>
    public static class LocalizationEnglishDealerSeedData
    {
        private static LocalizationSeedItem E(string source, string english, string area)
            => new(source, english, area);

        public static readonly IReadOnlyList<LocalizationSeedItem> Items = new LocalizationSeedItem[]
        {
            E("ADMIN ONAYINA GONDER", "SEND FOR ADMIN APPROVAL", "/Dealer/BankTransfer"),
            E("Havale Bildirimi", "Bank Transfer Notification", "/Dealer"),
            E("NSX Havale Bilgileri", "NSX Bank Transfer Details", "/Dealer/BankTransfer"),
            E("Transfer Tarihi", "Transfer Date", "/Dealer/BankTransfer"),
            E("Gerekirse admin icin not ekleyin...", "Add a note for the admin if needed...", "/Dealer/BankTransfer"),
            E("SATIS KONTROLU", "SALE REVIEW", "/Dealer/SaleDetail"),
            E("Havale Bildirimi Bekliyor", "Awaiting Bank Transfer Notification", "/Dealer/SaleDetail"),
            E("Havale Bildirimi Yap", "Submit Bank Transfer Notification", "/Dealer/SaleDetail"),
            E("Bildirim Tarihi", "Notification Date", "/Dealer/SaleDetail"),
            E("Admin Notu", "Admin Note", "/Dealer/SaleDetail"),
            E("Kâr Modeli", "Profit Model", "/Dealer"),
            E("Musteri", "Customer", "/Dealer"),
            E("Sinirsiz", "Lifetime", "/Dealer"),
            E("Yillik", "Annual", "/Dealer"),
            E("Onayli alacak", "Approved receivable", "/Dealer"),
            E("Iptal", "Cancelled", "/Dealer"),
            E("Beklemede", "Pending", "/Dealer"),
            E("Onaylandi", "Approved", "/Dealer"),
            E("Reddedildi", "Rejected", "/Dealer"),
            E("Admin Onayi", "Admin Approval", "/Dealer"),
            E("Bildirim Bekliyor", "Awaiting Notification", "/Dealer"),
            E("Musteri e-postasina bagli", "Linked to customer email", "/Dealer"),
            E("Onaydan sonra", "After approval", "/Dealer"),
            E("Onayli", "Approved", "/Dealer"),
            E("Onay bekliyor", "Awaiting approval", "/Dealer"),
            E("Admin Onayi Bekliyor", "Awaiting Admin Approval", "/Dealer"),
            E("Havale Bekliyor", "Awaiting Bank Transfer", "/Dealer"),
            E("Admin Onayladi", "Admin Approved", "/Dealer"),
            E("Admin Reddetti", "Admin Rejected", "/Dealer"),
            E("Programi Indir", "Download Software", "/Dealer"),
            E("Hak edildi", "Earned", "/Dealer"),
            E("Bayi Paneli", "Dealer Panel", "/Dealer"),
            E("Güvenli Çıkış", "Secure Sign Out", "/Dealer"),
            E("NSX Yazılım Sitesi", "NSX Software Website", "/Dealer"),
            E("Satış ve kontrol kanalı", "Sales and Management Channel", "/Dealer"),
            E("Satışlarım / Lisanslar", "My Sales / Licenses", "/Dealer"),
            E("Hoş geldiniz,", "Welcome,", "/Dealer"),
            E("Başlangıç:", "Start:", "/Dealer/SaleDetail"),
            E("/ Bitiş:", "/ End:", "/Dealer/SaleDetail"),
            E("Admin onayından sonra hak edilir.", "Earned after admin approval.", "/Dealer"),
            E("Bildirim gönderildikten sonra bayi tarafında onay yetkisi yoktur. Admin onayladığında müşteri lisansı oluşur, bayi panelinde lisans ve onaylı alacak görünür.", "After the notification is submitted, the dealer cannot approve it. Once the admin approves it, the customer license is created and the license and approved receivable appear in the dealer panel.", "/Dealer"),
            E("Bildirimi Admin Onayına Gönder", "Send Notification for Admin Approval", "/Dealer"),
            E("Bu bildirim satışı otomatik onaylamaz. Son onay NSX admin tarafından verilir.", "This notification does not approve the sale automatically. Final approval is given by the NSX admin.", "/Dealer"),
            E("Gönderen Adı / Firma", "Sender Name / Company", "/Dealer"),
            E("Gönderen Banka", "Sender Bank", "/Dealer"),
            E("Hesap Sahibi", "Account Holder", "/Dealer"),
            E("Onay akışı:", "Approval flow:", "/Dealer"),
            E("Satış Özeti", "Sales Summary", "/Dealer"),
            E("Satışa Dön", "Back to Sale", "/Dealer"),
            E("Ödenecek Tutar", "Amount Due", "/Dealer"),
            E("Şube", "Branch", "/Dealer"),
            E("+ Yeni Satış", "+ New Sale", "/Dealer"),
            E("Admin Onayı Bekleyen", "Awaiting Admin Approval", "/Dealer"),
            E("Bayi E-posta", "Dealer Email", "/Dealer"),
            E("Bayi Kodu", "Dealer Code", "/Dealer"),
            E("Bayi Kârı", "Dealer Profit", "/Dealer"),
            E("Detay", "Details", "/Dealer"),
            E("Henüz bayi satışı yok.", "No dealer sales yet.", "/Dealer"),
            E("Müşteri", "Customer", "/Dealer"),
            E("Müşteri e-postasına bağlı satış, lisans ve bayi alacakları tek ekranda.", "Sales, licenses and dealer receivables linked to the customer's email in one screen.", "/Dealer"),
            E("Onaylanan Satış", "Approved Sales", "/Dealer"),
            E("Onaylı Bayi Alacağı", "Approved Dealer Receivables", "/Dealer"),
            E("Sipariş", "Order", "/Dealer"),
            E("Son 50 bayi satış kaydı.", "Latest 50 dealer sales records.", "/Dealer"),
            E("Son Satışlar", "Recent Sales", "/Dealer"),
            E("Toplam Satış Kaydı", "Total Sales Records", "/Dealer"),
            E("Tümünü Gör", "View All", "/Dealer"),
            E("İl / Yetkili", "City / Contact", "/Dealer"),
            E("Bayi Girişi", "Dealer Login", "/Dealer/Login"),
            E("Bayi Paneline Giriş", "Sign in to Dealer Panel", "/Dealer/Login"),
            E("Bayi hesabı admin tarafından oluşturulur. Müşteri hesabı için", "Dealer accounts are created by an admin. For a customer account, use the", "/Dealer/Login"),
            E("Bayi hesabınızla satışlarınızı, müşteriye bağlı lisansları ve onaylanmış alacaklarınızı kontrol edin.", "Use your dealer account to manage your sales, customer-linked licenses and approved receivables.", "/Dealer/Login"),
            E("Bu cihazda beni hatırla", "Remember me on this device", "/Dealer/Login"),
            E("Kullanıcı Girişi", "Customer Login", "/Dealer/Login"),
            E("NSX BAYI KANALI", "NSX DEALER CHANNEL", "/Dealer/Login"),
            E("sayfasını kullanın.", "page.", "/Dealer/Login"),
            E("Şifre", "Password", "/Dealer/Login"),
            E("Ad soyad veya e-posta yazin...", "Enter name or email...", "/Dealer/NewSale"),
            E("Bu satış için bayi kârınız mevcut hesabınızdaki", "Your dealer profit for this sale is calculated using the", "/Dealer/NewSale"),
            E("Lisans Türü", "License Type", "/Dealer/NewSale"),
            E("MUSTERIYE BAGLI LISANS", "CUSTOMER-LINKED LICENSE", "/Dealer/NewSale"),
            E("Müşteri Ara", "Search Customer", "/Dealer/NewSale"),
            E("Müşteri seçin", "Select customer", "/Dealer/NewSale"),
            E("Müşteri sitede önceden üye olmalıdır. Bayi lisans sahibi olmaz; lisans müşteri adı, soyadı ve e-posta hesabına kaydedilir.", "The customer must already have a site account. The dealer does not become the license holder; the license is registered to the customer's name, surname and email account.", "/Dealer/NewSale"),
            E("Müşteri Üyeliği", "Customer Account", "/Dealer/NewSale"),
            E("Satışlara Dön", "Back to Sales", "/Dealer/NewSale"),
            E("Satışı Oluştur ve Havaleye Geç", "Create Sale and Continue to Bank Transfer", "/Dealer/NewSale"),
            E("Satışı bayi yapar; lisans seçtiğiniz mevcut site üyesinin e-posta adresine bağlanır.", "The dealer creates the sale; the license is linked to the email address of the existing site member you select.", "/Dealer/NewSale"),
            E("Sınırsız", "Lifetime", "/Dealer/NewSale"),
            E("Vazgeç", "Cancel", "/Dealer/NewSale"),
            E("Yeni Satış", "New Sale", "/Dealer/NewSale"),
            E("Yıllık", "Annual", "/Dealer/NewSale"),
            E("kuralı ile hesaplanır ve satış anında sabitlenir.", "rule and is locked when the sale is created.", "/Dealer/NewSale"),
            E("Önemli:", "Important:", "/Dealer/NewSale"),
            E("Ürün seçin", "Select product", "/Dealer/NewSale"),
            E("Bayi Alacağı", "Dealer Receivable", "/Dealer/SaleDetail"),
            E("Bayi Kâr Kuralı", "Dealer Profit Rule", "/Dealer/SaleDetail"),
            E("Bu ürün için aktif program dosyası bulunamadı.", "No active software file was found for this product.", "/Dealer/SaleDetail"),
            E("Gönderen", "Sender", "/Dealer/SaleDetail"),
            E("Havale / Admin Onayı", "Bank Transfer / Admin Approval", "/Dealer/SaleDetail"),
            E("Lisans, havale bildirimi admin tarafından onaylandığında otomatik oluşur ve", "The license is created automatically when the bank transfer notification is approved by the admin and is linked to the", "/Dealer/SaleDetail"),
            E("Müşteri E-posta", "Customer Email", "/Dealer/SaleDetail"),
            E("Müşteri Lisansları", "Customer Licenses", "/Dealer/SaleDetail"),
            E("Program İndirme", "Software Download", "/Dealer/SaleDetail"),
            E("Satış Bilgileri", "Sale Information", "/Dealer/SaleDetail"),
            E("Satış Tutarı", "Sale Amount", "/Dealer/SaleDetail"),
            E("Satış kaydı hazır. Sonraki adımda havale/EFT bildiriminizi gönderin. Nihai onay sadece NSX admin tarafından verilir.", "The sale record is ready. In the next step, submit your bank transfer notification. Final approval can only be given by the NSX admin.", "/Dealer/SaleDetail"),
            E("Satış onaylı görünüyor ancak lisans kaydı henüz bulunamadı.", "The sale appears approved, but no license record has been found yet.", "/Dealer/SaleDetail"),
            E("Satış, havale onayı, müşteri lisansı ve indirme durumu.", "Sale, bank transfer approval, customer license and download status.", "/Dealer/SaleDetail"),
            E("hesabına bağlanır.", "customer account.", "/Dealer/SaleDetail"),
            E("İndirme butonları admin onayı ve lisans oluşumundan sonra açılır.", "Download buttons become available after admin approval and license creation.", "/Dealer/SaleDetail"),
            E("Aç", "Open", "/Dealer/Sales"),
            E("BAYI HAREKETLERI", "DEALER ACTIVITY", "/Dealer/Sales"),
            E("Henüz satış kaydınız yok.", "You do not have any sales records yet.", "/Dealer/Sales"),
            E("Her lisans müşterinin site üyeliğindeki e-posta adresine bağlı oluşur.", "Each license is created against the email address in the customer's site account.", "/Dealer/Sales"),
            E("Satış", "Sale", "/Dealer/Sales"),
            E("Satışlarım ve Lisanslar", "My Sales and Licenses", "/Dealer/Sales")
        };
    }
}
