namespace NSYazilim.Web.Services
{
    public static class LocalizationEnglishOfflineUiSeedData
    {
        public static readonly IReadOnlyList<LocalizationSeedItem> Items = new LocalizationSeedItem[]
        {
            new("Kolay kullanım", "Easy to use", "/Home"),
            new("Yerli destek", "Local support", "/Home"),
            new("Dijital lisans", "Digital license", "/Home/Returns"),
            new("1. Kapsam", "1. Scope", "/Home/Returns"),
            new("4. Teknik sorunlar", "4. Technical issues", "/Home/Returns"),
            new("Talebinizi", "Send your request to", "/Home/Returns"),
            new("adresine veya", "or through", "/Home/Legal"),
            new("iletin.", ".", "/Home/Returns"),
            new("2. Toplanan bilgiler", "2. Information we collect", "/Home/Privacy"),
            new("'ni inceleyin.", ".", "/Home/Privacy"),
            new("Merak ettiklerinizi", "Whatever you are wondering,", "/Home/FAQ"),
            new("SON İNDİRME", "LATEST DOWNLOAD", "/Account/Downloads"),
            new("kez indirildi", "times downloaded", "/Account/Downloads"),
            new("Gelen kutusunu kontrol edin", "Check your inbox", "/Account/ForgotPasswordConfirmation"),
            new("Kontrol edin", "Check", "/Account/ForgotPasswordConfirmation"),
            new("kontrol edin.", "check it.", "/Account/ForgotPasswordConfirmation"),
            new("TL ve üzeri", "TL and above", "/Shared/Campaign"),
            new("tarihine kadar", "until", "/Shared/Campaign"),
            new("Bakkal Veresiye Defteri Nasıl Tutulur?", "How to Keep a Grocery Store Credit Ledger?", "/Blog"),
            new("Bakkal Veresiye Defteri Nasıl Tutulur? rehberini oku", "Read the How to Keep a Grocery Store Credit Ledger guide", "/Blog"),
            new("Bakkal veresiye defterini dijitalleştirin; müşteri borç, tahsilat ve açık bakiyeyi masaüstü ve cep telefonundan Bulut sistemiyle takip edin.", "Digitize your grocery store credit ledger; track customer debt, collections and outstanding balances from desktop and mobile with the Cloud system.", "/Blog"),
            new("Esnaflar İçin Veresiye Takip Programı", "Credit Tracking Software for Tradespeople", "/Blog"),
            new("Esnaflar İçin Veresiye Takip Programı rehberini oku", "Read the Credit Tracking Software for Tradespeople guide", "/Blog"),
            new("NSX Sigorta Acente Pro ile Poliçe ve Acente Yönetimini Tek Merkezde Toplayın", "Manage Policies and Agency Operations in One Place with NSX Insurance Agency Pro", "/Blog"),
            new("NSX Sigorta Acente Pro ile Poliçe ve Acente Yönetimini Tek Merkezde Toplayın için NSX Yazılım ürün görseli", "NSX Software product image for Manage Policies and Agency Operations in One Place with NSX Insurance Agency Pro", "/Blog"),
            new("NSX Sigorta Acente Pro ile Poliçe ve Acente Yönetimini Tek Merkezde Toplayın rehberini oku", "Read the Manage Policies and Agency Operations in One Place with NSX Insurance Agency Pro guide", "/Blog"),
            new("NSX Kasa Defteri Pro | Gelir Gider, Kasa ve Cari Takip Rehberi", "NSX Cash Book Pro | Income, Expense, Cash and Account Tracking Guide", "/Blog"),
            new("Gizlilik Politikası | NSX Yazılım", "Privacy Policy | NSX Software", "/Home/Privacy"),
            new("Kurulum", "Installation", "/Home/FAQ"),
            new("Lisans", "License", "/Home/FAQ"),
            new("Beklenmeyen bir sorun", "An unexpected issue occurred", "/Home/Error"),
            new("Tekrar Dene", "Try Again", "/Home/Error"),
            new("Teknik destek", "Technical support", "/Home/Contact"),
            new("NSX güvencesiyle.", "Backed by NSX.", "/Store/Detail"),
            new("Windows uyumlu", "Windows compatible", "/Store/Detail"),
            new("Dijital teslimat", "Digital delivery", "/Store/Detail"),
            new("NSX teknik destek", "NSX technical support", "/Store/Detail"),
            new("Ürün avantajları", "Product benefits", "/Store/Detail"),
            new("NSX ORİJİNAL YAZILIM", "GENUINE NSX SOFTWARE", "/Store/Detail"),
            new("Stokta · Dijital teslimat", "In stock · Digital delivery", "/Store/Detail"),
            new("Şu anda stokta yok", "Currently out of stock", "/Store/Detail"),
            new("⌕ Büyüt", "⌕ Zoom", "/Store/Detail"),
            new("Görsele tıklayarak tam boy inceleyin", "Click the image to view it full size", "/Store/Detail"),
            new("Windows masaüstü yazılımı", "Windows desktop software", "/Store/Detail"),
            new("Yeni", "New", "/Store"),
            new("Hızlı kurulum", "Quick setup", "/Store/Detail"),
            new("Güvenli lisans", "Secure license", "/Store/Detail"),
            new("Kullanım lisansı", "Usage license", "/Store/Detail"),
            new("Ücretsiz", "Free", "/Store"),
            new("Üye girişiyle doğrudan indirme", "Direct download after signing in", "/Store/Detail"),
            new("Ödeme adımı yok", "No payment required", "/Store/Detail"),
            new("Hemen kullanmaya başlayın", "Start using it right away", "/Store/Detail"),
            new("İndirim havale bildiriminde otomatik uygulanır.", "The discount is applied automatically to the bank transfer notice.", "/Store/Detail"),
            new("Lisans türü", "License type", "/Store/Detail"),
            new("Yıllık lisans", "Annual license", "/Store/Detail"),
            new("365 gün kullanım", "365 days of use", "/Store/Detail"),
            new("Sınırsız lisans", "Lifetime license", "/Store/Detail"),
            new("Ömür boyu kullanım", "Lifetime use", "/Store/Detail"),
            new("Ücretsiz İndir", "Free Download", "/Store/Detail"),
            new("Satın Alma Bildirimi", "Purchase Notification", "/Store/Detail"),
            new("Demo / İndirme", "Demo / Download", "/Store/Detail"),
            new("Kurulum dosyasını alın", "Get the installer", "/Store/Detail"),
            new("Stokta Yok", "Out of Stock", "/Store/Detail"),
            new("Bilgi Al", "Get Information", "/Store/Detail"),
            new("Dosya açılmıyor mu?", "Won't the file open?", "/Store/Detail"),
            new("Dosya açılmıyor mu?", "Won't the file open?", "/Products/Detail"),
            new("Güvenli Kurulum Rehberini İnceleyin", "View the Safe Installation Guide", "/Store/Detail"),
            new("Sağ tık → Engellemeyi kaldır", "Right-click → Unblock", "/Store/Detail"),
            new("Sağ tık → Engellemeyi kaldır", "Right-click → Unblock", "/Products/Detail"),
            new("Rehberi Aç", "Open Guide", "/Store/Detail"),
            new("Ürün uzmanına sorun", "Ask a product specialist", "/Store/Detail"),
            new("WhatsApp ile bilgi alın", "Get information on WhatsApp", "/Store/Detail"),
            new("Onay sonrası hızlı erişim", "Fast access after approval", "/Store/Detail"),
            new("Uzaktan kurulum", "Remote installation", "/Store/Detail"),
            new("NSX destek ekibi yanınızda", "NSX support is with you", "/Store/Detail"),
            new("Ürün Özellikleri", "Product Features", "/Store/Detail"),
            new("Teknik Bilgiler", "Technical Information", "/Store/Detail"),
            new("Kurulum & Destek", "Installation & Support", "/Store/Detail"),
            new("Yorumlar", "Reviews", "/Store/Detail"),
            new("Soru & Cevap", "Questions & Answers", "/Store/Detail"),
            new("İndirme Bilgileri", "Download Information", "/Store/Detail"),
            new("Havale Bilgileri", "Bank Transfer Information", "/Store/Detail"),
            new("ÜRÜNÜ TANIYIN", "DISCOVER THE PRODUCT", "/Store/Detail"),
            new("TEKNİK BİLGİLER", "TECHNICAL INFORMATION", "/Store/Detail"),
            new("Kuruluma hazır, anlaşılır yapı.", "Ready to install and easy to understand.", "/Store/Detail"),
            new("Satın almadan önce temel kullanım ve teslimat bilgilerini tek bakışta inceleyin.", "Review key usage and delivery details at a glance before purchasing.", "/Store/Detail"),
            new("Platform", "Platform", "/Store/Detail"),
            new("Windows masaüstü", "Windows desktop", "/Store/Detail"),
            new("Teslimat", "Delivery", "/Store/Detail"),
            new("Ürün kodu", "Product code", "/Store/Detail"),
            new("Kurulumda yalnız değilsiniz.", "You are not alone during installation.", "/Store/Detail"),
            new("Lisans ve indirme sonrasında ihtiyaç halinde uzaktan bağlantıyla kurulum ve başlangıç desteği alabilirsiniz.", "After licensing and download, remote installation and onboarding support is available when needed.", "/Store/Detail"),
            new("Ürünü ve lisansı seçin", "Choose the product and license", "/Store/Detail"),
            new("İşlemi tamamlayın", "Complete the process", "/Store/Detail"),
            new("Kurulum desteği alın", "Get installation support", "/Store/Detail"),
            new("MÜŞTERİ YORUMLARI", "CUSTOMER REVIEWS", "/Store/Detail"),
            new("İlk yorumu siz yapın", "Be the first to review", "/Store/Detail"),
            new("Yorumlar gerçek kullanıcı deneyimlerini yansıtır ve yayın öncesi kontrol edilir.", "Reviews reflect real user experiences and are checked before publication.", "/Store/Detail"),
            new("Yorum yapmak için giriş yap", "Sign in to leave a review", "/Store/Detail"),
            new("Henüz yorum yok", "No reviews yet", "/Store/Detail"),
            new("Bu ürün hakkındaki deneyiminizi paylaşan ilk kişi olabilirsiniz.", "You can be the first to share your experience with this product.", "/Store/Detail"),
            new("SIK SORULAN SORULAR", "FREQUENTLY ASKED QUESTIONS", "/Store/Detail"),
            new("Satın almadan önce bilmeniz gerekenler.", "What you should know before purchasing.", "/Store/Detail"),
            new("Ürün, lisans veya kurulum hakkında farklı bir sorunuz varsa destek ekibimize ulaşabilirsiniz.", "If you have another question about the product, license or installation, contact our support team.", "/Store/Detail"),
            new("Program hangi işletim sisteminde çalışır?", "Which operating system does the software run on?", "/Store/Detail"),
            new("NSX masaüstü yazılımları Windows ortamında çalışır. Ürün özel gereksinimleri destek ekibinden doğrulanabilir.", "NSX desktop software runs on Windows. Product-specific requirements can be confirmed with our support team.", "/Store/Detail"),
            new("Kurulum desteği veriliyor mu?", "Is installation support available?", "/Store/Detail"),
            new("Evet. İhtiyaç halinde uzaktan bağlantı ile kurulum ve ilk kullanım desteği sağlanır.", "Yes. Remote installation and first-use support is available when needed.", "/Store/Detail"),
            new("Lisansı nasıl teslim alırım?", "How do I receive my license?", "/Store/Detail"),
            new("Ödeme onayından sonra lisans kullanıcı hesabına tanımlanır ve indirme erişimi açılır.", "After payment approval, the license is assigned to the user account and download access is enabled.", "/Store/Detail"),
            new("Başka bir soru sorun →", "Ask another question →", "/Store/Detail"),
            new("Banka", "Bank", "/Store/Detail"),
            new("Alıcı", "Account holder", "/Store/Detail"),
            new("IBAN", "IBAN", "/Store/Detail"),
            new("Açıklama", "Description", "/Store/Detail"),
            new("Lütfen boş bırakınız", "Please leave blank", "/Store/Detail"),
            new("Tutar", "Amount", "/Store/Detail"),
            new("Hesabınıza giriş yapın", "Sign in to your account", "/Store/Detail"),
            new("Demo / İndirme düğmesine basın", "Click the Demo / Download button", "/Store/Detail"),
            new("Dosyanıza güvenli şekilde erişin", "Access your file securely", "/Store/Detail"),
            new("NSX ürün galerisi", "NSX product gallery", "/Store/Detail"),
            new("ile gezinin", "to navigate", "/Store/Detail"),
            new("Ürün görselleri", "Product images", "/Store/Detail"),
            new("Galeriyi kapat", "Close gallery", "/Store/Detail"),
            new("Önceki görsel", "Previous image", "/Store/Detail"),
            new("Sonraki görsel", "Next image", "/Store/Detail"),
            new("Galeri küçük görselleri", "Gallery thumbnails", "/Store/Detail"),
            new("Deneyiminizi paylaşın", "Share your experience", "/Store/Comment"),
            new("Ürünü puanlayın ve dilerseniz kısa bir yorum bırakın.", "Rate the product and optionally leave a short review.", "/Store/Comment"),
            new("Puanınız", "Your rating", "/Store/Comment"),
            new("Yorumunuz", "Your review", "/Store/Comment"),
            new("isteğe bağlı", "optional", "/Store/Comment"),
            new("Değerlendirmeyi Gönder", "Submit Review", "/Store/Comment"),
            new("Ürün puanı", "Product rating", "/Store/Comment"),
            new("Ürünle ilgili deneyiminizi yazın...", "Write about your experience with the product...", "/Store/Comment"),
            new("NSX Yazılım Kütüphanesi", "NSX Software Library", "/Store"),
            new("İşinize uygun yazılımı", "Find the software that fits your business", "/Store"),
            new("kolayca keşfedin.", "with ease.", "/Store"),
            new("Cari hesaptan teknik servise, otomotivden klinik ve organizasyona kadar işletmeniz için geliştirilen NSX çözümlerini tek ekranda karşılaştırın.", "Compare NSX solutions for your business in one place, from account tracking and technical service to automotive, clinic and event management.", "/Store"),
            new("Kolay kurulum", "Easy installation", "/Store"),
            new("İşletme Yazılımları", "Business Software", "/Store"),
            new("Profesyonel NSX çözümleri", "Professional NSX solutions", "/Store"),
            new("Kullanıma hazır", "Ready to use", "/Store"),
            new("Yazılım Kütüphanesi", "Software Library", "/Store"),
            new("Tek noktadan keşfet", "Discover in one place", "/Store"),
            new("Hızlı", "Fast", "/Store"),
            new("Yerli", "Local", "/Store"),
            new("NSX desteği", "NSX support", "/Store"),
            new("Güvenli", "Secure", "/Store"),
            new("Profesyonel kullanım", "Professional use", "/Store"),
            new("İşletmeniz için doğru çözümü seçin.", "Choose the right solution for your business.", "/Store"),
            new("Kategoriye göre filtreleyin, ürünleri karşılaştırın ve ihtiyacınıza en uygun NSX yazılımının detaylarını inceleyin.", "Filter by category, compare products and review the details of the NSX software that best fits your needs.", "/Store"),
            new("Önerilen", "Recommended", "/Store"),
            new("En yeni", "Newest", "/Store"),
            new("Fiyat: düşükten yükseğe", "Price: low to high", "/Store"),
            new("Fiyat: yüksekten düşüğe", "Price: high to low", "/Store"),
            new("Ara", "Search", "/Store"),
            new("Stokta yok", "Out of stock", "/Store"),
            new("Kampanyalı fiyat", "Sale price", "/Store"),
            new("Başlangıç", "Starting at", "/Store"),
            new("Ürün bulunamadı", "No products found", "/Store"),
            new("Arama kriterlerinizi değiştirerek tekrar deneyin.", "Change your search criteria and try again.", "/Store"),
            new("Tüm yazılımları göster", "Show all software", "/Store"),
            new("NSX yazılım avantajları", "NSX software benefits", "/Store"),
            new("Yazılımlarda ara", "Search software", "/Store"),
            new("Barkodlu Satış & Stok", "Barcode Sales & Inventory", "/Shared/Footer"),
            new("Cari & Veresiye Takip", "Account & Receivables Tracking", "/Shared/Footer"),
            new("Düğün & Organizasyon", "Wedding & Event Management", "/Shared/Footer"),
            new("Klinik & Randevu", "Clinic & Appointment", "/Shared/Footer"),
            new("Kurumsal & Yasal", "Corporate & Legal", "/Shared/Footer"),
            new("Yerli & Güvenli", "Local & Secure", "/Home"),
            new("Gelişmiş takip", "Advanced tracking", "/Home"),
            new("Detaylı raporlar", "Detailed reports", "/Home"),
            new("NSX Veresiye Pro program ekranı", "NSX Veresiye Pro application screen", "/Home"),
            new("Rezervasyon ve salon planlama", "Reservation and venue planning", "/Store/Features"),
            new("Sözleşme oluşturma", "Contract creation", "/Store/Features"),
            new("Cari ve kasa takibi", "Account and cash tracking", "/Store/Features"),
            new("SMS bilgilendirme", "SMS notifications", "/Store/Features"),
            new("Müşteri yönetimi", "Customer management", "/Store/Features"),
            new("Etkinlik takvimi", "Event calendar", "/Store/Features"),
            new("Çok kullanıcılı yapı", "Multi-user structure", "/Store/Features"),
            new("Cari hesap yönetimi", "Account management", "/Store/Features"),
            new("Komisyon hesaplama", "Commission calculation", "/Store/Features"),
            new("Tahsilat takibi", "Collection tracking", "/Store/Features"),
            new("Gelişmiş raporlar", "Advanced reports", "/Store/Features"),
            new("Veri yedekleme", "Data backup", "/Store/Features"),
            new("Servis kabul", "Service intake", "/Store/Features"),
            new("Parça ve işçilik", "Parts and labor", "/Store/Features"),
            new("Araç geçmişi", "Vehicle history", "/Store/Features"),
            new("Cari hesap", "Account", "/Store/Features"),
            new("Müşteri takibi", "Customer tracking", "/Store/Features"),
            new("Servis raporları", "Service reports", "/Store/Features"),
            new("Araç stok yönetimi", "Vehicle inventory management", "/Store/Features"),
            new("Kapora takibi", "Deposit tracking", "/Store/Features"),
            new("Kâr ve zarar", "Profit and loss", "/Store/Features"),
            new("Cari takip", "Account tracking", "/Store/Features"),
            new("Satış raporları", "Sales reports", "/Store/Features"),
            new("QR canlı takip", "Live QR tracking", "/Store/Features"),
            new("SMS bildirimi", "SMS notifications", "/Store/Features"),
            new("Müşteri onayı", "Customer approval", "/Store/Features"),
            new("Cihaz geçmişi", "Device history", "/Store/Features"),
            new("Canlı durum takibi", "Live status tracking", "/Store/Features"),
            new("Hasta yönetimi", "Patient management", "/Store/Features"),
            new("Randevu takibi", "Appointment tracking", "/Store/Features"),
            new("Kapı üstü sıra", "Door display queue", "/Store/Features"),
            new("Hasta monitörü", "Patient monitor", "/Store/Features"),
            new("Sesli çağrı", "Voice calling", "/Store/Features"),
            new("Servis fişi", "Service ticket", "/Store/Features"),
            new("Cihaz kabul", "Device intake", "/Store/Features"),
            new("Arıza takibi", "Fault tracking", "/Store/Features"),
            new("Teslim yönetimi", "Delivery management", "/Store/Features"),
            new("Cari kartlar", "Account cards", "/Store/Features"),
            new("Borç ve alacak", "Debit and credit", "/Store/Features"),
            new("Hatırlatmalar", "Reminders", "/Store/Features"),
            new("Hızlı temizlik", "Quick cleanup", "/Store/Features"),
            new("Performans modu", "Performance mode", "/Store/Features"),
            new("Tek tık optimizasyon", "One-click optimization", "/Store/Features"),
            new("Başlangıç yönetimi", "Startup management", "/Store/Features"),
            new("Sistem araçları", "System tools", "/Store/Features"),
            new("Güvenli veri", "Secure data", "/Store/Features"),
            new("Windows uyumu", "Windows compatibility", "/Store/Features"),
            new("NSX Turbo Performans Programı ile FPS değerlerini iyileştirin, ping ve gecikmeyi azaltın; oyunlarda daha akıcı, hızlı ve kararlı performans elde edin.", "Improve FPS, reduce ping and latency, and get smoother, faster and more stable gaming performance with NSX Turbo Performance Pro.", "/Products/Turbo"),
            new("NSX Turbo – Maksimum Performans, Tek Tık Ultra Güç", "NSX Turbo – Maximum Performance, One-Click Power", "/Products/Turbo"),
            new("Bilgisayarını sınırlarına kadar zorla.", "Push your PC to its limits.", "/Products/Turbo"),
            new("NSX Turbo, sistemini analiz eder, optimize eder ve tek tıkla gerçek performans açığa çıkarır.", "NSX Turbo analyzes and optimizes your system, unlocking real performance with one click.", "/Products/Turbo"),
            new("Oyun Modu (Game Mode)", "Game Mode", "/Products/Turbo"),
            new("Oyun başlatmadan önce tek tuşla aktif et:", "Enable it with one click before starting a game:", "/Products/Turbo"),
            new("Arka plan işlemleri temizlenir", "Background processes are cleaned up", "/Products/Turbo"),
            new("CPU önceliği artırılır", "CPU priority is increased", "/Products/Turbo"),
            new("RAM optimize edilir", "RAM is optimized", "/Products/Turbo"),
            new("Sistem gecikmesi düşürülür", "System latency is reduced", "/Products/Turbo"),
            new("Maksimum FPS hedeflenir", "Maximum FPS is targeted", "/Products/Turbo"),
            new("Daha akıcı oyun, daha stabil performans.", "Smoother gameplay and more stable performance.", "/Products/Turbo"),
            new("GPU Akıllı Optimizasyon", "Smart GPU Optimization", "/Products/Turbo"),
            new("Ekran kartını otomatik tanır ve en iyi ayarı uygular:", "Automatically detects your graphics card and applies the best settings:", "/Products/Turbo"),
            new("NVIDIA kartlarda performans profili", "Performance profile for NVIDIA graphics cards", "/Products/Turbo"),
            new("AMD kartlarda sistem tabanlı boost", "System-based boost for AMD graphics cards", "/Products/Turbo"),
            new("Intel GPU’larda optimize edilmiş çalışma", "Optimized operation for Intel GPUs", "/Products/Turbo"),
            new("Donanıma özel akıllı güç yönetimi.", "Smart power management tailored to your hardware.", "/Products/Turbo"),
            new("Akıllı Sistem Analizi", "Smart System Analysis", "/Products/Turbo"),
            new("Bilgisayarını detaylı şekilde analiz eder:", "Analyzes your computer in detail:", "/Products/Turbo"),
            new("CPU, GPU, RAM durumu", "CPU, GPU and RAM status", "/Products/Turbo"),
            new("Gerçek zamanlı performans verileri", "Real-time performance data", "/Products/Turbo"),
            new("Sistem darboğaz tespiti", "System bottleneck detection", "/Products/Turbo"),
            new("Her zaman kontrol sende.", "You stay in control at all times.", "/Products/Turbo"),
            new("NSX Yazılım", "NSX Software", "/Shared"),
            new("NSX Rehber", "NSX Guides", "/Blog"),
            new("Tamam", "OK", "/Shared"),
            new("NSX_Kurulum.exe", "NSX_Kurulum.exe", "/Shared/InstallGuide"),
            new("Bu dosya başka bir bilgisayardan geldi. Güvenliği doğrulamak için engellendi.", "This file came from another computer and might be blocked to help protect this computer.", "/Shared/InstallGuide"),
            new("Tür:", "Type:", "/Shared/InstallGuide"),
            new("Konum:", "Location:", "/Shared/InstallGuide"),
            new("Özellikler penceresi örneği", "Properties window example", "/Shared/InstallGuide"),
        };
    }
}
