namespace NSYazilim.Web.Services
{
    /// <summary>
    /// Reviewed-at-build admin UI pack. Only source-code UI literals are included;
    /// customer, order and payment data is never sent to a translation provider.
    /// </summary>
    public static class LocalizationAdminSeedData
    {
        public static readonly IReadOnlyList<LocalizationSeedItem> Items = new LocalizationSeedItem[]
        {
            new("% aktif", "% active", "/Admin"),
            new("(Pasif)", "(Inactive)", "/Admin"),
            new("1 Yıl", "1 Year", "/Admin"),
            new("1 Yıllık", "1 Year", "/Admin"),
            new("30+ gün pasif", "30+ days passive", "/Admin"),
            new("30+ gün veya hiç kontrol yok", "30+ days or no control", "/Admin"),
            new("600 x 400 px - kampanya/popup alanı", "600 x 400 px - campaign/popup space", "/Admin"),
            new("728 x 90 px - program içi üst reklam", "728 x 90 px - built-in top advertising", "/Admin"),
            new("728 x 90 px - site içi kullanım", "728 x 90 px - in-site usage m", "/Admin"),
            new("728 x 90 px - ücretsiz sürüm alt reklam", "728 x 90 px - free version sub advertising", "/Admin"),
            new("728 x 90 reklam görseli", "728 x 90 advertising visual", "/Admin"),
            new("81 il bayi yapısı, bayi hesapları ve satış kâr oranlarını mevcut sipariş sisteminden ayrı bir kanalda yönetin.", "Manage 81 province dealer structure, dealer accounts and sales profit rates in a separate channel from the current order system.", "/Admin"),
            new("API Anahtarı", "API Key", "/Admin"),
            new("API Servisleri", "API Services", "/Admin"),
            new("API Test", "API Testing", "/Admin"),
            new("API anahtarı ve offline lisans imza anahtarı durumu.", "API key and offline license signing key status.", "/Admin"),
            new("Active", "Active", "/Admin"),
            new("Admin Panel", "Admin Panel", "/Admin"),
            new("Admin menüsü", "Admin menu", "/Admin"),
            new("Admin notu veya reklam açıklaması", "Admin note or ad description", "/Admin"),
            new("Admin panel giriş ekranı", "Admin panel login screen", "/Admin"),
            new("Admin panelden iptal edildi", "cancelled from admin panel", "/Admin"),
            new("Aktif", "Active", "/Admin"),
            new("Aktif Bayi", "Active Dealer", "/Admin"),
            new("Aktif Cihaz", "Active Device", "/Admin"),
            new("Aktif Et", "Active", "/Admin"),
            new("Aktif Kurulum İstatistikleri", "Active Installation Statistics", "/Admin"),
            new("Aktif Paket", "Active Package", "/Admin"),
            new("Aktif Reklam", "Active Advertising", "/Admin"),
            new("Aktif Sayfa", "Active Page", "/Admin"),
            new("Aktif Yap", "Active", "/Admin"),
            new("Aktif lisans / toplam lisans", "Active license / total license", "/Admin"),
            new("Aktif müşteri", "Active customer", "/Admin"),
            new("Aktif paket / toplam paket", "Active package / total package", "/Admin"),
            new("Aktif reklam / toplam reklam", "Active Advertising / Total Advertising", "/Admin"),
            new("Aktif yayınla", "Publish as active", "/Admin"),
            new("Aktif/Pasif", "Active/Inactive", "/Admin"),
            new("Akıllı Arama", "Smart Search", "/Admin"),
            new("Alt Başlık", "Sub Title", "/Admin"),
            new("Altı çizili", "Underline", "/Admin"),
            new("Alıcı Grubu", "Buyer Group", "/Admin"),
            new("Alınan Ücret", "Received Fee", "/Admin"),
            new("Alıntı / Önemli Not", "Quote / Important Note", "/Admin"),
            new("Ana Cihaz Yap", "Main Device", "/Admin"),
            new("Ana cihaz", "Main device", "/Admin"),
            new("Ana sayfa için sınırsız slider ekleyebilirsin.", "You can add unlimited sliders for the home page.", "/Admin"),
            new("Ana sayfa slider görsellerini, ürün bağlantılarını ve sıralamayı yönet.", "Manage home slider images, product connections and ranking.", "/Admin"),
            new("Ana sayfada ve sliderda bu kod gösterilir.", "This code is shown on the home page and slider.", "/Admin"),
            new("Anasayfa", "Dashboard", "/Admin"),
            new("Anlık Canlı Destek", "Real-Time Live Support", "/Admin"),
            new("Askıda", "On Hold", "/Admin"),
            new("Aylık Gelişim", "Monthly Development", "/Admin"),
            new("Aylık trafik grafiği", "Monthly traffic chart", "/Admin"),
            new("Aynı ürünün eski aktif paketleri otomatik pasif olur.", "The old active packages of the same product are passive automatically.", "/Admin"),
            new("Açık kalırsa sipariş tamamlandı olarak kaydedilir ve seçili üyeye lisans anahtarı otomatik oluşturulur.", "If the order remains open, the order is recorded and the license key to the selected member is created automatically.", "/Admin"),
            new("Açıklama biçimlendirme araçları", "Description formatting tools", "/Admin"),
            new("Açıklama yok", "No Description", "/Admin"),
            new("Banner görseli yok", "No banner images", "/Admin"),
            new("Banner görseli, URL, program kodu, yayın durumu ve geçiş süresini düzenleyin.", "Edit banner visual, URL, program code, broadcast status and pass time.", "/Admin"),
            new("Bayi", "Dealer", "/Admin"),
            new("Bayi / Firma Adı", "Dealer / Company Name", "/Admin"),
            new("Bayi Düzenle", "Dealer Layout", "/Admin"),
            new("Bayi Giris Sifresi", "Dealer Login", "/Admin"),
            new("Bayi Listesi", "Dealer List", "/Admin"),
            new("Bayi Satışları", "Dealer Sales", "/Admin"),
            new("Bayi Satışı", "Dealer Sales", "/Admin"),
            new("Bayi hesabı, il bilgisi ve satıştan verilecek kâr modelini tanımlayın.", "Identify the profit model that will be given from dealer account, il knowledge and sales.", "/Admin"),
            new("Bayi tarafından oluşturulan satışları, müşteri e-postasını, lisans durumunu ve bayi alacağını kontrol edin.", "Check the sales generated by the dealer, customer email, license status and dealer.", "/Admin"),
            new("Bayilere Dön", "Return to Dealers", "/Admin"),
            new("Bayilik Yönetimi", "Dealership Management", "/Admin"),
            new("Bağlandı", "Connected", "/Admin"),
            new("Bağlantı adresini yazın (https://... veya /sayfa):", "Type the link address (https://... or/page):", "/Admin"),
            new("Bağlantı ekle", "Add link", "/Admin"),
            new("Bağlantı kesildi. Dosya yükleme başarısız oldu.", "Disconnected. File installation failed.", "/Admin"),
            new("Bağlantı kurulamadı", "The connection was not installed", "/Admin"),
            new("Bağlantıyı girin ve videonun ait olduğu programı seçin.", "Enter the link and select the program owned by the video.", "/Admin"),
            new("Bağlantıyı yapıştırınca kapak burada görünür.", "If you glue the link, the cover will appear here.", "/Admin"),
            new("Bağlanıyor...", "Connect...", "/Admin"),
            new("Bağlı program:", "Affiliate Program:", "/Admin"),
            new("Bağlı Ürün", "Connected Product", "/Admin"),
            new("Başarılı", "Successful", "/Admin"),
            new("Başarısız", "Failed", "/Admin"),
            new("Başlangıç Tarihi", "Start Date", "/Admin"),
            new("Başlangıç yok", "No Start", "/Admin"),
            new("Başlık", "Title", "/Admin"),
            new("Başlıksız sayfa", "Titleless page", "/Admin"),
            new("Bekliyor", "Wait", "/Admin"),
            new("Beni hatırla", "Remember Me", "/Admin"),
            new("Bir konuşma seçerek müşteriye cevap yazabilirsiniz.", "By choosing a conversation, you can answer the customer.", "/Admin"),
            new("Bir program ve reklam alanında birden fazla aktif reklam varsa, sistem her reklamın geçiş süresine göre sıradaki reklamı otomatik döndürür.", "If there are multiple active ads in a program and advertising field, the system automatically returns the ad on the row according to the transition time of each ad.", "/Admin"),
            new("Bir ürün için aktif hale getirilen paket, aynı ürünün diğer aktif paketlerini otomatik pasif yapar. Böylece program her zaman tek güncel paketi görür.", "The package, which is activated for a product, makes other active packages of the same product automatically passive. Thus, the program always sees one-to-date package.", "/Admin"),
            new("Bitiş Tarihi", "Finish Date", "/Admin"),
            new("Bitiş yok", "No", "/Admin"),
            new("Biçimi temizle", "Clear format", "/Admin"),
            new("Boş bırakılabilir", "Empty", "/Admin"),
            new("Boş bırakılırsa otomatik", "Automatic if left", "/Admin"),
            new("Boş bırakırsan mevcut banner korunur. Önerilen: 728 x 90 px. PNG, JPG veya WEBP kullanabilirsin.", "The existing banner is protected if you leave empty. Recommended: 728 x 90 px. You can use PNG, JPG or WEBP.", "/Admin"),
            new("Boş bırakırsanız program adı kullanılır", "Program name is used if you leave empty", "/Admin"),
            new("Bu Ay Tekil Ziyaretçi", "This Month Tekil Visitor", "/Admin"),
            new("Bu bayi satis kaydi silinsin mi? Siparis, havale ve lisans kayitlari korunur.", "Do you delete this dealer? Siparis is protected from weather and license.", "/Admin"),
            new("Bu canlı destek konuşması silinsin mi?", "Do you delete this live support conversation?", "/Admin"),
            new("Bu cihaz ana cihaz yapılsın mı?", "Does this device build main device?", "/Admin"),
            new("Bu cihaz engeli kaldırılsın mı?", "Does this device unblock?", "/Admin"),
            new("Bu cihaz engellensin mi?", "Are you blocked this device?", "/Admin"),
            new("Bu demo indirme kaydı silinsin mi?", "Delete this demo download record?", "/Admin"),
            new("Bu dosya mutlaka yedeklenmeli. Kaybolursa eski offline lisanslarla uyumluluk riske girer.", "This file must be backed up. The compatibility with old offline licenses enters the risk.", "/Admin"),
            new("Bu ekran müşterinin cari, borç, işlem veya özel program verilerini toplamaz. Kullanım durumu yalnızca başarılı lisans doğrulamasının son görülme bilgisinden hesaplanır.", "This screen does not collect client’s car, debt, transaction or private program data. The status of use is calculated only from the latest information of successful licensing.", "/Admin"),
            new("Bu güncelleme aktif olsun", "Get this update active", "/Admin"),
            new("Bu güncelleme paketi silinsin mi?", "Delete this update package?", "/Admin"),
            new("Bu havale bildirimi silinsin mi?", "Do you delete this air notification?", "/Admin"),
            new("Bu işlem sadece bu reklama ait gösterim ve tıklama sayılarını sıfırlar.", "This process only resets the views and click numbers of this ad.", "/Admin"),
            new("Bu kampanya şart sağlanınca satın alma bildirimi sırasında değerlendirilir.", "This campaign is evaluated during the notification of purchase in the right place.", "/Admin"),
            new("Bu kategori silinsin mi?", "Do you delete this category?", "/Admin"),
            new("Bu kayıt normal sipariş gibi", "This registration is like normal order", "/Admin"),
            new("Bu kod programdaki sabit ProductCode ile aynı olmalı. Lisans, reklam ve güncelleme sistemleri bu koda bağlanır.", "This code should be the same as Fixed ProductCode in the program. License, advertising and update systems are connected to this code.", "/Admin"),
            new("Bu lisans silinsin mi?", "Do you delete this license?", "/Admin"),
            new("Bu lisansa ait tüm kontrol logları temizlenecek. Emin misiniz?", "All control logs of this license will be cleaned. Are you sure?", "/Admin"),
            new("Bu lisansa bağlı cihaz kaydı yok.", "No device registration attached to this license.", "/Admin"),
            new("Bu lisansın cihaz eşleşmesi sıfırlansın mı? Eski cihazlar pasife alınacak.", "Is this license reset device match? Older devices will be passive.", "/Admin"),
            new("Bu mail kaydı silinsin mi?", "Do you delete this mail record?", "/Admin"),
            new("Bu mesaj kaydı silinsin mi?", "Delete this message record?", "/Admin"),
            new("Bu offline sertifika iptal edilsin mi?", "Can you cancel this offline certificate?", "/Admin"),
            new("Bu offline sertifika tekrar aktif edilsin mi?", "Is this offline certificate activated again?", "/Admin"),
            new("Bu reklam aktif olsun", "Get this ad active", "/Admin"),
            new("Bu reklam silinsin mi?", "Do you delete this ad?", "/Admin"),
            new("Bu reklamın gösterim ve tıklama istatistikleri sıfırlansın mı?", "Are you reset the views and click statistics of this ad?", "/Admin"),
            new("Bu satış için otomatik lisans oluştur", "Create automatic license for this sale", "/Admin"),
            new("Bu sipariş kaydı silinsin mi? Lisanslar silinmez, sadece sipariş bağlantısı kaldırılır.", "Delete this order record? Licenses are not deleted, only the order connection is removed.", "/Admin"),
            new("Bu video kaydı silinsin mi? YouTube üzerindeki video silinmez.", "Delete this video record? The video on YouTube is not deleted.", "/Admin"),
            new("Bu ürün için henüz güncelleme paketi yok.", "There is no update pack yet for this product.", "/Admin"),
            new("Bu ürüne ait masaüstü program güncellemesini buradan yükle. Program kodu otomatik:", "Upload this product desktop program update here. Program code auto:", "/Admin"),
            new("Bu ürünü silmek/pasife almak istiyor musun?", "Do you want to delete/pasife this product?", "/Admin"),
            new("Bu üyeyi silmek/pasife almak istiyor musun?", "Do you want to delete/pasife this member?", "/Admin"),
            new("Bugün Aktif", "Today Active", "/Admin"),
            new("Bugün aktif", "Today active", "/Admin"),
            new("Bugün başarılı doğrulama", "Successful verification today", "/Admin"),
            new("Bugünkü Kazanç", "Earning Today", "/Admin"),
            new("Bugünkü Tekil Ziyaretçi", "Today's Tekil Visitor", "/Admin"),
            new("Bulunduğu Sayfa", "Current Page", "/Admin"),
            new("Buradaki başlık, paragraf, liste ve vurgular ürün detay sayfasında aynı düzenle gösterilir.", "The header, paragraph, list and highlight here are shown in the product detail page.", "/Admin"),
            new("Buton Yazısı", "Buton Font", "/Admin"),
            new("Büyük Başlık", "Large Title", "/Admin"),
            new("CANLI ZİYARETÇİ TAKİBİ", "LIVE VISITING", "/Admin"),
            new("Canlı API anahtarı varsayılan değerden farklı görünüyor.", "Live API key looks different from default value.", "/Admin"),
            new("Canlı Ziyaretçiler", "Live Visitors", "/Admin"),
            new("Canlı destek mesajı", "Live support message", "/Admin"),
            new("Canlı veriler alınamadı. Bağlantı tekrar denenecek.", "Live data could not be received. The connection will be repeated.", "/Admin"),
            new("Canlı ziyaretçi özeti", "Live visitor summary", "/Admin"),
            new("Canlı ziyaretçiler getiriliyor…", "Live visitors are brought...", "/Admin"),
            new("Canlı Önizleme", "Live Preview", "/Admin"),
            new("Canlıda", "Live", "/Admin"),
            new("Cihaz", "Device", "/Admin"),
            new("Cihaz / Tarayıcı", "Device / Scanner", "/Admin"),
            new("Cihaz Dağılımı", "Device Distribution", "/Admin"),
            new("Cihaz Limiti", "Device Limit", "/Admin"),
            new("Cihazı Sıfırla", "Reset Device", "/Admin"),
            new("Client", "Website", "/Admin"),
            new("Critical", "Critical", "/Admin"),
            new("DB ile eşleşen müşterilerin gerçek V2 lisans doğrulama hareketlerinden oluşturulan kullanım görünümü.", "The appearance of use created from real V2 license verification movements of customers matching with DB.", "/Admin"),
            new("DB üye + lisans eşleşmesi", "DB member + license match", "/Admin"),
            new("Demo Program Dosyası", "Demo Program File", "/Admin"),
            new("Demo Program Dosyası Değiştir", "Change Demo Program File", "/Admin"),
            new("Demo Program İndirenler", "Demo Program Downloads", "/Admin"),
            new("Demo dosyası yok.", "No demo file.", "/Admin"),
            new("Demo indiren müşterileri ve IP tahmini konum bilgilerini buradan takip edebilirsiniz.", "You can track demo download customers and IP forecast location information here.", "/Admin"),
            new("Demo program dosyası sunucudan tamamen silinsin mi?", "Are you completely deleted from the demo program file server?", "/Admin"),
            new("Demo İndirenler", "Demo Downloads", "/Admin"),
            new("Değişiklikleri Kaydet", "Save Changes", "/Admin"),
            new("Dil Kodu", "Language Code", "/Admin"),
            new("Dil Motoru", "Language Engine  u", "/Admin"),
            new("Dil bilgilerini düzenle", "Edit language information", "/Admin"),
            new("Dili Ekle", "Add Language", "/Admin"),
            new("Diller koddan bağımsız yönetilir. Yeni dil eklendiğinde veritabanı yapısı veya site kodu değişmez.", "Languages are governed independently from code. When the new language is added, the database structure or the site code does not change.", "/Admin"),
            new("Dosya", "File", "/Admin"),
            new("Dosya:", "File:", "/Admin"),
            new("Dosyalar yükleniyor", "Loading files", "/Admin"),
            new("Dosyayı aç / indir", "Open/Download File", "/Admin"),
            new("Durum", "Status", "/Admin"),
            new("Düzenle", "Edit", "/Admin"),
            new("Ekler eklemez aktif et ve site dil seçicisinde göster", "Show attachments in active meat and site language selector", "/Admin"),
            new("Eksik Tahmini Konumları Güncelle", "Update Miss Forecast Locations", "/Admin"),
            new("En az bir kez doğrulanan", "Validated at least once", "/Admin"),
            new("En fazla 10 görsel seçebilirsin.", "You can choose up to 10 images.", "/Admin"),
            new("En fazla 10 görsel yüklenir.", "Maximum 10 photos are uploaded.", "/Admin"),
            new("En son 50 gerçek ziyaret kaydı", "Last 50 real visits registration", "/Admin"),
            new("En son oluşturulan müşteri siparişleri.", "Last created customer orders.", "/Admin"),
            new("En Çok Görünen IP Tahmini Şehirler", "Top Viewed IP Forecast Cities", "/Admin"),
            new("En Çok Ziyaret Edilen Sayfalar", "Most Visited Pages", "/Admin"),
            new("Endpoint", "Endpoint", "/Admin"),
            new("Engeli Kaldır", "Remove Obstacle", "/Admin"),
            new("Engelli cihaz yok.", "No disabled devices.", "/Admin"),
            new("Eğitim", "Training", "/Admin"),
            new("Eşleşen Lisans", "Matched License", "/Admin"),
            new("Eşleşen Müşteri", "Matched Customer", "/Admin"),
            new("Failed", "Tags", "/Admin"),
            new("Farklı cihaz, ürün uyuşmazlığı, crack/tamper bildirimi ve güvenlik olayları.", "Different devices, product numbness, crack/fullper notification and security events.", "/Admin"),
            new("Filtrele", "Filter", "/Admin"),
            new("Footer iletişim ve sağ alt canlı destek penceresinden gelen mesajları burada takip edebilirsiniz.", "You can follow the messages from the Footer dialog and the right bottom live support window here.", "/Admin"),
            new("Format: 1.0.2 / 1.0.3 gibi olmalı.", "Format: 1.0.2/1.0.3.", "/Admin"),
            new("Français", "English", "/Admin"),
            new("Gelen Form Alanları:", "In Form Areas:", "/Admin"),
            new("Gelişmiş Ayarlar", "Advanced Settings", "/Admin"),
            new("Geniş Ürün Açıklaması", "Wide Product Description", "/Admin"),
            new("Genişlik", "Width", "/Admin"),
            new("Geri", "Back", "/Admin"),
            new("Geri al", "Get back", "/Admin"),
            new("Geri dön", "Back", "/Admin"),
            new("Geçiş Süresi / sn", "Pass Time/s", "/Admin"),
            new("Giriş Yapan", "Login", "/Admin"),
            new("Google Cloud / DeepL etkinleşene kadar kuyruk güvenle bekler.", "The tail until Google Cloud / DeepL activates safely awaits.", "/Admin"),
            new("Gönderildi", "Sended", "/Admin"),
            new("Gönderim Devam Ediyor...", "Shipping Continue...", "/Admin"),
            new("Gönderim Özeti", "Submission Summary", "/Admin"),
            new("Görsel", "Visual", "/Admin"),
            new("Görsel açıklaması", "Visual description", "/Admin"),
            new("Görsel silinsin mi?", "Delete a visual?", "/Admin"),
            new("Görsel yok.", "No images.", "/Admin"),
            new("Görsel, ürün bağlantısı, sıra ve yayın durumunu düzenle.", "Edit visual, product connection, sequence and broadcast status.", "/Admin"),
            new("Görseller", "Visuals", "/Admin"),
            new("Gösterilen kayıt · en fazla 1000", "Shown Registration · up to 1000", "/Admin"),
            new("Gösterim", "Views", "/Admin"),
            new("Gösterim:", "Views:", "/Admin"),
            new("Güncelle", "Update", "/Admin"),
            new("Güncelleme API", "Update API", "/Admin"),
            new("Güncelleme Dosyası Ekle", "Add Update File", "/Admin"),
            new("Güncelleme Ekle", "Add Update", "/Admin"),
            new("Güncelleme Notu", "Update Note", "/Admin"),
            new("Güncelleme Paketini Kaydet", "Save Update Package", "/Admin"),
            new("Güncelleme ZIP", "Update ZIP", "/Admin"),
            new("Güncelleme ZIP dosyaları artık ilgili ürünün", "Update ZIP files no longer related product", "/Admin"),
            new("Güncelleme dosyası silinsin mi?", "Delete the update file?", "/Admin"),
            new("Günlük Trafik", "Daily Traffic", "/Admin"),
            new("Günlük trafik grafiği", "Daily traffic chart", "/Admin"),
            new("Günlük ve aylık ziyaretleri, tekil kullanıcıları, popüler sayfaları ve cihaz dağılımını tek ekrandan takip edin.", "Track daily and monthly visits, single users, popular pages and device distribution from one screen.", "/Admin"),
            new("Hatalı", "Error", "/Admin"),
            new("Hatalı:", "Error:", "/Admin"),
            new("Havale", "Bank Transfer", "/Admin"),
            new("Havale Bildirimi Listesi", "Bank Transfer Notification List", "/Admin"),
            new("Havale Bildirimleri", "Bank Transfer Notifications", "/Admin"),
            new("Havale Onayları", "Air Approvals", "/Admin"),
            new("Hayır", "No", "/Admin"),
            new("Henüz aktif konuşma yok.", "No active conversation yet.", "/Admin"),
            new("Henüz bayi hesabı oluşturulmadı.", "Not yet the dealer account was created.", "/Admin"),
            new("Henüz cihaz kaydı yok.", "No device registration yet.", "/Admin"),
            new("Henüz demo indirme kaydı yok.", "No demo downloads yet.", "/Admin"),
            new("Henüz güncelleme paketi eklenmemiş.", "Not yet added the update package.", "/Admin"),
            new("Henüz havale bildirimi yok.", "No air notice yet.", "/Admin"),
            new("Henüz kampanya yok.", "No campaign yet.", "/Admin"),
            new("Henüz kayıt yok.", "No registration yet.", "/Admin"),
            new("Henüz kupon yok.", "No coupon yet.", "/Admin"),
            new("Henüz lisans yok.", "No license yet.", "/Admin"),
            new("Henüz mail kaydı yok.", "No email registration yet.", "/Admin"),
            new("Henüz mesaj yok.", "No message yet.", "/Admin"),
            new("Henüz offline sertifika yok.", "No offline certificate yet.", "/Admin"),
            new("Henüz reklam eklenmemiş. İlk 728 x 90 banner reklamını ekleyerek başlayabilirsin.", "Not yet advertised. You can start adding the first 728 x 90 banner ads.", "/Admin"),
            new("Henüz sipariş yok.", "No order yet.", "/Admin"),
            new("Henüz slider eklenmedi. Ürün ekleme/düzenleme ekranından veya Yeni Slider butonundan ekleyebilirsin.", "Not yet add sliders. You can add the product from the insert/flating screen or the New Slider button.", "/Admin"),
            new("Henüz tahmini konum verisi yok", "No estimated location data yet", "/Admin"),
            new("Henüz video eklenmedi", "Not yet add videos", "/Admin"),
            new("Henüz yok", "No", "/Admin"),
            new("Henüz ziyaret verisi oluşmadı.", "Not yet visited data.", "/Admin"),
            new("Henüz ürün eklenmedi.", "Not yet add products.", "/Admin"),
            new("Henüz şüpheli kayıt yok.", "No suspicious registration yet.", "/Admin"),
            new("Her iki değeri de kaydedebilirsiniz. Satışta", "You can also save both values. Sales", "/Admin"),
            new("Her video yalnızca seçtiğiniz programa bağlı çalışır.", "Every video only works depending on the program you choose.", "/Admin"),
            new("Hiç doğrulanmayan", "No verification", "/Admin"),
            new("IP / Şehir", "IP / City", "/Admin"),
            new("Info", "Info", "/Admin"),
            new("KALICI TRAFİK ANALİZİ", "CHICIENT TRAFFIC ANALYSIS", "/Admin"),
            new("Kalın", "Close", "/Admin"),
            new("Kampanya & Kupon Sistemi", "Campaign & Coupon System", "/Admin"),
            new("Kampanya / Kupon", "Campaign / Coupon", "/Admin"),
            new("Kampanya Adı", "Campaign Name", "/Admin"),
            new("Kampanya Düzenle", "Campaign Layout", "/Admin"),
            new("Kampanya Kodu", "Campaign Code", "/Admin"),
            new("Kampanya gönder", "Offer", "/Admin"),
            new("Kampanya silinsin mi?", "Do you delete the campaign?", "/Admin"),
            new("Kapak görseli", "Cover visual", "/Admin"),
            new("Kapalı", "Close", "/Admin"),
            new("Kategori", "Category", "/Admin"),
            new("Kategori Ekle", "Add Category", "/Admin"),
            new("Kategori adı", "Category name", "/Admin"),
            new("Kategori seçin", "Select Category", "/Admin"),
            new("Kategoriyi Sil", "Delete Category", "/Admin"),
            new("Kaydet", "Save", "/Admin"),
            new("Kaynak metinde ara...", "Search in source text...", "/Admin"),
            new("Kayıtlı", "Register", "/Admin"),
            new("Kayıtlı üye bulunmuyor.", "No registered members.", "/Admin"),
            new("Kompakt görünüm", "Compact view", "/Admin"),
            new("Kontrol Logları", "Control Logs", "/Admin"),
            new("Konuşma seçin", "Select conversation", "/Admin"),
            new("Konuşmalar", "Conversations", "/Admin"),
            new("Kullanıcıya zorunlu güncelleme olarak göster", "Show user as mandatory update", "/Admin"),
            new("Kullanım", "Usage", "/Admin"),
            new("Kullanım Limiti", "Usage Limit", "/Admin"),
            new("Kupon Güncelle", "Coupon Update", "/Admin"),
            new("Kupon aktif olsun", "Get Coupon Active", "/Admin"),
            new("Kâr Hesaplama Türü", "Profit Calculation Type", "/Admin"),
            new("Kâr Oranı (%)", "Profit Rate (%)", "/Admin"),
            new("Küçük sayı önce gösterilir.", "The small number is shown first.", "/Admin"),
            new("Kısa Açıklama", "Short Description", "/Admin"),
            new("Kısa açıklama", "Short description", "/Admin"),
            new("LicenseApi:ApiKey kullanılıyor", "LicenseApi:ApiKey is used", "/Admin"),
            new("Lifetime", "Lifetime", "/Admin"),
            new("Lisans API", "License API", "/Admin"),
            new("Lisans Anahtarı", "License Key", "/Admin"),
            new("Lisans Cihazları", "License Devices", "/Admin"),
            new("Lisans Düzenle", "License Layout", "/Admin"),
            new("Lisans Güvenlik Ayarları", "License Security Settings", "/Admin"),
            new("Lisans Kontrol Logları", "License Control Logs", "/Admin"),
            new("Lisans Listesi", "License List", "/Admin"),
            new("Lisans Tipi", "License Type", "/Admin"),
            new("Lisans Yönetimi", "License Management", "/Admin"),
            new("Lisans güvenlik loglarının tamamını kalıcı olarak silmek istiyor musunuz? Bu işlem geri alınamaz.", "Do you want to permanently delete all license security logs? This process cannot be taken back.", "/Admin"),
            new("Lisans kontrol loglarının tamamını kalıcı olarak silmek istiyor musunuz? Bu işlem geri alınamaz.", "Do you want to permanently delete all license control logs? This process cannot be taken back.", "/Admin"),
            new("Lisans kuralı:", "License rule:", "/Admin"),
            new("Lisans oluşturulamadı.", "The license cannot be created.", "/Admin"),
            new("Lisans sahibi üyeler", "License members", "/Admin"),
            new("Lisans ve güncelleme sistemindeki ürün koduyla aynı olmalı.", "The license and update system should be the same as the product code.", "/Admin"),
            new("Lisans, güncelleme ve reklam servislerini tek ekrandan kontrol edin.", "Check license, update and advertising services from one screen.", "/Admin"),
            new("Lisanslara Dön", "Return to Licenses", "/Admin"),
            new("Lisanslara bağlanan cihazları ve son görülme bilgilerini takip et.", "Follow the devices connected to the licenses and the latest visibility information.", "/Admin"),
            new("Liste başında göster", "Show list", "/Admin"),
            new("Listeye Dön", "Back to List", "/Admin"),
            new("Listeyi Temizle / Sil", "Clear / Delete List", "/Admin"),
            new("Logları Temizle", "Clear Logs", "/Admin"),
            new("Madde işaretli liste", "Item marked list", "/Admin"),
            new("Mail gönderildi", "Mail sent", "/Admin"),
            new("Mail gönderilemedi / kayıt alındı", "Mail submission / registration was received", "/Admin"),
            new("Mail gönderimi SMTP ayarlarını kullanır. Gmail için uygulama şifresi gereklidir.", "Mail shipping uses SMTP settings. App password for Gmail is required.", "/Admin"),
            new("Maksimum 300 MB. Dosya otomatik olarak /wwwroot/updates/urun-kodu/versiyon/update.zip içine kaydedilir.", "Maximum 300 MB. The file is automatically saved into /wwwroot/updates/urun-kodu/version/update.zip.", "/Admin"),
            new("Manuel Lisans Oluştur", "Create Manual License", "/Admin"),
            new("Manuel Sabit Kâr (TL / Satış)", "Manual Fixed Profit (TL / Sales)", "/Admin"),
            new("Manuel Satış", "Manual Sales", "/Admin"),
            new("Manuel Satış Gir", "Manual Sales Input", "/Admin"),
            new("Manuel Satışı Kaydet", "Save Manual Sale", "/Admin"),
            new("Manuel satış kaydedilemedi.", "Manual sale is not recorded.", "/Admin"),
            new("Mağaza filtrelerinde ve ürün kartlarında kullanılacak kategorileri yönetin.", "Manage categories to be used in store filters and product cards.", "/Admin"),
            new("Mağaza filtresi ve ürün detayındaki kategori etiketi bu seçimden gelir.", "The category tag in store filter and product detail comes from this choice.", "/Admin"),
            new("Mesaj", "Message", "/Admin"),
            new("Mesajlar / Canlı Destek", "Messages / Live Support", "/Admin"),
            new("Meta Açıklama", "Meta Description", "/Admin"),
            new("Meta Başlık", "Meta Title", "/Admin"),
            new("Metin biçimi", "Text format", "/Admin"),
            new("Mevcut Görseller", "Available Visuals", "/Admin"),
            new("Mevcut Slider Görseli", "Available Slider Visual", "/Admin"),
            new("Mobil hızlı erişim", "Mobile quick access", "/Admin"),
            new("Mobil, tablet ve masaüstü kullanım oranları", "Mobile, tablet and desktop usage rates", "/Admin"),
            new("Müşteri mesajı gelince solda listelenir.", "Customer message is listed on the left.", "/Admin"),
            new("Müşteri notu:", "Customer note:", "/Admin"),
            new("Müşteri programlarının internet yokken kullanacağı imzalı lisans dosyaları.", "Signed license files that customer programs will use when they are not internet.", "/Admin"),
            new("Müşteri, e-posta, telefon, ürün veya sürüm...", "Customer, email, phone, product or version...", "/Admin"),
            new("Müşteriler site içindeki destek kutusundan yazdığında burada anında görünür. Yeni mesaj gelince uyarı sesi çalar.", "Customers appear instantly when they write from the support box on the site. Alarm sound when it comes to new message.", "/Admin"),
            new("Müşterilere gönderilecek mesaj...", "Send message to customers...", "/Admin"),
            new("Müşterilere kampanya, bilgilendirme ve ürün duyurularını profesyonel şablonla gönder.", "Send campaigns, information and product announcements to customers with professional templates.", "/Admin"),
            new("Müşterilerin gönderdiği havale/EFT bildirimlerini kontrol edin ve onaylayın.", "Check and confirm the weather/EFT notifications that customers send.", "/Admin"),
            new("Müşteriye cevap yazın...", "Reply to customer...", "/Admin"),
            new("NSX Admin Giriş", "NSX Admin Introduction", "/Admin"),
            new("NSX Reklam Merkezi", "NSX Advertising Center", "/Admin"),
            new("NSX Yazılım sitesinde şu anda aktif olan ziyaretçileri, gezdikleri sayfaları ve kullandıkları cihazları canlı olarak izleyin.", "Watch on NSX Software site currently active visitors, pages and devices they use live.", "/Admin"),
            new("NSX Yönetim Merkezi", "NSX Management Center", "/Admin"),
            new("NSX premium mail şablonu ile gönder", "Send NSX with premium mail template", "/Admin"),
            new("Numaralı liste", "Number list", "/Admin"),
            new("Offline", "Offline", "/Admin"),
            new("Offline Lisans", "Offline License", "/Admin"),
            new("Offline Lisans Sertifikaları", "Offline License Certificates", "/Admin"),
            new("Offline İmza Anahtarı", "Offline Signing Key", "/Admin"),
            new("Oluştur", "Create", "/Admin"),
            new("Oluşturma", "Created", "/Admin"),
            new("Onaylı", "Certificates", "/Admin"),
            new("Otomatik lisans", "Automatic license", "/Admin"),
            new("Oynatma ve trafik YouTube üzerinden çalışır. Plesk depolama alanı kullanılmaz.", "Play and traffic work on YouTube. Plesk storage is not used.", "/Admin"),
            new("PASİF", "PASIF", "/Admin"),
            new("Pasif", "Inactive", "/Admin"),
            new("Pasif / Doğrulanmamış", "Inactive / Unverified", "/Admin"),
            new("Pasif Yap", "Passive", "/Admin"),
            new("Pasif reklamlar API tarafından gösterilmez.", "Passive ads are not shown by API.", "/Admin"),
            new("Pending", "Tags  g", "/Admin"),
            new("Popup Reklam", "Popup Advertising", "/Admin"),
            new("Private key dosyası henüz oluşmamış. İlk offline lisans üretiminde oluşur.", "Private key file has not yet been created. It is formed in the production of the first offline license.", "/Admin"),
            new("Private key dosyası mevcut.", "Private key file available.", "/Admin"),
            new("Program Güncellemeleri", "Program Updates", "/Admin"),
            new("Program açılışta veya menüden kontrol edildiğinde buradaki aktif sürümü görecek.", "The program will see the active version here when it is checked in the opening or menu.", "/Admin"),
            new("Program bağlantısını, YouTube adresini ve yayın durumunu güncelleyin.", "Update the program link, YouTube address and broadcast status.", "/Admin"),
            new("Program bulunamadı", "Program not found", "/Admin"),
            new("Program seç, banner görselini yükle, URL ve geçiş süresini belirle.", "Select the program, upload banner visual, identify URL and pass time.", "/Admin"),
            new("Program seçildiğinde site tarafındaki başlık, açıklama, fiyat, stok ve işlem butonları o programdan otomatik alınır.", "When the program is selected, the header on the site side, description, price, stock and transaction buttons are automatically taken from that program.", "/Admin"),
            new("Program seçilmedi", "Program not selected", "/Admin"),
            new("Program seçin", "Select program", "/Admin"),
            new("Program seçince kod otomatik dolar. Gerekirse aşağıdan elle düzenleyebilirsin.", "Select program code automatically dollar. If necessary, you can edit it manually.", "/Admin"),
            new("Program tarafı bu bilgiye göre iptal seçeneğini kapatabilir.", "The program side may close the cancellation option according to this information.", "/Admin"),
            new("Program tarafındaki offline doğrulama bu public key ile yapılacak.", "The offline verification on the program side will be done with this public key.", "/Admin"),
            new("Program Üst Banner", "Program Top Banner", "/Admin"),
            new("Reklam", "Advertising", "/Admin"),
            new("Reklam API", "Advertising API", "/Admin"),
            new("Reklam Alanı", "Advertising Area", "/Admin"),
            new("Reklam Bilgileri", "Advertising Information", "/Admin"),
            new("Reklam Düzenle", "Advertising Edit", "/Admin"),
            new("Reklam Düzenleme", "Advertising Regulation", "/Admin"),
            new("Reklam Yönetimi", "Advertising Management", "/Admin"),
            new("Reklamlara Dön", "Back to Ads", "/Admin"),
            new("Reklamı Kaydet", "Save Advertisement", "/Admin"),
            new("Sadece demo program yüklenir. Tam sürüm/program dosyası alanı kaldırıldı.", "Only the demo program is installed. Full version/program file space removed.", "/Admin"),
            new("Sahada, havale ile veya dışarıdan aldığınız ödemeleri tek ekrandan sipariş/kazanç sistemine işleyin.", "Work in the field, by air or from the outside payments to the order/win system from one screen.", "/Admin"),
            new("Satın Alınan Ürün", "Purchased Product", "/Admin"),
            new("Satın alma sırasında değerlendirilecek kampanyaları yönetin.", "Manage campaigns to be evaluated during purchase.", "/Admin"),
            new("Satın alma, manuel lisans, cihaz eşleşmesi ve program konum bilgilerini tek ekrandan yönetin.", "Manage purchasing, manual license, device match and program location information from one screen.", "/Admin"),
            new("Satış Listesi", "Sales List", "/Admin"),
            new("Satış Tarihi", "Sales Date", "/Admin"),
            new("Satış ve lisans ayarı", "Sales and license setting", "/Admin"),
            new("Sayfa Görüntüleme", "Pageview", "/Admin"),
            new("Sayfa görüntüleme ve tekil ziyaretçi karşılaştırması", "View page and compare of single visitor", "/Admin"),
            new("Sayfa, IP, şehir, kullanıcı veya cihaz", "Page, IP, city, user or device", "/Admin"),
            new("Sayfayı kapatma kral, görseller / demo program / güncelleme paketi güvenli şekilde yükleniyor.", "Closing the page is loaded securely in the king, visuals / demo program / update package.", "/Admin"),
            new("Sayfayı kapatma kral, görseller ve demo program güvenli şekilde yükleniyor.", "Closing the page is loaded securely in the king, visuals and demo program.", "/Admin"),
            new("Servis Kataloğu", "Service Catalog", "/Admin"),
            new("Seçilen hedef gruptaki aktif müşteri hesaplarına gönderilir.", "The selected target group is sent to active customer accounts.", "/Admin"),
            new("Seçili Dönem", "Selected Period", "/Admin"),
            new("Seçili filtreye uyan lisans kontrol logları silinecek. Filtre yoksa tüm kontrol logları silinir. Emin misiniz?", "License control logs that match the selected filter will be deleted. If there is no filters, all control logs are deleted. Are you sure?", "/Admin"),
            new("Seçili filtreye uygun kurulum bulunamadı.", "No installation is available for selected filter.", "/Admin"),
            new("Seçili tarih aralığı", "Selected date range", "/Admin"),
            new("Seçili ürün ve üyeye gerçek lisans anahtarı oluşturun.", "Create real license key to selected products and members.", "/Admin"),
            new("SignalR canlı destek", "SignalR live support", "/Admin"),
            new("Sil", "Delete", "/Admin"),
            new("Sipariş Id", "Order Id", "/Admin"),
            new("Sipariş Listesi", "Order List", "/Admin"),
            new("Sipariş Yönetimi", "Order Management", "/Admin"),
            new("Sipariş tutarı", "Order amount", "/Admin"),
            new("Sipariş veren üyeler", "Order members", "/Admin"),
            new("Siparişlere Dön", "Return to orders", "/Admin"),
            new("Siparişleri Gör", "See orders", "/Admin"),
            new("Siparişleri, ödeme durumlarını ve alınan ürünleri hızlıca inceleyin.", "Quickly review orders, payment status and received products.", "/Admin"),
            new("Sitede Aç", "Open the Site", "/Admin"),
            new("Sitede Yüklü Program", "Online Installed Program", "/Admin"),
            new("Sitede görünür olsun", "See the site", "/Admin"),
            new("Siteyi Aç", "Open the Site", "/Admin"),
            new("Slider Düzenle", "Slider Edit", "/Admin"),
            new("Slider Görseli", "Slider Visual", "/Admin"),
            new("Slider Güncelle", "Slider Update", "/Admin"),
            new("Slider Kaydet", "Save Slider", "/Admin"),
            new("Slider Yönetimi", "Slider Management", "/Admin"),
            new("Slider açıklaması", "Slider description", "/Admin"),
            new("Son 12 ayın trafik eğilimi", "Last 12 month's traffic trend Home", "/Admin"),
            new("Son 30 Gün", "Last 30 Days", "/Admin"),
            new("Son 30 gün", "Last 30 days", "/Admin"),
            new("Son 30 günde görülen cihaz", "Last 30 days viewed devices", "/Admin"),
            new("Son 7 Gün", "Last 7 Days", "/Admin"),
            new("Son 7 gün", "Last 7 days", "/Admin"),
            new("Son Giriş", "Last Login", "/Admin"),
            new("Son Gönderimler", "Latest Submissions", "/Admin"),
            new("Son Görülme", "Last Seen", "/Admin"),
            new("Son Kullanım", "Latest Use", "/Admin"),
            new("Son Lisans Kontrolleri", "Recent License Controls", "/Admin"),
            new("Son Siparişler", "Last Orders", "/Admin"),
            new("Sonuç", "Conclusion", "/Admin"),
            new("Stok", "Stock", "/Admin"),
            new("Stok Adedi", "Stock MOQ", "/Admin"),
            new("Stok Uyarıları", "Stock Alerts", "/Admin"),
            new("Stok uyarısı yok.", "No stock alert.", "/Admin"),
            new("Stoku azalan veya biten ürünler.", "Reduced or ending products in stock.", "/Admin"),
            new("Sunucu toplu mail isteğini tamamlayamadı.", "The server could not complete the bulk mail request.", "/Admin"),
            new("Süre", "Time", "/Admin"),
            new("Süresiz", "Timeless", "/Admin"),
            new("Sürüm", "Version", "/Admin"),
            new("Sıfırla", "Reset", "/Admin"),
            new("Sınırsız Fiyat", "Unlimited Price", "/Admin"),
            new("Sınırsız lisans için boş bırak.", "Leave empty for unlimited licenses.", "/Admin"),
            new("Sıra", "Order", "/Admin"),
            new("Sıra No", "Phone Number", "/Admin"),
            new("Sıra:", "Sort:", "/Admin"),
            new("Tahmini Konumu Bulunan Kayıt", "Estimated Location Found Registration", "/Admin"),
            new("Tahmini Şehir", "Forecast City", "/Admin"),
            new("Tanımlı", "Description", "/Admin"),
            new("Tarayıcı", "Browser", "/Admin"),
            new("Tarayıcılar", "Browsers", "/Admin"),
            new("Tarih", "Date", "/Admin"),
            new("Tarih aralığı", "Date range", "/Admin"),
            new("Tekil Ziyaretçi", "Tekil Visitor", "/Admin"),
            new("Toplam Bayi", "Total Dealer", "/Admin"),
            new("Toplam Demo İndirme", "Total Demo Download", "/Admin"),
            new("Toplam Reklam", "Total Ads", "/Admin"),
            new("Toplam kurulum/lisans kaydı", "Total installation/license registration", "/Admin"),
            new("Toplam sipariş geliri. Ödeme tamamlanan sipariş geliri:", "Total order revenue. Payment completed order income:", "/Admin"),
            new("Toplu Mail Gönder", "Send Mail", "/Admin"),
            new("Toplu mail gönderilsin mi?", "Are you sending a bulk mail?", "/Admin"),
            new("Toplu mail gönderimi başlatılamadı.", "Bulk mail shipping failed to start.", "/Admin"),
            new("Tüm Alanlar", "All Area", "/Admin"),
            new("Tüm Eksikleri Kuyruğa Al", "Get All Missiles", "/Admin"),
            new("Tüm Konuşmaları Sil", "Delete All Talks", "/Admin"),
            new("Tüm Programlar", "All Programs", "/Admin"),
            new("Tüm aktif canlı destek konuşmaları silinsin mi?", "Delete all active live support conversations?", "/Admin"),
            new("Tüm aktif üyeler", "All active members", "/Admin"),
            new("Tüm mesaj kayıtları silinsin mi?", "Delete all message logs?", "/Admin"),
            new("Tüm programlara yayınla", "Stream all programs", "/Admin"),
            new("Tüm toplu mail geçmişi silinsin mi?", "Delete all bulk mail history?", "/Admin"),
            new("Tüm ürünler", "All products", "/Admin"),
            new("Tümünü Sil", "Delete All", "/Admin"),
            new("Türkiye", "Turkey", "/Admin"),
            new("Tıklama", "Click here", "/Admin"),
            new("Tıklama say", "Click", "/Admin"),
            new("Tıklama:", "Click:", "/Admin"),
            new("V2 API anahtarı program tarafından", "V2 API key by program", "/Admin"),
            new("V2 Durum", "V2 Status", "/Admin"),
            new("V2 Lisans / Cihaz Bilgisi", "V2 License / Device Information", "/Admin"),
            new("V2 lisans aktivasyon/kontrol denemeleri.", "V2 license activation/control trials.", "/Admin"),
            new("V2 lisans kontrolünde program kodu.", "Program code in V2 license control.", "/Admin"),
            new("V2 lisans kontrolünde reddedilecek cihazlar.", "Devices to be rejected in V2 license control.", "/Admin"),
            new("Varsayılan", "By default", "/Admin"),
            new("Varsayılan Yap", "Default", "/Admin"),
            new("Veri alınamadı", "Data Not Found", "/Admin"),
            new("Veriler yükleniyor…", "Loading data...", "/Admin"),
            new("Video Düzenle", "Edit Video", "/Admin"),
            new("Video Yönetimi", "Video Management", "/Admin"),
            new("Video dosyası siteye yüklenmez", "Video file does not load to the site", "/Admin"),
            new("Videolara Dön", "Back to Videos", "/Admin"),
            new("Videoyu Düzenle", "Edit Video", "/Admin"),
            new("Videoyu Kaydet", "Save Video", "/Admin"),
            new("Videoyu programa bağlayın", "Connect video to the program", "/Admin"),
            new("WPF programların otomatik güncelleme paketlerini buradan yönetin.", "Manage automated update packages from WPF programs here.", "/Admin"),
            new("WPF tarafındaki productCode ile aynı olmalı.", "The productCode on the WPF side should be the same.", "/Admin"),
            new("Warning", "Warning", "/Admin"),
            new("Yalnızca e-posta adresin bu cihazda güvenli biçimde saklanır.", "Only the email address is stored securely on this device.", "/Admin"),
            new("Yalnızca puan verdi.", "Only scored.", "/Admin"),
            new("Yayında", "Published", "/Admin"),
            new("Yayında Değil", "Not Published", "/Admin"),
            new("Yayında olsun", "Subscribe", "/Admin"),
            new("Yayından Kaldır", "Remove from Broadcast", "/Admin"),
            new("Yayınla", "Publish", "/Admin"),
            new("Yazı yönü", "Writing Direction", "/Admin"),
            new("Yeni Banner Görseli", "New Banner Visual", "/Admin"),
            new("Yeni Bayi", "New Dealer", "/Admin"),
            new("Yeni Dil Ekle", "Add New Language", "/Admin"),
            new("Yeni Görsel Ekle", "Add New Visual", "/Admin"),
            new("Yeni Güncelleme Ekle", "Add New Update", "/Admin"),
            new("Yeni Güncelleme Paketi", "New Update Package", "/Admin"),
            new("Yeni Kampanya", "New Campaign", "/Admin"),
            new("Yeni Kupon Oluştur", "Create New Coupon", "/Admin"),
            new("Yeni Lisans", "New License", "/Admin"),
            new("Yeni Mail Gönder", "Send New Mail", "/Admin"),
            new("Yeni Reklam Ekle", "Add New Ads", "/Admin"),
            new("Yeni Sifre (degistirmeyecekseniz bos birakin)", "New Symptom (bos aakin if you are not going to be)", "/Admin"),
            new("Yeni Slider", "New Slider", "/Admin"),
            new("Yeni Slider Görseli", "New Slider Visual", "/Admin"),
            new("Yeni Sürüm", "New Version", "/Admin"),
            new("Yeni Versiyon", "New Version", "/Admin"),
            new("Yeni Video Ekle", "Add New Video", "/Admin"),
            new("Yeni Yayın", "New Release", "/Admin"),
            new("Yeni YouTube Videosu", "New YouTube Videos", "/Admin"),
            new("Yeni bir ziyaretçi siteyi açtığında burada otomatik olarak görünecek.", "When opening a new visitor site, it will automatically appear here.", "/Admin"),
            new("Yeni dil eklenince tüm mevcut site, ürün, uzun açıklama, kategori, video, reklam ve dinamik içerikler otomatik kuyruğa alınır.", "All available sites, products, long description, category, video, advertising and dynamic content are automatically collected.", "/Admin"),
            new("Yeni görsel eklersen listeye eklenir ve ilk yeni görsel ana görsel olur. Toplam 10 görsel sınırı uygulanır.", "If you add new visuals, the list is added and the first new visual becomes the main visual. Total 10 visual limits apply.", "/Admin"),
            new("Yeni görsel seçmezsen mevcut slider görseli korunur.", "The current slider visual is protected if you do not choose new visual.", "/Admin"),
            new("Yeni kategori ekle", "Add new category", "/Admin"),
            new("Yeni konuşma", "New conversation", "/Admin"),
            new("Yeni lisans hareketleri.", "New license movements.", "/Admin"),
            new("Yeni ziyaretler geldikçe burada görünecek.", "New visits will appear here as they came.", "/Admin"),
            new("Yeni Ürün", "New Product", "/Admin"),
            new("Yeni Ürün Ekle", "New Product Add", "/Admin"),
            new("Yeni üyeye özel indirim", "Special download for new members m", "/Admin"),
            new("Yerel test / localhost — gerçek şehir için public IP gerekir", "Local test / localhost — public IP required for real city", "/Admin"),
            new("Yorum Onayları", "Comment Approvals", "/Admin"),
            new("Yorum Yönetimi", "Comment Management", "/Admin"),
            new("Yorum bulunamadı", "No comments found", "/Admin"),
            new("YouTube bağlantısını seçtiğiniz programa bağlayın. Program adı, açıklaması ve işlem butonları site tarafında otomatik kullanılır.", "Connect YouTube link to the program you select. Program name, description and operation buttons are used automatically on site side.", "/Admin"),
            new("YouTube kapağı", "YouTube cover", "/Admin"),
            new("YouTube video kapağı", "YouTube video cover", "/Admin"),
            new("YouTube watch, youtu.be, Shorts, Live ve embed bağlantıları desteklenir.", "YouTube watch, youtu. be, Shorts, Live and embed connections are supported.", "/Admin"),
            new("Yön", "Directions", "/Admin"),
            new("Yönetim merkezi", "Management center", "/Admin"),
            new("Yükleme tamamlanamadı. Sunucu hata kodu:", "Not complete installation. Server error code:", "/Admin"),
            new("Yükleme tamamlandı. Sayfa yenileniyor...", "Installation is completed. Page renew...", "/Admin"),
            new("Yükseklik", "Height", "/Admin"),
            new("Yüzde", "Face", "/Admin"),
            new("Yüzde (%)", "Percentage (%)", "/Admin"),
            new("Yüzde veya sabit indirimli kuponlar oluştur, kullanım limiti ve tarih aralığı belirle.", "Create hundreds or fixed discount coupons, use limit and date range.", "/Admin"),
            new("Yıllık Fiyat", "Annual Price", "/Admin"),
            new("ZIP içine sadece programın güncellenecek exe/dll dosyalarını koy. Firma, kayıt, database ve kullanıcı dosyalarını koyma.", "Put exe/dll files to be updated only in ZIP. Put company, registration, database and user files.", "/Admin"),
            new("Zaman Dışı", "Timeless", "/Admin"),
            new("Ziyaretçi", "Visitor", "/Admin"),
            new("Ziyaretçi Başına Sayfa", "Page Per Visitors", "/Admin"),
            new("Ziyaretçi İstatistikleri", "Visitor Statistics", "/Admin"),
            new("Ziyaretçi, tarayıcısı açıkken düzenli sinyal gönderir. Yaklaşık 90 saniye sinyal gelmeyen ziyaretçi çevrim dışı kabul edilir. Canlı durum ortak veritabanında tutulduğu için Plesk yeniden başlatmalarında ve birden fazla sunucu işleminde kesintisiz izlenir.", "The visitor sends regular signals when the browser is open. The visitor who does not have a signal for about 90 seconds is considered online. Since the live status is kept in the common database, Plesk is continuously monitored in reboots and multiple server operations.", "/Admin"),
            new("Zorunlu güncelleme", "Required update", "/Admin"),
            new("aktif", "active", "/Admin"),
            new("aktif / kayıtlı", "active / registered", "/Admin"),
            new("alanında seçili olan yöntem kullanılır ve tutar satış kaydına sabitlenir.", "The method selected in the field is used and the amount is fixed to the sales record.", "/Admin"),
            new("appsettings.json içine LicenseApi:ApiKey eklenebilir", "LicenseApi into appsettings.json:ApiKey can be added", "/Admin"),
            new("dosya", "File", "/Admin"),
            new("durumunda oluşturulur. Bu nedenle anasayfa kazanç alanlarına otomatik eklenir.", "created in case. This is why the homepage is automatically added to the earnings areas.", "/Admin"),
            new("ekranından yüklenir.", "Loading from screen.", "/Admin"),
            new("görsel", "visual", "/Admin"),
            new("görüntülenme", "View", "/Admin"),
            new("header ile gönderilmeli.", "sent with header.", "/Admin"),
            new("kayıt", "Registration", "/Admin"),
            new("kayıt • aktif • cihaz bekliyor", "• Active • device waiting", "/Admin"),
            new("mutlaka güçlü ve gizli bir değer olmalı. Varsayılan anahtarla V2 API kabul edilmez.", "must be a strong and hidden value. V2 API with default key is not accepted.", "/Admin"),
            new("müşteri e-postasına bağlı", "based on customer email", "/Admin"),
            new("onaylı", "approved", "/Admin"),
            new("sipariş", "Order", "/Admin"),
            new("stok", "stock", "/Admin"),
            new("toplam kayıt", "total records", "/Admin"),
            new("Çeviri motoru arka planda tamamlar.", "The translation engine completes in the background.", "/Admin"),
            new("Çevirileri Yönet", "Manage Translations", "/Admin"),
            new("Çevriliyor:", "Translated:", "/Admin"),
            new("Çevrim İçi", "Online", "/Admin"),
            new("Çıkış", "Checkout", "/Admin"),
            new("Ön izleme", "Front tracking", "/Admin"),
            new("Ön İzleme", "Front Tracking", "/Admin"),
            new("Öncelik", "Priority", "/Admin"),
            new("Öncelik: / Sıra:", "Priority: / Sort:", "/Admin"),
            new("Öne Çıkan", "Featured", "/Admin"),
            new("Önerilen banner: 728 x 90 px. Maksimum 5 MB. PNG, JPG veya WEBP tavsiye edilir.", "Recommended banner: 728 x 90 px. Maximum 5 MB. PNG, JPG or WEBP is recommended.", "/Admin"),
            new("Önerilen yapı:", "Recommended structure:", "/Admin"),
            new("Örn: 1000 TL üzeri %10 indirim", "Example: 10% discount over 1,000 TL", "/Admin"),
            new("Örn: 500 TL üzeri %10 indirim", "Example: 10% discount over 500 TL", "/Admin"),
            new("Örn: Bahar Kampanyası", "Example: Spring Campaign", "/Admin"),
            new("Örn: NSX Teknik Servis", "Example: NSX Technical Service", "/Admin"),
            new("Örn: NSX Turbo yeni sürüm duyurusu", "Example: NSX Turbo new version announcement", "/Admin"),
            new("Örn: NSX Veresiye Takip", "Example: NSX Credit Tracking", "/Admin"),
            new("Örn: NSX30", "Example: NSX30", "/Admin"),
            new("Örn: NSX30 kodu ile indirim", "Example: Discount with code NSX30", "/Admin"),
            new("Örn: NSXKOMISYONLUCARITAKIPPRO", "Example: NSXKOMISYONLUCARITAKIPPRO", "/Admin"),
            new("Örn: NSXVERESIYEDEFTERI", "Example: NSXVERESIYEDEFTERI", "/Admin"),
            new("Örn: OTO500", "Example: OTO500", "/Admin"),
            new("Örn: Performans iyileştirmeleri ve küçük hata düzeltmeleri.", "Example: Performance improvements and minor bug fixes.", "/Admin"),
            new("Örn: Restoran Yönetimi", "Example: Restaurant Management", "/Admin"),
            new("Örnek: 1.0.2", "Example: 1.0. 2", "/Admin"),
            new("Örnek: 2499.90", "Example: 2499. 9090", "/Admin"),
            new("Örnek: 999.90", "Example: 999. 9090", "/Admin"),
            new("Örnek: Performans iyileştirmeleri ve küçük hata düzeltmeleri.", "Example: Performance improvements and small bug fixes.", "/Admin"),
            new("Ücretsiz programların alt banner reklamlarını, geçiş süresini ve tıklama linklerini buradan yönetin.", "Manage sub banner ads, transition time and click links from here for free programs.", "/Admin"),
            new("Ülke", "Country", "/Admin"),
            new("Ürün Adı", "Product Name", "/Admin"),
            new("Ürün Durumu", "Product Condition  u", "/Admin"),
            new("Ürün Düzenle", "Product Layout", "/Admin"),
            new("Ürün Ekle / Güncelle", "Product Add / Update", "/Admin"),
            new("Ürün Görselleri", "Product Visuals", "/Admin"),
            new("Ürün Kategorileri", "Product Categories", "/Admin"),
            new("Ürün Kodu", "Product Code", "/Admin"),
            new("Ürün Kodu / ProductCode", "Product Code / ProductCode", "/Admin"),
            new("Ürün Sayısı", "Product Number", "/Admin"),
            new("Ürün Yönetimi", "Product Management", "/Admin"),
            new("Ürün aktif", "Product active", "/Admin"),
            new("Ürün bilgileri, stok, görseller ve demo dosyası.", "Product information, stock, images and demo file.", "/Admin"),
            new("Ürün bilgisi yok", "No product information", "/Admin"),
            new("Ürün ekle, düzenle, stok ve dosyaları yönet.", "Add products, edit, manage inventory and files.", "/Admin"),
            new("Ürün seç", "Select product", "/Admin"),
            new("Ürün seçersen başlık/link boş bırakıldığında ürün bilgileri otomatik kullanılır. Özel slider istiyorsan ürün seçmeden başlık, link ve görsel gir.", "The product information is used automatically when the header/link is empty. If you want to slide special, enter header, link and visual without selecting the product.", "/Admin"),
            new("Ürün ve müşteri seçimi", "Product and customer selection", "/Admin"),
            new("Ürün yorumlarını onayla, pasife al veya sil.", "Confirm product comments, passive or delete.", "/Admin"),
            new("Ürün, müşteri, ücret ve lisans ayarını seçin. Kayıt anasayfa kazancına otomatik yansır.", "Select product, customer, fee and license setting. The registration is reflected automatically to the home page gain.", "/Admin"),
            new("Ürün, stok, sipariş, lisans, yorum ve toplu mail yönetimini tek merkezden kontrol et.", "Check product, stock, order, license, comment and bulk mail management from one center.", "/Admin"),
            new("Ürün, üye, süre ve makine eşleşmesini yönetin.", "Manage product, member, time and machine match.", "/Admin"),
            new("Ürünlere Dön", "Back to Products", "/Admin"),
            new("Ürünlere Git", "Go to Products", "/Admin"),
            new("Ürünlere yorum geldikçe burada listelenecek.", "The products will be listed here as comments come.", "/Admin"),
            new("Ürünü Aç", "Open Product", "/Admin"),
            new("Ürünü Kaydet", "Save Product", "/Admin"),
            new("Üye", "Member", "/Admin"),
            new("Üye / Müşteri", "Member / Customer", "/Admin"),
            new("Üye Adı", "Member Name", "/Admin"),
            new("Üye Listesi", "Member List", "/Admin"),
            new("Üye Yönetimi", "Member Management", "/Admin"),
            new("Üye bilgisi yok", "No membership information", "/Admin"),
            new("Üye hesaplarını, rol, aktiflik ve IP tahmini konum bilgilerini tek ekrandan kontrol edin.", "Check member accounts, role, active and IP forecast location information from one screen.", "/Admin"),
            new("Üye seç", "Select Member", "/Admin"),
            new("Üyeler", "Members", "/Admin"),
            new("çevirisi", "Translation", "/Admin"),
            new("ödeme/sipariş", "payment/order", "/Admin"),
            new("İl", "Province", "/Admin"),
            new("İl seçin", "Select City", "/Admin"),
            new("İlk Aktivasyon", "First Activation", "/Admin"),
            new("İlk Giriş", "First Entry", "/Admin"),
            new("İlk Videoyu Ekle", "Add First Video", "/Admin"),
            new("İlk YouTube videonuzu bir programa bağlayarak video merkezini oluşturmaya başlayın.", "Start creating video center by connecting your first YouTube video to a program.", "/Admin"),
            new("İlçe", "District", "/Admin"),
            new("İndirim", "Discount", "/Admin"),
            new("İndirim Değeri", "Discount Value", "/Admin"),
            new("İndirim Tipi", "Discount Type", "/Admin"),
            new("İngilizce Ad", "English Name", "/Admin"),
            new("İngilizce ad", "English Name", "/Admin"),
            new("İptal", "Cancel", "/Admin"),
            new("İptal / Askı Açıklaması", "Cancellation / Hanger Description", "/Admin"),
            new("İptal Et", "Cancel", "/Admin"),
            new("İpuçları", "Tips", "/Admin"),
            new("İstatistik", "Statistics", "/Admin"),
            new("İstatistik Sıfırlama", "Statistical Reset", "/Admin"),
            new("İstatistikler bu güncellemeden sonraki ziyaretleri toplamaya başlar. Arama motoru botları, API çağrıları, admin paneli ve bulut uygulama sayfaları sayılmaz.", "Statistics begin to collect subsequent visits from this update. Search engine bots, API calls, admin panel and cloud application pages are not counted.", "/Admin"),
            new("İstatistikleri Sıfırla", "Reset Statistics", "/Admin"),
            new("İsteğe bağlıdır. Boşsa başlık seçilen programdan oluşturulur.", "Optional. The empty header is created from the selected program.", "/Admin"),
            new("İtalik", "Italic", "/Admin"),
            new("İşlem", "Action", "/Admin"),
            new("Şehir bilgisi alınamadı", "City information could not be received", "/Admin"),
            new("Şifren hiçbir zaman kaydedilmez. Hatırlanan e-postayı değiştirerek farklı bir admin hesabıyla da giriş yapabilirsin.", "No time is saved. You can also log in with a different admin account by changing the forgotten email.", "/Admin"),
            new("Şimdi", "Now", "/Admin"),
            new("Şimdi Yenile", "Register Now", "/Admin"),
            new("Şu an çevrim içi", "Online", "/Admin"),
            new("Şu anda aktif ziyaretçi yok", "No active visitors currently", "/Admin"),
            new("Şüpheli Kullanımlar", "Surely Uses", "/Admin"),
            new("💰 Siparişlerden Elde Edilen Kazanç", "Earnings From Orders", "/Admin"),
        };
    }
}
