namespace NSYazilim.Web.Services
{
    /// <summary>
    /// Extended reviewed English coverage for customer-facing pages.
    /// </summary>
    public static class LocalizationEnglishExtendedSeedData
    {
        private static LocalizationSeedItem E(string source, string english, string area)
            => new(source, english, area);

        public static readonly IReadOnlyList<LocalizationSeedItem> Items = new LocalizationSeedItem[]
        {
            E("1. Veri sorumlusu", "1. Data controller", "/Home/Kvkk"),
            E("kanallara iletebilirsiniz.", "channels.", "/Home/Kvkk"),
            E("E-posta adresiniz", "Your email address", "/Home/Contact"),
            E("ornek@firma.com", "example@company.com", "/Home/Contact"),
            // Error / 404
            E("Destek erişimi", "Support access", "/Home/Error"),
            E("Devam etmek için hızlı seçenekler.", "Quick options to continue.", "/Home/Error"),
            E("Geçici bir sistem sorunu oluşmuş olabilir. Ana sayfaya dönün, işlemi yeniden deneyin veya devam eden bir sorun varsa destek ekibimize ulaşın.", "A temporary system issue may have occurred. Return to the home page, try the action again, or contact our support team if the issue continues.", "/Home/Error"),
            E("Güvenli geri dönüş", "Safe return", "/Home/Error"),
            E("Hata sayfası seçenekleri", "Error page options", "/Home/Error"),
            E("SİSTEM BİLDİRİMİ", "SYSTEM NOTICE", "/Home/Error"),
            E("Takip kodu:", "Tracking code:", "/Home/Error"),
            E("YARDIM MERKEZİ", "HELP CENTER", "/Home/Error"),
            E("oluştu.", "occurred.", "/Home/Error"),
            E("İşlem takibi", "Process tracking", "/Home/Error"),
            E("İşlemi güvenli biçimde yeniden deneyebilirsiniz.", "You can safely try the action again.", "/Home/Error"),
            E("İşleminiz tamamlanamadı. Birkaç dakika sonra tekrar deneyebilir veya destek ekibimize ulaşabilirsiniz.", "Your request could not be completed. Please try again in a few minutes or contact our support team.", "/Home/Error"),
            E("İşleminizi güvenli biçimde sürdürmek için aşağıdaki bölümleri kullanabilirsiniz.", "Use the sections below to continue safely.", "/Home/Error"),

            // About
            E("Bir yazılımın yalnızca çok özellikli olması yetmez. Ekranların anlaşılır, işlemlerin hızlı ve temel iş akışlarının kolay öğrenilebilir olması gerektiğine inanıyoruz.", "Software should offer more than a long feature list. We believe screens should be clear, actions should be fast, and core workflows should be easy to learn.", "/Home/About"),
            E("Gerçek iş ihtiyaçlarına odaklanıyoruz", "We focus on real business needs", "/Home/About"),
            E("Günlük iş süreçlerini sadeleştiren, kurulumu ve kullanımı kolay Windows yazılımları geliştiriyoruz.", "We develop Windows software that simplifies daily business processes and is easy to install and use.", "/Home/About"),
            E("Her ürün gerçek kullanım senaryolarına göre şekillenir.", "Every product is shaped around real-world use cases.", "/Home/About"),
            E("Kurulum, lisanslama ve kullanım sorularında destek kanallarımız üzerinden yardımcı oluyor; ürün videoları ve rehberlerle kullanıcılarımızın doğru bilgiye kolayca ulaşmasını sağlıyoruz.", "We assist with installation, licensing and usage questions through our support channels, while product videos and guides help users reach the right information quickly.", "/Home/About"),
            E("NSX YAZILIM", "NSX SOFTWARE", "/Home/About"),
            E("NSX Yazılım yaklaşımı", "The NSX Software approach", "/Home/About"),
            E("NSX Yazılım; veresiye ve cari takipten teknik servise, oto tamir ve galeri yönetiminden klinik, randevu ve düğün salonu süreçlerine kadar farklı sektörlerin günlük çalışma düzenine uygun çözümler sunar.", "NSX Software provides solutions designed for the day-to-day workflows of different industries, from receivables and account tracking to technical service, auto repair and dealership management, clinics, appointments and wedding venues.", "/Home/About"),
            E("Sade kullanım, net sonuç", "Simple to use, clear results", "/Home/About"),
            E("Satış sonrasında da yanınızdayız", "We stay with you after the sale", "/Home/About"),
            E("Sorularınız için iletişim kanallarımız her zaman görünürdür.", "Our contact channels are always easy to find when you have questions.", "/Home/About"),
            E("Ulaşılabilir destek", "Accessible support", "/Home/About"),
            E("güçlü yazılım çözümleri.", "powerful software solutions.", "/Home/About"),
            E("Ürün, lisans ve destek bilgileri açık biçimde sunulur.", "Product, licensing and support information is presented clearly.", "/Home/About"),
            E("İşletme odaklı", "Business-focused", "/Home/About"),
            E("İşletmeler için anlaşılır,", "Clear for businesses,", "/Home/About"),

            // Returns
            E("14 gün başvuru", "14-day request period", "/Home/Returns"),
            E("2. İade edilebilir siparişler", "2. Orders eligible for return", "/Home/Returns"),
            E("3. İade kapsamı dışındaki durumlar", "3. Cases excluded from returns", "/Home/Returns"),
            E("5. Başvuru adımları", "5. Request steps", "/Home/Returns"),
            E("6. Değerlendirme ve ödeme", "6. Review and refund", "/Home/Returns"),
            E("7. İletişim", "7. Contact", "/Home/Returns"),
            E("Başvurunuz lisans ve sipariş kayıtları kontrol edilerek değerlendirilir. Onaylanan iadeler, teknik ve bankacılık süreçlerine bağlı olarak mümkün olan en kısa sürede ödeme yapılan kanala yönlendirilir.", "Your request is reviewed against license and order records. Approved refunds are returned through the original payment channel as soon as possible, subject to technical and banking processing times.", "/Home/Returns"),
            E("Bu politika, NSX Yazılım internet sitesi üzerinden satın alınan dijital yazılım, lisans anahtarı ve bunlarla bağlantılı dijital teslimatlar için geçerlidir.", "This policy applies to digital software, license keys and related digital deliveries purchased through the NSX Software website.", "/Home/Returns"),
            E("Dijital ürün ve lisans siparişlerindeki iade koşullarını, başvuru adımlarını ve değerlendirme sürecini açıklıyoruz.", "We explain the return conditions, request steps and review process for digital products and license orders.", "/Home/Returns"),
            E("Etkinleştirilmiş veya kullanılmış lisanslar, kullanıcıya özel hazırlanmış çözümler, teslimi ve kullanımı başlamış dijital hizmetler ile kötüye kullanım şüphesi bulunan talepler iade kapsamı dışında değerlendirilebilir.", "Activated or used licenses, custom solutions prepared for a specific user, digital services whose delivery or use has begun, and requests involving suspected misuse may be excluded from the return policy.", "/Home/Returns"),
            E("Kullanılmamış ve etkinleştirilmemiş dijital lisanslar için teslim tarihinden itibaren 14 gün içinde iade talebi oluşturabilirsiniz. Talep, ürünün ve lisansın durumuna göre değerlendirilir.", "For unused and unactivated digital licenses, you may submit a return request within 14 days of delivery. Requests are evaluated according to the status of the product and license.", "/Home/Returns"),
            E("Kısa özet", "Quick summary", "/Home/Returns"),
            E("Lisansın etkinleştirilmemiş, ürünün kullanılmamış ve talebin teslim tarihinden itibaren 14 gün içinde iletilmiş olması hâlinde iade başvurusu değerlendirilebilir.", "A return request may be considered if the license has not been activated, the product has not been used, and the request is submitted within 14 days of delivery.", "/Home/Returns"),
            E("Politikası", "Policy", "/Home/Returns"),
            E("SATIŞ SONRASI SÜREÇ", "AFTER-SALES PROCESS", "/Home/Returns"),
            E("Siparişte kullandığınız e-posta adresini ve sipariş bilginizi belirtin.", "Provide the email address used for the order and your order details.", "/Home/Returns"),
            E("iletişim kanallarımıza", "our contact channels", "/Home/Returns"),
            E("Ürünle ilgili teknik bir sorun yaşandığında öncelikle destek ekibimiz çözüm sunar. Sorunun giderilememesi ve ürünün vaat edilen temel işlevleri yerine getirmemesi durumunda talep ayrıca incelenir.", "If you experience a technical issue with a product, our support team will first work to resolve it. If the issue cannot be resolved and the product does not perform its promised core functions, the request will be reviewed separately.", "/Home/Returns"),
            E("İade", "Returns", "/Home/Returns"),
            E("İade etmek istediğiniz ürünü ve talep nedeninizi açıklayın.", "Specify the product you want to return and explain the reason for your request.", "/Home/Returns"),
            E("İade politikası başlıkları", "Return policy sections", "/Home/Returns"),
            E("İade süreciyle ilgili sorularınız için destek ekibimize ulaşabilirsiniz. Başvurunuzda sipariş bilgilerini eksiksiz paylaşmanız değerlendirme süresini kısaltır.", "Contact our support team with questions about the return process. Providing complete order information with your request helps shorten the review time.", "/Home/Returns"),
            E("Şeffaf süreç", "Transparent process", "/Home/Returns"),

            // Contact
            E("Daha Hızlı Çözüm", "Faster Resolution", "/Home/Contact"),
            E("Destek Talebi", "Support Request", "/Home/Contact"),
            E("Destek kanalı aktif", "Support channel active", "/Home/Contact"),
            E("Destek talebinizi hazırlayın.", "Prepare your support request.", "/Home/Contact"),
            E("Doğru çözüme", "The right solution", "/Home/Contact"),
            E("Hızlı destek alın", "Get fast support", "/Home/Contact"),
            E("Hızlı sorular için telefon veya WhatsApp, ayrıntılı destek talepleri için mesaj formunu kullanabilirsiniz.", "Use phone or WhatsApp for quick questions, and the message form for detailed support requests.", "/Home/Contact"),
            E("Hızlı İletişim", "Quick Contact", "/Home/Contact"),
            E("Karşılaştığınız durum ve hata mesajı", "What happened and the error message you received", "/Home/Contact"),
            E("Kullandığınız NSX ürününün adı", "Name of the NSX product you use", "/Home/Contact"),
            E("Lisans ve kurulum", "Licensing and installation", "/Home/Contact"),
            E("Mesajı gönder", "Send message", "/Home/Contact"),
            E("Mesajınız", "Your message", "/Home/Contact"),
            E("Mesajınızı doğrudan iletin, destek ekibimiz talebinizi incelemeye başlasın.", "Send your message directly so our support team can begin reviewing your request.", "/Home/Contact"),
            E("NSX Destek Merkezi", "NSX Support Center", "/Home/Contact"),
            E("NSX destek alanları", "NSX support areas", "/Home/Contact"),
            E("Satış, ürün seçimi ve teknik destek için doğrudan iletişim.", "Direct contact for sales, product selection and technical support.", "/Home/Contact"),
            E("Sipariş, lisans ve ayrıntılı teknik destek taleplerinizi e-posta ile paylaşın.", "Send order, license and detailed technical support requests by email.", "/Home/Contact"),
            E("Size dönüş yapabilmemiz için e-posta adresinizi ve ihtiyacınızı mümkün olduğunca açık şekilde yazın.", "Enter your email address and describe what you need as clearly as possible so we can get back to you.", "/Home/Contact"),
            E("Size en uygun destek kanalını seçin.", "Choose the support channel that suits you best.", "/Home/Contact"),
            E("Sık Sorulan Sorular", "Frequently Asked Questions", "/Home/Contact"),
            E("Talebinizde aşağıdaki bilgilerin bulunması sorunun daha hızlı anlaşılmasına yardımcı olur.", "Including the following information in your request helps us understand the issue faster.", "/Home/Contact"),
            E("Talebinizi bize anlatın", "Tell us what you need", "/Home/Contact"),
            E("Varsa sipariş veya lisans bilginiz", "Your order or license information, if available", "/Home/Contact"),
            E("WhatsApp Destek", "WhatsApp Support", "/Home/Contact"),
            E("birlikte ulaşalım.", "together.", "/Home/Contact"),
            E("Ürün seçimi, satın alma, kurulum, lisans ve kullanım sorularınız için ihtiyacınıza en uygun destek kanalından bize ulaşın.", "Contact us through the support channel that best fits your needs for product selection, purchasing, installation, licensing and usage questions.", "/Home/Contact"),
            E("Ürün ve satış desteği", "Product and sales support", "/Home/Contact"),
            E("İlgilendiğiniz ürünü veya destek talebinizi kısaca yazın.", "Briefly describe the product you are interested in or your support request.", "/Home/Contact"),
            E("Telefon veya e-posta ile bize ulaşabilir, uzaktan teknik destek için ücretsiz yardım programını doğrudan indirebilirsiniz.", "You can reach us by phone or email, and download the free remote assistance program for remote technical support.", "/Home/Contact"),
            E("TELEFON", "PHONE", "/Home/Contact"),
            E("E-POSTA", "EMAIL", "/Home/Contact"),
            E("Hızlı Yanıt", "Fast Response", "/Home/Contact"),
            E("Uzman Ekip", "Expert Team", "/Home/Contact"),
            E("Güvenilir", "Reliable", "/Home/Contact"),
            E("Mesai saatlerinde", "During business hours", "/Home/Contact"),
            E("anında destek", "instant support", "/Home/Contact"),
            E("Deneyimli", "Experienced", "/Home/Contact"),
            E("teknik kadro", "technical staff", "/Home/Contact"),
            E("Doğrudan", "Direct", "/Home/Contact"),
            E("NSX desteği", "NSX support", "/Home/Contact"),
            E("Hemen Ara", "Call Now", "/Home/Contact"),
            E("0543 462 42 26 numarasını hemen ara", "Call 0543 462 42 26 now", "/Home/Contact"),
            E("Detaylı İletişim", "Detailed Contact", "/Home/Contact"),
            E("En Kısa Sürede", "As Soon As Possible", "/Home/Contact"),
            E("Tüm Talepler", "All Requests", "/Home/Contact"),
            E("Taleplerinizi açık", "Describe your requests clearly", "/Home/Contact"),
            E("şekilde iletin", "and in detail", "/Home/Contact"),
            E("Ekibimiz size", "Our team will", "/Home/Contact"),
            E("dönüş yapar", "get back to you", "/Home/Contact"),
            E("Sipariş, lisans,", "Orders, licensing,", "/Home/Contact"),
            E("E-Posta Gönder", "Send Email", "/Home/Contact"),
            E("destek@nsxyazilim.com adresine e-posta gönder", "Send an email to destek@nsxyazilim.com", "/Home/Contact"),
            E("NSX UZAKTAN DESTEK", "NSX REMOTE SUPPORT", "/Home/Contact"),
            E("Ücretsiz Uzaktan Yardım", "Free Remote Assistance", "/Home/Contact"),
            E("Programını İndir", "Download the Program", "/Home/Contact"),
            E("Ücretsiz Uzaktan Yardım Programını İndir", "Download the Free Remote Assistance Program", "/Home/Contact"),
            E("Kurulum gerektirmeyen NSX Uzaktan Yardım uygulamasını indirip destek ekibimize bağlantı kodunu iletin.", "Download the install-free NSX Remote Assistance app and share the connection code with our support team.", "/Home/Contact"),
            E("Destek programı kısa süre içinde indirilebilir olacak.", "The support program will be available for download shortly.", "/Home/Contact"),
            E("Kurulum gerektirmez", "No installation required", "/Home/Contact"),
            E("Ücretsiz Hemen İndir", "Download Free Now", "/Home/Contact"),
            E("Program hazırlanıyor", "Program is being prepared", "/Home/Contact"),
            E("Ücretsiz uzaktan yardım programını indir", "Download the free remote assistance program", "/Home/Contact"),
            E("Destek programı hazırlanıyor", "Support program is being prepared", "/Home/Contact"),
            E("İletişim ve Destek", "Contact and Support", "/Home/Contact"),
            E("NSX Yazılım satış, ürün seçimi, kurulum, lisans ve teknik destek sorularınız için iletişim kanalları.", "Contact channels for NSX Software sales, product selection, installation, licensing and technical support questions.", "/Home/Contact"),

            // KVKK / data protection
            E("2. İşlenebilecek kişisel veriler", "2. Personal data that may be processed", "/Home/Kvkk"),
            E("3. İşleme amaçları", "3. Purposes of processing", "/Home/Kvkk"),
            E("4. Aktarım", "4. Data transfers", "/Home/Kvkk"),
            E("5. Toplama yöntemi ve hukuki sebep", "5. Collection method and legal basis", "/Home/Kvkk"),
            E("6. Saklama ve güvenlik", "6. Retention and security", "/Home/Kvkk"),
            E("6698 sayılı KVKK", "Turkish Personal Data Protection Law No. 6698", "/Home/Kvkk"),
            E("6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamında NSX Yazılım, internet sitesi ve sunduğu hizmetlerle bağlantılı olarak elde edilen kişisel veriler bakımından veri sorumlusu sıfatıyla hareket eder.", "Under Turkish Personal Data Protection Law No. 6698, NSX Software acts as the data controller for personal data obtained in connection with its website and services.", "/Home/Kvkk"),
            E("7. KVKK kapsamındaki haklarınız", "7. Your rights under data protection law", "/Home/Kvkk"),
            E("8. Başvuru", "8. Requests and applications", "/Home/Kvkk"),
            E("Aydınlatma Metni", "Privacy Notice", "/Home/Kvkk"),
            E("Başvuru hakları", "Data subject rights", "/Home/Kvkk"),
            E("KVKK bilgilendirme başlıkları", "Privacy notice sections", "/Home/Kvkk"),
            E("KVKK'nın 11. maddesi kapsamında verilerinizin işlenip işlenmediğini öğrenme, bilgi talep etme, amacına uygun kullanılıp kullanılmadığını öğrenme, aktarılan tarafları bilme, eksik veya yanlış verilerin düzeltilmesini ve şartları oluştuğunda silinmesini isteme haklarına sahipsiniz.", "Under Article 11 of the Turkish data protection law, you have the right to learn whether your data is processed, request information, learn whether it is used for its intended purpose, know the parties to whom it is transferred, request correction of incomplete or inaccurate data, and request deletion when the legal conditions are met.", "/Home/Kvkk"),
            E("Kimlik ve iletişim bilgileri, hesap ve üyelik bilgileri, sipariş ve ödeme işlem kayıtları, destek talepleri, lisans ve ürün kullanımına ilişkin işlem bilgileri ile site güvenliği için gerekli teknik kayıtlar işlenebilir.", "Identity and contact details, account and membership information, order and payment records, support requests, license and product usage records, and technical records required for website security may be processed.", "/Home/Kvkk"),
            E("Kişisel veriler, işleme amacı ve ilgili yasal saklama süreleri boyunca muhafaza edilir. Yetkisiz erişim, kayıp veya kötüye kullanımı önlemek için makul teknik ve idari tedbirler uygulanır; süresi dolan veriler mevzuata uygun şekilde silinir, yok edilir veya anonim hâle getirilir.", "Personal data is retained for the period required by the processing purpose and applicable legal retention periods. Reasonable technical and administrative measures are applied to prevent unauthorized access, loss or misuse; expired data is deleted, destroyed or anonymized in accordance with applicable law.", "/Home/Kvkk"),
            E("Kişisel veriler, yalnızca hizmetin yürütülmesi veya yasal yükümlülüklerin yerine getirilmesi için gerekli olduğu ölçüde; barındırma, ödeme, e-posta, muhasebe ve yetkili kamu kuruluşları gibi ilgili taraflarla mevzuata uygun biçimde paylaşılabilir.", "Personal data may be shared, only to the extent necessary to provide the service or meet legal obligations, with relevant parties such as hosting, payment, email and accounting providers and authorized public authorities, in accordance with applicable law.", "/Home/Kvkk"),
            E("Kişisel verilerinizin hangi amaçlarla işlendiğini, nasıl korunduğunu ve haklarınızı açık biçimde anlatıyoruz.", "We clearly explain why your personal data is processed, how it is protected and what rights you have.", "/Home/Kvkk"),
            E("Son güncelleme: 17 Temmuz 2026", "Last updated: July 17, 2026", "/Home/Kvkk"),
            E("Taleplerinizi kimliğinizi ve başvuru konusunu açıklayarak", "You may submit your request by stating your identity and the subject of your application through", "/Home/Kvkk"),
            E("Veriler; internet sitesi formları, kullanıcı hesabı, sipariş ve destek süreçleri ile elektronik iletişim kanalları üzerinden otomatik veya kısmen otomatik yöntemlerle toplanabilir. İşleme faaliyeti; sözleşmenin kurulması veya ifası, hukuki yükümlülük, meşru menfaat ve gerektiğinde açık rıza hukuki sebeplerine dayanır.", "Data may be collected automatically or partly automatically through website forms, user accounts, order and support processes, and electronic communication channels. Processing is based on legal grounds such as entering into or performing a contract, legal obligations, legitimate interests and, where required, explicit consent.", "/Home/Kvkk"),
            E("Veriler; üyelik ve sipariş işlemlerini yürütmek, dijital ürün ve lisans teslimini sağlamak, destek taleplerini yanıtlamak, güvenliği sağlamak, hizmet kalitesini geliştirmek ve yasal yükümlülükleri yerine getirmek amacıyla işlenebilir.", "Data may be processed to manage membership and orders, deliver digital products and licenses, answer support requests, maintain security, improve service quality and comply with legal obligations.", "/Home/Kvkk"),
            E("YASAL BİLGİLENDİRME", "LEGAL NOTICE", "/Home/Kvkk"),
            E("iletişim sayfasındaki", "on the contact page", "/Home/Kvkk"),

            // 404
            E("Ana Sayfaya Dön", "Return to Home", "/Home/NotFound"),
            E("Aradığınız içeriğe buradan devam edin.", "Continue to the content you need from here.", "/Home/NotFound"),
            E("Aradığınız sayfaya", "the page you were looking for", "/Home/NotFound"),
            E("Bağlantı artık mevcut olmayabilir. Ana sayfaya dönebilir, yazılım kataloğunu inceleyebilir veya destek ekibimize ulaşabilirsiniz.", "The link may no longer be available. You can return to the home page, browse the software catalog or contact our support team.", "/Home/NotFound"),
            E("Destek Al", "Get Support", "/Home/NotFound"),
            E("En çok kullanılan NSX bölümlerine tek tıkla ulaşabilirsiniz.", "Reach the most-used NSX sections with one click.", "/Home/NotFound"),
            E("Güvenli yönlendirme", "Safe navigation", "/Home/NotFound"),
            E("HIZLI BAĞLANTILAR", "QUICK LINKS", "/Home/NotFound"),
            E("Hızlı erişim", "Quick access", "/Home/NotFound"),
            E("Kaybolmadınız, doğru yere yönlendirelim.", "You're not lost — we'll point you in the right direction.", "/Home/NotFound"),
            E("NSX destek", "NSX support", "/Home/NotFound"),
            E("SAYFA BULUNAMADI", "PAGE NOT FOUND", "/Home/NotFound"),
            E("Sayfa bulunamadı seçenekleri", "Page not found options", "/Home/NotFound"),
            E("Sayfa taşınmış, kaldırılmış veya bağlantı adresi değişmiş olabilir. Doğru bölüme hızlıca devam edebilirsiniz.", "The page may have been moved, removed or its address may have changed. You can quickly continue to the right section.", "/Home/NotFound"),
            E("Yazılımları İncele", "Browse Software", "/Home/NotFound"),
            E("YÖNLENDİRME MERKEZİ", "NAVIGATION CENTER", "/Home/NotFound"),
            E("ulaşamadık.", "could not be reached.", "/Home/NotFound"),

            // Privacy
            E("1. Politikanın kapsamı", "1. Scope of this policy", "/Home/Privacy"),
            E("3. Bilgilerin kullanım amacı", "3. How information is used", "/Home/Privacy"),
            E("4. Çerezler", "4. Cookies", "/Home/Privacy"),
            E("5. Bilgilerin paylaşılması", "5. Sharing of information", "/Home/Privacy"),
            E("6. Güvenlik ve saklama", "6. Security and retention", "/Home/Privacy"),
            E("7. Üçüncü taraf bağlantıları", "7. Third-party links", "/Home/Privacy"),
            E("8. İletişim", "8. Contact", "/Home/Privacy"),
            E("Ad, soyad, e-posta, telefon, fatura ve sipariş bilgileri; hesap, lisans ve destek kayıtları ile IP adresi, tarayıcı, cihaz ve sayfa erişimi gibi teknik bilgiler işlenebilir.", "Your first and last name, email address, phone number, billing and order information; account, license and support records; and technical information such as IP address, browser, device and page access may be processed.", "/Home/Privacy"),
            E("Bilgiler; hesabınızı ve siparişinizi yönetmek, ürün veya lisans teslimini gerçekleştirmek, destek sağlamak, güvenlik kontrollerini yürütmek, hataları gidermek ve yasal yükümlülükleri yerine getirmek için kullanılır.", "Information is used to manage your account and orders, deliver products or licenses, provide support, perform security checks, resolve errors and comply with legal obligations.", "/Home/Privacy"),
            E("Bilgileriniz satılmaz veya kiralanmaz. Hizmetin sunulması için gerekli olduğu ölçüde ödeme, barındırma, e-posta ve muhasebe hizmeti sağlayıcılarıyla ya da yasal zorunluluk hâlinde yetkili mercilerle paylaşılabilir.", "Your information is not sold or rented. It may be shared with payment, hosting, email and accounting service providers only as necessary to provide the service, or with authorized authorities where legally required.", "/Home/Privacy"),
            E("Bu politika, NSX Yazılım internet sitesini ziyaret ettiğinizde, hesap oluşturduğunuzda, sipariş verdiğinizde veya destek talebi ilettiğinizde oluşabilecek bilgi işleme faaliyetlerini açıklar.", "This policy explains the information-processing activities that may occur when you visit the NSX Software website, create an account, place an order or submit a support request.", "/Home/Privacy"),
            E("Gizlilik ilkesi", "Privacy principle", "/Home/Privacy"),
            E("Gizlilik politikası başlıkları", "Privacy policy sections", "/Home/Privacy"),
            E("Gizlilik uygulamalarımız hakkında soru ve talepleriniz için", "For questions or requests about our privacy practices, contact us at", "/Home/Privacy"),
            E("GİZLİLİK VE GÜVEN", "PRIVACY & TRUST", "/Home/Privacy"),
            E("Kişisel bilgileri yetkisiz erişime karşı korumak için uygun teknik ve idari tedbirler uygulanır. Kayıtlar yalnızca kullanım amacı ve yasal yükümlülükler için gerekli süre boyunca saklanır.", "Appropriate technical and administrative measures are applied to protect personal information from unauthorized access. Records are retained only for as long as required for their purpose and legal obligations.", "/Home/Privacy"),
            E("Site işlevlerinin çalışması, oturum güvenliği ve tercihlerin korunması için zorunlu çerezler kullanılabilir. İstatistik veya pazarlama amaçlı ek çerezler kullanıldığında gerekli bilgilendirme ve tercih seçenekleri sunulur.", "Essential cookies may be used to operate website functions, protect session security and remember preferences. If additional cookies are used for analytics or marketing, the required information and preference controls will be provided.", "/Home/Privacy"),
            E("Sitede üçüncü taraf internet sitelerine yönlendiren bağlantılar bulunabilir. Bu sitelerin içerik ve gizlilik uygulamaları kendi sorumluluklarındadır.", "The website may contain links to third-party websites. Their content and privacy practices are the responsibility of those third parties.", "/Home/Privacy"),
            E("Siteyi kullanırken oluşan bilgileri neden işlediğimizi ve gizliliğinizi nasıl koruduğumuzu öğrenin.", "Learn why we process information generated while you use the website and how we protect your privacy.", "/Home/Privacy"),
            E("adresinden bize ulaşabilirsiniz. Kişisel veri haklarınıza ilişkin ayrıntılar için", "You can contact us at this address. For details about your personal data rights, see", "/Home/Privacy"),
            E("Şeffaf kullanım", "Transparent use", "/Home/Privacy"),

            // FAQ
            E("DESTEK MERKEZİ", "SUPPORT CENTER", "/Home/FAQ"),
            E("Destek ekibimize doğrudan ulaşın.", "Contact our support team directly.", "/Home/FAQ"),
            E("Evet. Kurulum ve ilk kullanım sorularınız için telefon, WhatsApp veya e-posta üzerinden destek ekibimize ulaşabilirsiniz.", "Yes. For installation and first-use questions, you can reach our support team by phone, WhatsApp or email.", "/Home/FAQ"),
            E("Kurulum konusunda destek alabilir miyim?", "Can I get help with installation?", "/Home/FAQ"),
            E("Lisans taşıma koşulları ürüne ve lisans türüne göre değişebilir. Mevcut lisans bilgilerinizle destek ekibimize ulaşarak kontrol ettirebilirsiniz.", "License transfer conditions may vary by product and license type. Contact our support team with your current license information to have eligibility checked.", "/Home/FAQ"),
            E("Lisansı başka bir bilgisayara taşıyabilir miyim?", "Can I move my license to another computer?", "/Home/FAQ"),
            E("NSX yazılımları hangi işletim sisteminde çalışır?", "Which operating system does NSX software run on?", "/Home/FAQ"),
            E("Satın aldığım lisans nasıl teslim edilir?", "How is my purchased license delivered?", "/Home/FAQ"),
            E("Satın alma öncesinden kuruluma ve günlük kullanıma kadar en sık karşılaştığımız sorular.", "Answers to the questions we receive most often, from pre-purchase decisions to installation and daily use.", "/Home/FAQ"),
            E("Satın almadan önce ürünü inceleyebilir miyim?", "Can I review a product before purchasing?", "/Home/FAQ"),
            E("Sık sorulan soru konuları", "Frequently asked question topics", "/Home/FAQ"),
            E("Veri saklama biçimi ürüne göre değişebilir. Masaüstü ürünlerindeki yerel veri ve varsa çevrim içi özelliklerle ilgili ayrıntılar ilgili ürün belgelerinde açıklanır.", "Data storage methods may vary by product. Details about local data in desktop products and any online features are explained in the relevant product documentation.", "/Home/FAQ"),
            E("Verilerim nerede saklanır?", "Where is my data stored?", "/Home/FAQ"),
            E("Yanıtı bulamadınız mı?", "Didn't find the answer?", "/Home/FAQ"),
            E("hızlıca yanıtlayalım.", "we'll answer quickly.", "/Home/FAQ"),
            E("Ödeme onayından sonra lisansınız hesabınıza tanımlanır. Hesabınızdaki indirmeler ve lisanslar bölümünden ilgili bilgilere ulaşabilirsiniz.", "After payment approval, your license is assigned to your account. You can access the relevant information from the Downloads and Licenses sections of your account.", "/Home/FAQ"),
            E("Ücretsiz ürünleri nasıl indirebilirim?", "How can I download free products?", "/Home/FAQ"),
            E("Ürün sayfalarındaki açıklamaları, ekran görüntülerini ve varsa tanıtım videolarını inceleyebilirsiniz. Karar veremediğinizde destek ekibimiz ihtiyacınıza uygun ürünü belirlemenize yardımcı olur.", "You can review product descriptions, screenshots and available promotional videos on each product page. If you're unsure, our support team can help you choose the product that fits your needs.", "/Home/FAQ"),
            E("Ürünlerimiz Windows bilgisayarlar için geliştirilir. Ürüne özel sistem gereksinimlerini ilgili ürün sayfasında görebilirsiniz.", "Our products are developed for Windows computers. Product-specific system requirements are listed on the relevant product page.", "/Home/FAQ"),
            E("İade koşullarını iade politikası sayfasından inceleyebilir, talebinizi sipariş ve iletişim bilgilerinizle destek ekibimize iletebilirsiniz.", "Review the return conditions on the Return Policy page and send your request to our support team together with your order and contact information.", "/Home/FAQ"),
            E("İade talebi nasıl oluşturulur?", "How do I submit a return request?", "/Home/FAQ"),
            E("İletişime geçin", "Contact us", "/Home/FAQ"),
            E("İlgili ücretsiz ürün sayfasındaki indirme adımlarını izleyebilirsiniz. Gerekli olduğunda hesap girişi veya kısa bir bilgilendirme formu istenebilir.", "Follow the download steps on the relevant free product page. When required, you may be asked to sign in or complete a short information form.", "/Home/FAQ")
        };
    }
}
