namespace NSYazilim.Web.Services
{
    /// <summary>
    /// English coverage for the public video library and guide/blog pages.
    /// These are reviewed source translations so English never falls back to Turkish
    /// for the site's editorial navigation and fixed explanatory copy.
    /// </summary>
    public static class LocalizationEnglishContentSeedData
    {
        private static LocalizationSeedItem E(string source, string english, string area)
            => new(source, english, area);

        public static readonly IReadOnlyList<LocalizationSeedItem> Items = new LocalizationSeedItem[]
        {
            E("Merak Edilenler", "Frequently Asked", "/Blog/Detail"),
            E("Rehber Bilgisi", "Guide Information", "/Blog/Detail"),
            E("uygulanabilir rehberler.", "practical guides.", "/Blog"),
            E("saha deneyimi", "field experience", "/Blog"),
            E("Blog bilgileri", "Blog information", "/Blog"),
            E("Rehber kategorileri", "Guide categories", "/Blog"),
            E("Dijital", "Digital", "/Videos/Detail"),
            E("Video bulunamadı.", "No videos found.", "/Videos"),
            E("Arama metnini veya filtreyi değiştirin.", "Change the search text or filter.", "/Videos"),
            E("Program Videosu", "Software Video", "/Videos"),
            E("video kapağı", "video cover", "/Videos"),
            E("Videoyu izle", "Watch video", "/Videos"),
            E("Ürünü incele", "View product", "/Videos"),
            E("▶ Videoyu izle", "▶ Watch video", "/Videos"),
            E("Ürünü incele →", "View product →", "/Videos"),
            E("Video servisi yanıt vermedi.", "The video service did not respond.", "/Videos"),
            E("Video listesi alınamadı.", "The video list could not be loaded.", "/Videos"),
            E("Sayfa hazır.", "Page ready.", "/Videos"),
            E("Video listesi şu anda alınamadı. Birkaç saniye sonra tekrar deneyebilirsiniz.", "The video list is temporarily unavailable. Please try again in a few seconds.", "/Videos"),
            // Videos
            E("Bu kurulum videosu temel masaüstü kullanımını gösterir. Güncel programda ayrıca Cloud Bağlantısı üzerinden QR ile mobil erişim, Toplam Borç / Toplam Tahsilat / Açık Bakiye özeti, müşteri arama, cari hareket görüntüleme, borç-tahsilat girişi ve canlı senkronizasyon bulunur.", "This installation video shows the basic desktop workflow. The current version also includes QR-based mobile access through Cloud Connection, Total Debt / Total Collections / Outstanding Balance summaries, customer search, account activity viewing, debt and collection entry, and live synchronization.", "/Videos/Detail"),
            E("Bu program şu anda stokta olmadığı için indirme ve satın alma işlemleri kapalıdır.", "Downloads and purchases are currently unavailable because this software is out of stock.", "/Videos/Detail"),
            E("Diğer İçerikler", "More Content", "/Videos/Detail"),
            E("Güncel v1.0.5 sürüm notu:", "Current v1.0.5 release note:", "/Videos/Detail"),
            E("Program Detayı", "Software Details", "/Videos/Detail"),
            E("Program Detayını Aç", "Open Software Details", "/Videos/Detail"),
            E("Program Hakkında", "About the Software", "/Videos/Detail"),
            E("Video özellikleri", "Video features", "/Videos/Detail"),
            E("NSX program videosu", "NSX software video", "/Videos/Detail"),
            E("Kurulum ve kullanım rehberi", "Installation and usage guide", "/Videos/Detail"),
            E("Hızlı video erişimi", "Quick video access", "/Videos/Detail"),
            E("Tüm ürün özelliklerini incele →", "Explore all product features →", "/Videos/Detail"),
            E("Video YouTube üzerinden oynatılıyor.", "This video is played via YouTube.", "/Videos/Detail"),
            E("Video ile Bağlı Program", "Software Featured in This Video", "/Videos/Detail"),
            E("Videoya geç →", "Go to video →", "/Videos/Detail"),
            E("YouTube'da Aç", "Open on YouTube", "/Videos/Detail"),
            E("İzleyebileceğiniz videolar", "Videos You Can Watch", "/Videos/Detail"),
            E("Şimdi İzleniyor", "Now Playing", "/Videos/Detail"),
            E("Hızlı erişim", "Quick Access", "/Videos"),
            E("Kullanım videoları", "How-to Videos", "/Videos"),
            E("Kurulum, kullanım ve tanıtım videolarıyla NSX yazılımlarının çalışma mantığını kısa ve anlaşılır videolarla inceleyin.", "Discover how NSX software works through clear, concise installation, usage and product introduction videos.", "/Videos"),
            E("NSX Video Kütüphanesi", "NSX Video Library", "/Videos"),
            E("Programları izleyin,", "Watch the software,", "/Videos"),
            E("Tüm Videolar", "All Videos", "/Videos"),
            E("Tümü", "All", "/Videos"),
            E("Video listesi yükleniyor.", "Loading video list.", "/Videos"),
            E("Video sayfası özellikleri", "Video page features", "/Videos"),
            E("Video türleri", "Video types", "/Videos"),
            E("Video veya program adına göre arayın, içerik türüne göre filtreleyin ve ilgili ürün sayfasına tek tıkla geçin.", "Search by video or software name, filter by content type, and open the related product page with one click.", "/Videos"),
            E("Video veya program ara", "Search videos or software", "/Videos"),
            E("Video veya program ara...", "Search videos or software...", "/Videos"),
            E("Videolar hazırlanıyor...", "Preparing videos...", "/Videos"),
            E("yakından keşfedin.", "discover them in detail.", "/Videos"),
            E("Ürün tanıtımları", "Product Introductions", "/Videos"),
            E("İzlemek istediğiniz içeriği seçin.", "Choose the content you want to watch.", "/Videos"),

            // Blog / Guides
            E("Bakkal ve marketler için uygun mu?", "Is it suitable for grocery stores and markets?", "/Blog/Detail"),
            E("Bakkal, market, bayi, esnaf ve müşteri bazlı borç-tahsilat takibi yapan küçük ve orta ölçekli işletmeler için uygundur. Masaüstünde çalışmaya devam ederken gerektiğinde cep telefonundan cari hesaplara erişmek isteyen işletmelere sade bir Bulut ve Mobil kullanım sunar.", "It is suitable for small and medium-sized businesses such as grocery stores, markets, dealers and tradespeople that track customer-based debt and collections. It offers simple Cloud and Mobile access for businesses that want to keep working on desktop while accessing customer accounts from a phone when needed.", "/Blog/Detail"),
            E("Bu konuyla ilgili diğer sayfalar", "Other pages related to this topic", "/Blog/Detail"),
            E("Bu sayfadan direkt indirme işlemine başlayabilir veya ürün detay sayfasına gidebilirsiniz.", "You can start the download directly from this page or open the product details page.", "/Blog/Detail"),
            E("Canlı senkronizasyon, masaüstü ve mobil tarafta yapılan cari değişikliklerin iki tarafta güncel tutulmasına yardımcı olur.", "Live synchronization helps keep account changes made on desktop and mobile up to date on both sides.", "/Blog/Detail"),
            E("Cari hesap telefondan yönetilebilir mi?", "Can customer accounts be managed from a phone?", "/Blog/Detail"),
            E("Detay Sayfasına Git", "Go to Details Page", "/Blog/Detail"),
            E("Evet. Bakkal, market, bayi ve küçük işletmeler müşteri cari hesaplarını masaüstünden ve QR ile bağlanan mobil panelden takip edebilir.", "Yes. Grocery stores, markets, dealers and small businesses can track customer accounts from the desktop application and the QR-connected mobile panel.", "/Blog/Detail"),
            E("Evet. Mobil panelde müşteri aranır; cari hareketleri açılır ve borç veya tahsilat aynı müşteri hesabından kaydedilebilir.", "Yes. You can search for a customer in the mobile panel, open account activity, and record debt or collection transactions under the same customer account.", "/Blog/Detail"),
            E("Evet. Program ücretsiz kullanım için sunulur; güncel v1.0.5 sürümünde masaüstü cari takibe ek olarak Bulut ve Mobil Yönetim özellikleri bulunur.", "Yes. The software is offered free of charge; the current v1.0.5 release includes Cloud and Mobile Management features in addition to desktop account tracking.", "/Blog/Detail"),
            E("Güncelleme", "Update", "/Blog/Detail"),
            E("Hızlı Ürün Erişimi", "Quick Product Access", "/Blog/Detail"),
            E("Kimler için uygundur?", "Who is it for?", "/Blog/Detail"),
            E("Konu Başlıkları", "Topics", "/Blog/Detail"),
            E("Kurulum Videosu + Güncel Sürüm", "Installation Video + Current Version", "/Blog/Detail"),
            E("Masaüstü hızını koruyup mobil tarafta yalnızca günlük ihtiyaçlara odaklanır: toplam borç, toplam tahsilat, açık bakiye, müşteri arama, cari hareketler, borç ve tahsilat. Mevcut veriler korunarak Bulut ve Mobil erişim mevcut programa eklenir.", "It preserves desktop speed while keeping the mobile side focused on everyday needs: total debt, total collections, outstanding balance, customer search, account activity, debt and collections. Cloud and Mobile access is added to the existing software while preserving current data.", "/Blog/Detail"),
            E("Masaüstü ve mobil veriler nasıl güncel kalır?", "How do desktop and mobile data stay in sync?", "/Blog/Detail"),
            E("NSX Veresiye Programı Ürün Sayfası", "NSX Receivables Software Product Page", "/Blog/Detail"),
            E("NSX Veresiye Takip Pro Kurulum ve Kullanım Videosu", "NSX Receivables Tracking Pro Installation and Usage Video", "/Blog/Detail"),
            E("NSX Veresiye Takip Pro ücretsiz mi?", "Is NSX Receivables Tracking Pro free?", "/Blog/Detail"),
            E("NSX Veresiye v1.0.5 yaklaşımı", "NSX Receivables v1.0.5 approach", "/Blog/Detail"),
            E("NSX Yazılım Rehberi", "NSX Software Guide", "/Blog/Detail"),
            E("NSX Yazılım yaklaşımı", "The NSX Software approach", "/Blog/Detail"),
            E("NSX Yazılım; hızlı kullanım, sade arayüz, güvenli dijital teslimat, güncelleme desteği ve destek odaklı çözümler geliştirmeyi hedefler.", "NSX Software focuses on fast workflows, clear interfaces, secure digital delivery, update support and support-oriented software solutions.", "/Blog/Detail"),
            E("Programı Ücretsiz İndir", "Download Software Free", "/Blog/Detail"),
            E("Tüm rehberler", "All guides", "/Blog/Detail"),
            E("Tüm rehberleri görüntüle", "View all guides", "/Blog/Detail"),
            E("Video temel masaüstü akışını anlatır. Yeni Bulut ve Mobil sistemde Cloud Bağlantısı ekranından QR oluşturabilir, telefondan müşteri arayabilir, cari hareketleri görebilir, borç ve tahsilat kaydedebilirsiniz.", "The video explains the basic desktop workflow. With the new Cloud and Mobile system, you can generate a QR code from the Cloud Connection screen, search customers from your phone, view account activity, and record debt and collection transactions.", "/Blog/Detail"),
            E("Videoda masaüstü programının kurulum ve temel kullanım adımlarını izleyebilirsiniz. Güncel v1.0.5 sürümünde bunlara ek olarak QR ile Bulut ve Mobil Yönetim, canlı senkronizasyon, mobil müşteri arama, cari hareket, borç ve tahsilat özellikleri bulunur.", "The video shows the desktop application's installation and basic usage steps. The current v1.0.5 release additionally includes QR-based Cloud and Mobile Management, live synchronization, mobile customer search, account activity, debt and collection features.", "/Blog/Detail"),
            E("Yayın", "Published", "/Blog/Detail"),
            E("Yayıncı", "Publisher", "/Blog/Detail"),
            E("Yazı bilgileri", "Article information", "/Blog/Detail"),
            E("v1.0.5 güncel sürüm notu:", "v1.0.5 current release note:", "/Blog/Detail"),
            E("İletişime Geç", "Contact Us", "/Blog/Detail"),
            E("İlgili Rehberler", "Related Guides", "/Blog/Detail"),
            E("İş süreçlerinizi daha düzenli yönetmenize yardımcı olacak sade ve uygulanabilir bilgiler.", "Clear, practical information to help you manage your business processes more systematically.", "/Blog/Detail"),
            E("İşini daha düzenli takip etmek, lisanslı veya ücretsiz yazılım kullanmak ve süreçlerini dijitalleştirmek isteyen işletmeler için uygundur.", "It is suitable for businesses that want to track their work more systematically, use licensed or free software, and digitize their processes.", "/Blog/Detail"),
            E("Bu sırada NSX yazılımlarını inceleyebilirsiniz.", "In the meantime, you can explore NSX software.", "/Blog"),
            E("Doğru çözümü birlikte seçelim", "Let's choose the right solution together", "/Blog"),
            E("NSX Bilgi Merkezi", "NSX Knowledge Center", "/Blog"),
            E("Okumaya devam et", "Continue reading", "/Blog"),
            E("Rehber arşivi", "Guide archive", "/Blog"),
            E("Rehberi incele", "View guide", "/Blog"),
            E("Tüm Rehberler", "All Guides", "/Blog"),
            E("Tüm yazılımlar", "All software", "/Blog"),
            E("Uzman desteği alın", "Get expert support", "/Blog"),
            E("Yazılım seçimi, günlük operasyonlar ve dijital iş süreçleri için sade, güvenilir ve doğrudan uygulanabilir içerikler.", "Clear, reliable and directly actionable content for software selection, daily operations and digital business processes.", "/Blog"),
            E("Yazılımları keşfet", "Explore Software", "/Blog"),
            E("Yeni rehberler hazırlanıyor.", "New guides are being prepared.", "/Blog"),
            E("güncel rehber", "current guides", "/Blog"),
            E("uzmanlık alanı", "areas of expertise", "/Blog"),
            E("Öne çıkan rehber", "Featured guide", "/Blog"),
            E("İhtiyacınıza göre keşfedin", "Explore by your needs", "/Blog"),
            E("İhtiyacınızı anlatın; size uygun NSX ürününü ve kullanım yolunu birlikte netleştirelim.", "Tell us what you need and we'll help you identify the right NSX product and the best way to use it.", "/Blog"),
            E("İşinizi büyüten", "Built to grow your business", "/Blog"),
            E("İşletmeniz için hangi yazılımın uygun olduğundan emin değil misiniz?", "Not sure which software is right for your business?", "/Blog")
        };
    }
}
