namespace NSYazilim.Web.Services
{
    /// <summary>
    /// Public product display-name translations. Canonical Product.Name/ProductCode/Slug values
    /// remain untouched; these values are only used by the site localization engine at render time.
    /// </summary>
    public static class ProductLocalizationSeedData
    {
        private static readonly Lazy<IReadOnlyDictionary<string, string>> EnglishBySourceKey = new(BuildEnglishBySourceKey);

        private static IReadOnlyDictionary<string, string> BuildEnglishBySourceKey()
        {
            var map = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var item in Items)
            {
                if (string.IsNullOrWhiteSpace(item.Source) || string.IsNullOrWhiteSpace(item.English))
                    continue;

                var key = LocalizationTextKey.Create(item.Source);
                if (!string.IsNullOrWhiteSpace(key))
                    map[key] = LocalizationTextKey.Normalize(item.English);
            }

            return map;
        }

        /// <summary>
        /// Reviewed English for a Turkish product/UI source string. Used as an authoritative
        /// runtime fallback when the DB catalog still holds a leaked Turkish EN row.
        /// </summary>
        public static bool TryResolveEnglish(string? sourceText, out string english)
        {
            english = string.Empty;
            var key = LocalizationTextKey.Create(sourceText);
            if (string.IsNullOrWhiteSpace(key))
                return false;

            if (!EnglishBySourceKey.Value.TryGetValue(key, out var resolved)
                || string.IsNullOrWhiteSpace(resolved))
            {
                return false;
            }

            english = resolved;
            return true;
        }

        public static readonly IReadOnlyList<LocalizationSeedItem> Items = new LocalizationSeedItem[]
        {
            new("NSX Yazılım", "NSX Software", "/Shared/Brand"),

            new("NSX Veri Kurtarma Pro", "NSX Data Recovery Pro", "/Products"),
            new("NSX Veri Kurtarma Pro | HDD, SSD ve USB Dosya Kurtarma", "NSX Data Recovery Pro | HDD, SSD and USB File Recovery", "/Products"),
            new("NSX Veri Kurtarma Pro ile HDD, SSD, USB ve hafıza kartlarında kayıp dosyaları arayın; hızlı ve derin tarama, önizleme ve filtrelemeyle sonuçları inceleyin.", "Search for lost files on HDD, SSD, USB and memory cards with NSX Data Recovery Pro; review results with quick and deep scans, preview and filtering.", "/Products"),

            new("NSX Okul Plan Pro", "NSX School Planner Pro", "/Products"),
            new("NSX Okul Plan Pro | Ders Programı ve Nöbet Planlama", "NSX School Planner Pro | Class Schedules and Duty Planning", "/Products"),
            new("NSX Kasa Defteri Pro", "NSX Cash Book Pro", "/Products"),
            new("NSX Kasa Defteri Pro | Kasa, Döviz ve Cari Takip", "NSX Cash Book Pro | Cash, Currency and Account Tracking", "/Products"),
            new("NSX Sigorta Acente Pro", "NSX Insurance Agency Pro", "/Products"),
            new("NSX Sigorta Acente Pro | Poliçe ve Yenileme Takibi", "NSX Insurance Agency Pro | Policy and Renewal Tracking", "/Products"),
            new("NSX Sigorta Acenta Pro", "NSX Insurance Agency Pro", "/Products"),
            new("NSX Security Auditor Pro", "NSX Security Auditor Pro", "/Products"),
            new("NSX Security Auditor Pro | AI Kod Güvenlik Analizi", "NSX Security Auditor Pro | AI Code Security Analysis", "/Products"),
            new("NSX Security Auditor", "NSX Security Auditor", "/Products"),

            new("NSX Barkodlu Satış, Cari ve Stok Takibi", "NSX Barcode Sales, Accounts & Inventory Pro", "/Products"),
            new("NSX Barkodlu Satış Cari Stok Takip", "NSX Barcode Sales, Accounts & Inventory Pro", "/Products"),
            new("NSX Barkodlu Satış Pro", "NSX Barcode Sales Pro", "/Products"),
            new("NSX Barkodlu Satış Pro | Cari, Stok ve Hızlı Satış", "NSX Barcode Sales Pro | Accounts, Inventory and Quick Sales", "/Products"),

            new("NSX Teknik Servis Pro", "NSX Technical Service Pro", "/Products"),
            new("NSX Teknik Servis Pro | Cihaz ve Servis Takip Programı", "NSX Technical Service Pro | Device and Service Tracking Software", "/Products"),
            new("NSX Teknik Servis Takip", "NSX Technical Service Tracking", "/Products"),
            new("NSX Servis Pro", "NSX Service Pro", "/Products"),
            new("NSX Servis Pro Live", "NSX Service Pro Live", "/Products"),
            new("NSX Servis Pro Live | QR Kodlu Canlı Servis Takibi", "NSX Service Pro Live | QR-Coded Live Service Tracking", "/Products"),

            new("NSX Cari Takip Pro", "NSX Account Tracking Pro", "/Products"),
            new("NSX Cari Takip Pro | Borç, Tahsilat ve Cari Hesap", "NSX Account Tracking Pro | Debt, Collections and Customer Accounts", "/Products"),
            new("NSX Cari Takip", "NSX Account Tracking", "/Products"),
            new("NSX Cari Takip Pro Bulut", "NSX Account Tracking Pro Cloud", "/Products"),
            new("NSX Cari Takip Pro Bulut | Çoklu Bilgisayar ve Mobil Cari Takip", "NSX Account Tracking Pro Cloud | Multi-PC and Mobile Account Tracking", "/Products"),
            new("NSX Cari Takip Pro Bulut ile firma ve müşteri carilerini, borç, alacak, tahsilat, ödeme ve raporları bilgisayarlar arasında canlı eşitleyin ve mobil cihazlardan yönetin.", "Live-sync company and customer accounts, debt, credit, collections, payments and reports across computers and manage them from mobile devices with NSX Account Tracking Pro Cloud.", "/Products"),
            new("NSX Komisyonlu Cari Takip Pro", "NSX Commission Account Tracking Pro", "/Products"),
            new("NSX Komisyonlu Cari Takip Pro | Komisyon ve Tahsilat", "NSX Commission Account Tracking Pro | Commission and Collections", "/Products"),
            new("NSX Komisyonlu Cari Takip", "NSX Commission Account Tracking", "/Products"),

            new("NSX Düğün Salonu Pro", "NSX Wedding Venue Pro", "/Products"),
            new("NSX Düğün Salonu Pro | Rezervasyon ve Tahsilat Takibi", "NSX Wedding Venue Pro | Reservation and Collection Tracking", "/Products"),
            new("NSX Salon Takip", "NSX Venue Tracking", "/Products"),

            new("NSX Oto Tamir Servis Pro", "NSX Auto Repair Service Pro", "/Products"),
            new("NSX Oto Tamir Servis Pro | Araç Kabul ve Servis Takibi", "NSX Auto Repair Service Pro | Vehicle Intake and Service Tracking", "/Products"),
            new("NSX Oto Galeri Pro", "NSX Auto Dealership Pro", "/Products"),
            new("NSX Oto Galeri Pro | Araç Stok ve Satış Takip Programı", "NSX Auto Dealership Pro | Vehicle Inventory and Sales Tracking", "/Products"),

            new("NSX Klinik ve Randevu Takip Programı", "NSX Clinic & Appointment Tracking Pro", "/Products"),
            new("NSX Klinik ve Randevu Takip | Hasta ve Doktor Programı", "NSX Clinic & Appointment Tracking | Patient and Doctor Software", "/Products"),
            new("NSX Klinik ve Randevu Takip", "NSX Clinic & Appointment Tracking", "/Products"),

            new("NSX Veresiye Takip Pro Free", "NSX Receivables Tracking Pro Free", "/Products"),
            new("NSX Veresiye Takip Pro Free | Ücretsiz Cari Takip", "NSX Receivables Tracking Pro Free | Free Account Tracking", "/Products"),
            new("NSX Veresiye Takip Pro Free ile cari hesap, borç, tahsilat ve açık bakiye takibini Windows, Bulut ve Mobil üzerinden ömür boyu ücretsiz yönetin.", "Manage customer accounts, debt, collections and outstanding balances for free on Windows, Cloud and Mobile for life with NSX Receivables Tracking Pro Free.", "/Products"),
            new("NSX Veresiye Takip Programı Ücretsiz", "NSX Free Receivables Tracking", "/Products"),
            new("NSX Veresiye Takip Programı", "NSX Receivables Tracking", "/Products"),
            new("NSX Veresiye Takip Pro", "NSX Receivables Tracking Pro", "/Products"),
            new("NSX Veresiye Pro", "NSX Receivables Pro", "/Products"),
            new("NSX Veresiye Free", "NSX Receivables Free", "/Products"),
            new("NSX Ücretsiz Veresiye Pro", "NSX Free Receivables Pro", "/Products"),
            new("NSX Ücretsiz Veresiye Takip", "NSX Free Receivables Tracking", "/Products"),

            new("NSX Turbo Performans Programı", "NSX Turbo Performance Pro", "/Products"),
            new("NSX Turbo Performans Pro", "NSX Turbo Performance Pro", "/Products"),
            new("NSX Turbo | Bilgisayar Hızlandırma ve FPS Artırma", "NSX Turbo | PC Speed-Up and FPS Boost", "/Products"),
            new("NSX Performance Pro", "NSX Performance Pro", "/Products"),
            new("En yeni ürün", "Newest product", "/Products"),
            new("İNDİRİM", "OFF", "/Products"),
            new("Ücretsiz", "Free", "/Products"),
            new("Dijital lisans", "Digital license", "/Products"),
            new("Stokta yok", "Out of stock", "/Products"),
            new("detay sayfasını aç", "open product details", "/Products"),
            new("detaylarını gör", "view details", "/Products"),
            new("ürün görseli", "product image", "/Products"),
            new("İş süreçlerinizi kolayca yönetin.", "Manage your business processes with ease.", "/Products"),
            new("Kolay kullanım", "Easy to use", "/Products"),
            new("Salon planlama", "Venue planning", "/Products"),
            new("Araç geçmişi", "Vehicle history", "/Products"),
            new("Araç stok", "Vehicle inventory", "/Products"),
            new("Kapora takibi", "Deposit tracking", "/Products"),
            new("Kâr-zarar", "Profit and loss", "/Products"),
            new("Hasta monitörü", "Patient monitor", "/Products"),
            new("Kapı üstü sıra", "Door queue display", "/Products"),
            new("Parça ve işçilik", "Parts and labor", "/Products"),
            new("QR canlı takip", "Live QR tracking", "/Products"),
            new("SMS bildirim", "SMS notifications", "/Products"),
            new("Müşteri onayı", "Customer approval", "/Products"),
            new("Servis fişi", "Service receipt", "/Products"),
            new("Müşteri geçmişi", "Customer history", "/Products"),
            new("Teslim takibi", "Delivery tracking", "/Products"),
            new("Cari kartlar", "Account cards", "/Products"),
            new("Tahsilat takibi", "Collection tracking", "/Products"),
            new("Raporlar", "Reports", "/Products"),
            new("Hızlı kullanım", "Fast workflow", "/Products"),
            new("Güvenli işlem", "Secure operations", "/Products"),
            new("Teknik destek", "Technical support", "/Products"),
            new("NSX Yazılım Kütüphanesi", "NSX Software Library", "/store"),
            new("İşinize uygun yazılımı", "Find the right software for your business", "/store"),
            new("kolayca keşfedin.", "discover it with ease.", "/store"),
            new("Cari hesaptan teknik servise, otomotivden klinik ve organizasyona kadar işletmeniz için geliştirilen NSX çözümlerini tek ekranda karşılaştırın.", "Compare NSX solutions for accounts, technical service, automotive, clinics and event businesses on one screen.", "/store"),
            new("NSX yazılım avantajları", "NSX software advantages", "/store"),
            new("Windows uyumlu", "Windows compatible", "/store"),
            new("Kolay kurulum", "Easy installation", "/store"),
            new("Yerli destek", "Local support", "/store"),
            new("İşletme Yazılımları", "Business Software", "/store"),
            new("Profesyonel NSX çözümleri", "Professional NSX solutions", "/store"),
            new("Kullanıma hazır", "Ready to use", "/store"),
            new("Yazılım Kütüphanesi", "Software Library", "/store"),
            new("Ürün", "Product", "/store"),
            new("Tek noktadan keşfet", "Explore in one place", "/store"),
            new("Kurulum", "Installation", "/store"),
            new("Hızlı", "Fast", "/store"),
            new("Yerli", "Local", "/store"),
            new("NSX desteği", "NSX support", "/store"),
            new("Lisans", "License", "/store"),
            new("Güvenli", "Secure", "/store"),
            new("Profesyonel kullanım", "Professional use", "/store"),
            new("İşletmeniz için doğru çözümü seçin.", "Choose the right solution for your business.", "/store"),
            new("Kategoriye göre filtreleyin, ürünleri karşılaştırın ve ihtiyacınıza en uygun NSX yazılımının detaylarını inceleyin.", "Filter by category, compare products and review the NSX software that best fits your needs.", "/store"),
            new("Yazılımlarda ara", "Search software", "/store"),
            new("Önerilen", "Recommended", "/store"),
            new("En yeni", "Newest", "/store"),
            new("Fiyat: düşükten yükseğe", "Price: low to high", "/store"),
            new("Fiyat: yüksekten düşüğe", "Price: high to low", "/store"),
            new("Ara", "Search", "/store"),
            new("Ürün bulunamadı", "No products found", "/store"),
            new("Arama kriterlerinizi değiştirerek tekrar deneyin.", "Try again with different search criteria.", "/store"),
            new("Tüm yazılımları göster", "Show all software", "/store"),
            new("NSX işletme yazılımları", "NSX business software", "/store"),
            new("NSX Yazılımları", "NSX Software", "/store"),
            new("NSX İşletme Yazılımları | Satış, Finans, Servis ve Güvenlik", "NSX Business Software | Sales, Finance, Service & Security", "/store"),
            new("NSX Kasa Defteri, Sigorta Acente ve Security Auditor Pro ile ücretsiz veresiye, barkodlu satış, cari takip, teknik servis, otomotiv ve klinik yazılımlarını inceleyin.", "Explore NSX Cash Book, Insurance Agency and Security Auditor Pro together with free receivables, barcode sales, account tracking, technical service, automotive and clinic software.", "/store"),
            new("NSX güvencesiyle.", "Backed by NSX.", "/Products/Detail"),
            new("Ürün avantajları", "Product advantages", "/Products/Detail"),
            new("Dijital teslimat", "Digital delivery", "/Products/Detail"),
            new("NSX teknik destek", "NSX technical support", "/Products/Detail"),
            new("NSX ORİJİNAL YAZILIM", "GENUINE NSX SOFTWARE", "/Products/Detail"),
            new("Stokta · Dijital teslimat", "In stock · Digital delivery", "/Products/Detail"),
            new("Şu anda stokta yok", "Currently out of stock", "/Products/Detail"),
            new("Büyüt", "Zoom", "/Products/Detail"),
            new("⌕ Büyüt", "⌕ Zoom", "/Products/Detail"),
            new("Ürün görselleri", "Product images", "/Products/Detail"),
            new("Görsele tıklayarak tam boy inceleyin", "Click the image to view full size", "/Products/Detail"),
            new("Windows masaüstü yazılımı", "Windows desktop software", "/Products/Detail"),
            new("Güvenli lisans", "Secure license", "/Products/Detail"),
            new("Ömür boyu ücretsiz", "Free for life", "/Products/Detail"),
            new("Bulut + Mobil erişim", "Cloud + Mobile access", "/Products/Detail"),
            new("Windows cari / veresiye takibi", "Windows accounts / receivables tracking", "/Products/Detail"),
            new("Ücretsiz · Dijital indirme", "Free · Digital download", "/Products/Detail"),
            new("Kullanım lisansı", "Usage license", "/Products/Detail"),
            new("Üye girişiyle doğrudan indirme", "Direct download after sign-in", "/Products/Detail"),
            new("Ödeme adımı yok", "No payment step", "/Products/Detail"),
            new("Hemen kullanmaya başlayın", "Start using it now", "/Products/Detail"),
            new("Lisans türü", "License type", "/Products/Detail"),
            new("Yıllık lisans", "Annual license", "/Products/Detail"),
            new("365 gün kullanım", "365 days of use", "/Products/Detail"),
            new("Sınırsız lisans", "Lifetime license", "/Products/Detail"),
            new("Ömür boyu kullanım", "Lifetime use", "/Products/Detail"),
            new("Satın Alma Bildirimi", "Purchase Notification", "/Products/Detail"),
            new("Demo / İndirme", "Demo / Download", "/Products/Detail"),
            new("Kurulum dosyasını alın", "Get the installer", "/Products/Detail"),
            new("Özellikleri İncele", "Explore Features", "/Products/Detail"),
            new("Programın tüm özelliklerini görün", "See all software features", "/Products/Detail"),
            new("Stokta Yok", "Out of Stock", "/Products/Detail"),
            new("Bilgi Al", "Get Information", "/Products/Detail"),
            new("Dosya açılmıyor mu?", "Won't the file open?", "/Products/Detail"),
            new("Güvenli Kurulum Rehberini İnceleyin", "View the Safe Installation Guide", "/Products/Detail"),
            new("Sağ tık → Engellemeyi kaldır", "Right-click → Unblock", "/Products/Detail"),
            new("Rehberi Aç", "Open Guide", "/Products/Detail"),
            new("Ürün uzmanına sorun", "Ask a product specialist", "/Products/Detail"),
            new("WhatsApp ile bilgi alın", "Get information via WhatsApp", "/Products/Detail"),
            new("Onay sonrası hızlı erişim", "Fast access after approval", "/Products/Detail"),
            new("Ücretsiz indirme", "Free download", "/Products/Detail"),
            new("Üye girişi sonrası anında erişim", "Instant access after sign-in", "/Products/Detail"),
            new("Uzaktan kurulum", "Remote installation", "/Products/Detail"),
            new("NSX destek ekibi yanınızda", "The NSX support team is with you", "/Products/Detail"),
            new("Ürün Özellikleri", "Product Features", "/Products/Detail"),
            new("Teknik Bilgiler", "Technical Information", "/Products/Detail"),
            new("Kurulum & Destek", "Installation & Support", "/Products/Detail"),
            new("Soru & Cevap", "Questions & Answers", "/Products/Detail"),
            new("İndirme Bilgileri", "Download Information", "/Products/Detail"),
            new("Havale Bilgileri", "Bank Transfer Information", "/Products/Detail"),
            new("ÜRÜNÜ TANIYIN", "DISCOVER THE PRODUCT", "/Products/Detail"),
            new("TEKNİK BİLGİLER", "TECHNICAL INFORMATION", "/Products/Detail"),
            new("Kuruluma hazır, anlaşılır yapı.", "Clear and ready to install.", "/Products/Detail"),
            new("Satın almadan önce temel kullanım ve teslimat bilgilerini tek bakışta inceleyin.", "Review the essential usage and delivery information at a glance before purchasing.", "/Products/Detail"),
            new("İndirmeden önce temel kullanım, lisans ve kurulum bilgilerini tek bakışta inceleyin.", "Review the essential usage, license and installation information at a glance before downloading.", "/Products/Detail"),
            new("Platform", "Platform", "/Products/Detail"),
            new("Windows masaüstü", "Windows desktop", "/Products/Detail"),
            new("Teslimat", "Delivery", "/Products/Detail"),
            new("Dijital indirme", "Digital download", "/Products/Detail"),
            new("Dijital lisans / indirme", "Digital license / download", "/Products/Detail"),
            new("Yıllık veya sınırsız", "Annual or lifetime", "/Products/Detail"),
            new("Ürün kodu", "Product code", "/Products/Detail"),
            new("Kurulumda yalnız değilsiniz.", "You are not alone during installation.", "/Products/Detail"),
            new("Lisans ve indirme sonrasında ihtiyaç halinde uzaktan bağlantıyla kurulum ve başlangıç desteği alabilirsiniz.", "After licensing and download, you can receive remote installation and onboarding support when needed.", "/Products/Detail"),
            new("Ücretsiz indirme sonrasında ihtiyaç halinde uzaktan bağlantıyla kurulum ve başlangıç desteği alabilirsiniz.", "After the free download, you can receive remote installation and onboarding support when needed.", "/Products/Detail"),
            new("Ürünü ve lisansı seçin", "Choose the product and license", "/Products/Detail"),
            new("İşlemi tamamlayın", "Complete the process", "/Products/Detail"),
            new("Ücretsiz indirin", "Download for free", "/Products/Detail"),
            new("Kurulum desteği alın", "Get installation support", "/Products/Detail"),
            new("Deneyiminizi paylaşın", "Share your experience", "/Products/Detail"),
            new("Ürünü puanlayın ve dilerseniz kısa bir yorum bırakın.", "Rate the product and leave a short review if you wish.", "/Products/Detail"),
            new("Puanınız", "Your rating", "/Products/Detail"),
            new("Yorumunuz", "Your review", "/Products/Detail"),
            new("isteğe bağlı", "optional", "/Products/Detail"),
            new("Ürünle ilgili deneyiminizi yazın...", "Tell us about your experience with the product...", "/Products/Detail"),
            new("Değerlendirmeyi Gönder", "Submit Review", "/Products/Detail"),
            new("Ürün puanı", "Product rating", "/Products/Detail"),
            new("yıldız", "star", "/Products/Detail"),
            new("Yorum en fazla 2000 karakter olabilir.", "The review can contain up to 2000 characters.", "/Products/Detail"),
            new("Yorum yapılacak ürün bulunamadı.", "The product to review could not be found.", "/Products/Detail"),
            new("Puanınız alındı. Admin onayından sonra ürün puanına eklenecek.", "Your rating has been received. It will be added to the product rating after approval.", "/Products/Detail"),
            new("Yorumunuz ve puanınız alındı. Admin onayından sonra yayınlanacak.", "Your review and rating have been received. They will be published after approval.", "/Products/Detail"),
            new("MÜŞTERİ YORUMLARI", "CUSTOMER REVIEWS", "/Products/Detail"),
            new("İlk yorumu siz yapın", "Be the first to review", "/Products/Detail"),
            new("Yorumlar gerçek kullanıcı deneyimlerini yansıtır ve yayın öncesi kontrol edilir.", "Reviews reflect real user experiences and are checked before publication.", "/Products/Detail"),
            new("Yorum yapmak için giriş yap", "Sign in to leave a review", "/Products/Detail"),
            new("Henüz yorum yok", "No reviews yet", "/Products/Detail"),
            new("Bu ürün hakkındaki deneyiminizi paylaşan ilk kişi olabilirsiniz.", "You can be the first to share your experience with this product.", "/Products/Detail"),
            new("SIK SORULAN SORULAR", "FREQUENTLY ASKED QUESTIONS", "/Products/Detail"),
            new("Satın almadan önce bilmeniz gerekenler.", "What you should know before buying.", "/Products/Detail"),
            new("İndirmeden önce bilmeniz gerekenler.", "What you should know before downloading.", "/Products/Detail"),
            new("Ürün, lisans veya kurulum hakkında farklı bir sorunuz varsa destek ekibimize ulaşabilirsiniz.", "If you have another question about the product, license or installation, contact our support team.", "/Products/Detail"),
            new("Program hangi işletim sisteminde çalışır?", "Which operating system does the software run on?", "/Products/Detail"),
            new("NSX masaüstü yazılımları Windows ortamında çalışır. Ürün özel gereksinimleri destek ekibinden doğrulanabilir.", "NSX desktop software runs on Windows. Product-specific requirements can be confirmed with our support team.", "/Products/Detail"),
            new("Kurulum desteği veriliyor mu?", "Is installation support available?", "/Products/Detail"),
            new("Evet. İhtiyaç halinde uzaktan bağlantı ile kurulum ve ilk kullanım desteği sağlanır.", "Yes. Remote installation and initial-use support is available when needed.", "/Products/Detail"),
            new("Lisansı nasıl teslim alırım?", "How do I receive my license?", "/Products/Detail"),
            new("Ödeme onayından sonra lisans kullanıcı hesabına tanımlanır ve indirme erişimi açılır.", "After payment approval, the license is assigned to the user account and download access is enabled.", "/Products/Detail"),
            new("Ücretsiz lisansımı nasıl alırım?", "How do I get my free license?", "/Products/Detail"),
            new("Hesabınıza giriş yaptıktan sonra Ücretsiz İndir düğmesine basmanız yeterlidir. Ücretsiz kullanım lisansı hesabınıza otomatik tanımlanır; ödeme veya havale gerekmez.", "After signing in, simply click the Free Download button. Your free usage license is assigned to your account automatically; no payment or bank transfer is required.", "/Products/Detail"),
            new("Başka bir soru sorun →", "Ask another question →", "/Products/Detail"),
            new("GÜVENLİ İNDİRME", "SECURE DOWNLOAD", "/Products/Detail"),
            new("GÜVENLİ ÖDEME", "SECURE PAYMENT", "/Products/Detail"),
            new("Üye girişiyle hemen indirin.", "Sign in and download immediately.", "/Products/Detail"),
            new("Havale / EFT bilgileri.", "Bank transfer details.", "/Products/Detail"),
            new("Bu ürün için ödeme veya havale bildirimi gerekmez.", "No payment or bank transfer notification is required for this product.", "/Products/Detail"),
            new("Satın alma bildirimini gönderdikten sonra ödeme kontrol edilir; lisans ve indirme erişimi hesabınıza tanımlanır.", "After you submit the purchase notification, payment is verified and license and download access are assigned to your account.", "/Products/Detail"),
            new("Banka", "Bank", "/Products/Detail"),
            new("Alıcı", "Recipient", "/Products/Detail"),
            new("Açıklama", "Description", "/Products/Detail"),
            new("Lütfen boş bırakınız", "Please leave blank", "/Products/Detail"),
            new("Tutar", "Amount", "/Products/Detail"),
            new("Hesabınıza giriş yapın", "Sign in to your account", "/Products/Detail"),
            new("Demo / İndirme düğmesine basın", "Click the Demo / Download button", "/Products/Detail"),
            new("Ücretsiz İndir düğmesine basın", "Click the Free Download button", "/Products/Detail"),
            new("Dosyanıza güvenli şekilde erişin", "Access your file securely", "/Products/Detail"),
            new("Galeriyi kapat", "Close gallery", "/Products/Detail"),
            new("Önceki görsel", "Previous image", "/Products/Detail"),
            new("Sonraki görsel", "Next image", "/Products/Detail"),
            new("NSX ürün galerisi", "NSX product gallery", "/Products/Detail"),
            new("Galeri küçük görselleri", "Gallery thumbnails", "/Products/Detail"),
            new("ile gezinin", "to navigate", "/Products/Detail"),
            new("Rezervasyon ve salon planlama", "Reservation and venue planning", "/Products/Detail"),
            new("Sözleşme oluşturma", "Contract creation", "/Products/Detail"),
            new("Cari ve kasa takibi", "Accounts and cash tracking", "/Products/Detail"),
            new("SMS bilgilendirme", "SMS notifications", "/Products/Detail"),
            new("Etkinlik takvimi", "Event calendar", "/Products/Detail"),
            new("Çok kullanıcılı yapı", "Multi-user structure", "/Products/Detail"),
            new("Cari hesap yönetimi", "Account management", "/Products/Detail"),
            new("Komisyon hesaplama", "Commission calculation", "/Products/Detail"),
            new("Gelişmiş raporlar", "Advanced reports", "/Products/Detail"),
            new("Veri yedekleme", "Data backup", "/Products/Detail"),
            new("Servis raporları", "Service reports", "/Products/Detail"),
            new("Araç stok yönetimi", "Vehicle inventory management", "/Products/Detail"),
            new("Kâr ve zarar", "Profit and loss", "/Products/Detail"),
            new("Satış raporları", "Sales reports", "/Products/Detail"),
            new("Cihaz geçmişi", "Device history", "/Products/Detail"),
            new("Canlı durum takibi", "Live status tracking", "/Products/Detail"),
            new("Sesli çağrı", "Voice calling", "/Products/Detail"),
            new("Arıza takibi", "Fault tracking", "/Products/Detail"),
            new("Teslim yönetimi", "Delivery management", "/Products/Detail"),
            new("Hatırlatmalar", "Reminders", "/Products/Detail"),
            new("Hızlı temizlik", "Quick cleanup", "/Products/Detail"),
            new("Performans modu", "Performance mode", "/Products/Detail"),
            new("Tek tık optimizasyon", "One-click optimization", "/Products/Detail"),
            new("Başlangıç yönetimi", "Startup management", "/Products/Detail"),
            new("Sistem araçları", "System tools", "/Products/Detail"),
            new("Güvenli veri", "Secure data", "/Products/Detail"),
            new("Windows uyumu", "Windows compatibility", "/Products/Detail"),
            new("hakkında bilgi almak istiyorum.", "I would like information about", "/Products/Detail"),
            new("İşinizi hızlandırın.", "Speed up your work.", "/Products/Detail"),
            new("Yorumlar", "Reviews", "/Products/Detail"),
            new("müşteri puanı", "customer rating", "/Products/Detail"),
            new("İndirim havale bildiriminde otomatik uygulanır.", "The discount is applied automatically in the bank transfer notification.", "/Products/Detail"),
            new("program ekranı ve ürün görseli", "software screen and product image", "/Products/Detail"),
            new("görselini büyüt", "zoom image", "/Products/Detail"),
            new("büyük ürün görseli", "large product image", "/Products/Detail"),
            new("görseli göster", "show image", "/Products/Detail"),
            new("NSX Veresiye Pro program ekranı", "NSX Receivables Pro software screen", "/"),
            new("Kampanya", "Campaign", "/Products/Detail"),
            new("NSX Okul Plan Pro ile öğretmen, sınıf, derslik, haftalık ders programı ve nöbet çizelgesini tek merkezden düzenleyin, raporlayın ve PDF olarak paylaşın.", "Manage teachers, classes, classrooms, weekly schedules and duty rosters in one place with NSX School Planner Pro; organize, report and share them as PDF.", "/Products"),
            new("NSX Kasa Defteri Pro ile gelir, gider, tahsilat, ödeme, çoklu kasa, döviz kasası ve cari hesap hareketlerini tek merkezden güvenle yönetin.", "Securely manage income, expenses, collections, payments, multiple cash accounts, foreign-currency cash and customer account transactions in one place with NSX Cash Book Pro.", "/Products"),
            new("NSX Sigorta Acente Pro ile müşteri, poliçe, teklif, tahsilat, komisyon ve yenileme süreçlerini tek merkezden yönetin; yaklaşan poliçeleri zamanında takip edin.", "Manage customers, policies, quotations, collections, commissions and renewals in one place with NSX Insurance Agency Pro, and track upcoming policies on time.", "/Products"),
            new("NSX Security Auditor Pro ile kaynak kod, API, bağımlılık ve yayın çıktılarındaki güvenlik risklerini, gizli anahtarları ve riskli kod akışlarını analiz edin.", "Analyze security risks, exposed secrets and risky code flows in source code, APIs, dependencies and publish outputs with NSX Security Auditor Pro.", "/Products"),
            new("NSX Barkodlu Satış Pro ile barkodlu satış, ürün, stok, kasa, cari hesap, veresiye, tahsilat ve tedarikçi işlemlerini tek programdan yönetin.", "Manage barcode sales, products, inventory, cash, customer accounts, credit sales, collections and supplier operations from one application with NSX Barcode Sales Pro.", "/Products"),
            new("NSX Teknik Servis Pro ile müşteri, cihaz kabul, arıza, servis kaydı, işlem geçmişi, ödeme ve teslimat süreçlerini tek merkezden düzenli yönetin.", "Manage customers, device intake, faults, service records, transaction history, payments and delivery processes in one organized system with NSX Technical Service Pro.", "/Products"),
            new("NSX Cari Takip Pro ile firma ve müşteri carilerini, borç, alacak, tahsilat, ödeme, hatırlatma ve raporlama süreçlerini tek merkezden yönetin.", "Manage company and customer accounts, debit, credit, collections, payments, reminders and reporting in one place with NSX Account Tracking Pro.", "/Products"),
            new("NSX Düğün Salonu Pro ile rezervasyon, etkinlik, müşteri, salon, sözleşme, ödeme ve tahsilat süreçlerini tek merkezden planlayıp takip edin.", "Plan and track reservations, events, customers, venues, contracts, payments and collections in one place with NSX Wedding Venue Pro.", "/Products"),
            new("NSX Komisyonlu Cari Takip Pro ile cari hesap, borç, tahsilat, komisyon ve raporlama süreçlerini Server Client yapısıyla merkezi olarak yönetin.", "Centrally manage accounts, debt, collections, commissions and reporting with the Server-Client structure of NSX Commission Account Tracking Pro.", "/Products"),
            new("NSX Oto Tamir Servis Pro ile araç kabul, müşteri, iş emri, yedek parça, bakım, onarım, ödeme ve teslimat süreçlerini tek programdan yönetin.", "Manage vehicle intake, customers, work orders, spare parts, maintenance, repairs, payments and delivery from one application with NSX Auto Repair Service Pro.", "/Products"),
            new("NSX Oto Galeri Pro ile araç stoklarını, müşteri görüşmelerini, ilan, alış, satış, ödeme ve tahsilat süreçlerini tek merkezden düzenli takip edin.", "Track vehicle inventory, customer meetings, listings, purchases, sales, payments and collections in one place with NSX Auto Dealership Pro.", "/Products"),
            new("NSX Servis Pro Live ile QR kodlu canlı servis durumunu, cihaz kabulünü, müşteri bilgilendirmesini, iş emrini ve teslimat akışını tek sistemden yönetin.", "Manage live QR-coded service status, device intake, customer notifications, work orders and delivery flow from one system with NSX Service Pro Live.", "/Products"),
            new("NSX Klinik ve Randevu Takip Programı ile hasta, doktor, randevu, muayene, ödeme ve klinik iş akışını tek merkezden düzenli biçimde yönetin.", "Manage patients, doctors, appointments, examinations, payments and clinic workflows in one organized system with NSX Clinic & Appointment Tracking Pro.", "/Products"),
            new("NSX Veresiye Takip Pro ile müşteri cari hesaplarını, borç, tahsilat ve açık bakiyeleri masaüstü ve cep telefonundan Bulut sistemiyle ücretsiz yönetin.", "Manage customer accounts, debt, collections and outstanding balances for free from desktop and mobile with the cloud-enabled NSX Receivables Tracking Pro.", "/Products"),
            new("NSX Turbo ile Windows bakımını ve oyun performansını iyileştirin; gereksiz yükleri azaltın, gecikmeyi düşürün ve daha akıcı bir bilgisayar deneyimi elde edin.", "Improve Windows maintenance and gaming performance with NSX Turbo; reduce unnecessary load, lower latency and enjoy a smoother PC experience.", "/Products"),
        };
    }
}
