namespace NSXVeriKurtarmaPro.Services;

public enum SignatureKind
{
    Jpeg,
    Png,
    Gif,
    Bmp,
    TiffLittleEndian,
    TiffBigEndian,
    FujiRaf,
    SigmaX3f,
    WebP,
    Ico,
    Jpeg2000,
    Jpeg2000Codestream,
    Psd,
    Dds,
    Exr,
    Riff,
    Asf,
    AsfDataObject,
    IsoBmff,
    IsoBmffFragment,
    MpegTs,
    MpegProgramStream,
    MpegVideoStream,
    H264LengthPrefixed,
    H265LengthPrefixed,
    H264AnnexB,
    H265AnnexB,
    Matroska,
    MatroskaCluster,
    Flv,
    OggVideo,
    RealMedia,
    Mxf,
    MxfEssence,
    Dv,
    Wtv,
    Nsv,
    Roq,
    Bink,
    Smacker,
    Av1Ivf,
    Pdf,
    Zip,
    Mp3,
    AacAdts,
    Aiff,
    Au,
    Midi,
    SevenZip,
    Cab,
    PortableExecutable,
    SqliteDatabase,
    SqliteWal,
    SqliteJournal,
    Rar,
    OleCompound
}

public sealed record FileSignatureDefinition(
    SignatureKind Kind,
    byte[] Signature,
    int SignatureOffset = 0);

public static class FileSignatureCatalog
{
    public static IReadOnlyList<FileSignatureDefinition> Defaults { get; } =
    [
        new(SignatureKind.Jpeg, [0xFF, 0xD8, 0xFF]),
        new(SignatureKind.Png, [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]),
        new(SignatureKind.Gif, [(byte)'G', (byte)'I', (byte)'F', (byte)'8']),
        new(SignatureKind.Bmp, [(byte)'B', (byte)'M']),
        new(SignatureKind.FujiRaf, [(byte)'F', (byte)'U', (byte)'J', (byte)'I', (byte)'F', (byte)'I', (byte)'L', (byte)'M', (byte)'C', (byte)'C', (byte)'D', (byte)'-', (byte)'R', (byte)'A', (byte)'W', (byte)' ']),
        new(SignatureKind.SigmaX3f, [(byte)'F', (byte)'O', (byte)'V', (byte)'b']),
        new(SignatureKind.TiffLittleEndian, [(byte)'I', (byte)'I', 0x2A, 0x00]),
        new(SignatureKind.TiffBigEndian, [(byte)'M', (byte)'M', 0x00, 0x2A]),
        new(SignatureKind.WebP, [(byte)'R', (byte)'I', (byte)'F', (byte)'F']),
        new(SignatureKind.Ico, [0x00, 0x00, 0x01, 0x00]),
        new(SignatureKind.Jpeg2000, [0x00, 0x00, 0x00, 0x0C, (byte)'j', (byte)'P', 0x20, 0x20, 0x0D, 0x0A, 0x87, 0x0A]),
        new(SignatureKind.Jpeg2000Codestream, [0xFF, 0x4F, 0xFF, 0x51]),
        new(SignatureKind.Psd, [(byte)'8', (byte)'B', (byte)'P', (byte)'S', 0x00, 0x01]),
        new(SignatureKind.Dds, [(byte)'D', (byte)'D', (byte)'S', (byte)' ' ]),
        new(SignatureKind.Exr, [0x76, 0x2F, 0x31, 0x01]),
        new(SignatureKind.Riff, [(byte)'R', (byte)'I', (byte)'F', (byte)'F']),
        new(SignatureKind.Asf, [0x30, 0x26, 0xB2, 0x75, 0x8E, 0x66, 0xCF, 0x11, 0xA6, 0xD9, 0x00, 0xAA, 0x00, 0x62, 0xCE, 0x6C]),
        new(SignatureKind.AsfDataObject, [0x36, 0x26, 0xB2, 0x75, 0x8E, 0x66, 0xCF, 0x11, 0xA6, 0xD9, 0x00, 0xAA, 0x00, 0x62, 0xCE, 0x6C]),
        new(SignatureKind.IsoBmff, [(byte)'f', (byte)'t', (byte)'y', (byte)'p'], 4),
        new(SignatureKind.Matroska, [0x1A, 0x45, 0xDF, 0xA3]),
        new(SignatureKind.MatroskaCluster, [0x1F, 0x43, 0xB6, 0x75]),
        new(SignatureKind.Flv, [(byte)'F', (byte)'L', (byte)'V', 0x01]),
        new(SignatureKind.OggVideo, [(byte)'O', (byte)'g', (byte)'g', (byte)'S', 0x00]),
        new(SignatureKind.RealMedia, [(byte)'.', (byte)'R', (byte)'M', (byte)'F']),
        new(SignatureKind.Mxf, [0x06, 0x0E, 0x2B, 0x34, 0x02, 0x05, 0x01, 0x01, 0x0D, 0x01, 0x02, 0x01, 0x01, 0x02]),
        new(SignatureKind.MxfEssence, [0x06, 0x0E, 0x2B, 0x34, 0x01, 0x02, 0x01, 0x01, 0x0D, 0x01, 0x03, 0x01]),
        new(SignatureKind.Wtv, [0xB7, 0xD8, 0x00, 0x20, 0x37, 0x49, 0xDA, 0x11, 0xA6, 0x4E, 0x00, 0x07, 0xE9, 0x5E, 0xAD, 0x8D]),
        new(SignatureKind.Nsv, [(byte)'N', (byte)'S', (byte)'V', (byte)'f']),
        new(SignatureKind.Roq, [0x84, 0x10, 0xFF, 0xFF, 0xFF, 0xFF]),
        new(SignatureKind.Bink, [(byte)'B', (byte)'I', (byte)'K']),
        new(SignatureKind.Bink, [(byte)'K', (byte)'B', (byte)'2']),
        new(SignatureKind.Smacker, [(byte)'S', (byte)'M', (byte)'K', (byte)'2']),
        new(SignatureKind.Smacker, [(byte)'S', (byte)'M', (byte)'K', (byte)'4']),
        new(SignatureKind.Av1Ivf, [(byte)'D', (byte)'K', (byte)'I', (byte)'F', 0x00, 0x00, 0x20, 0x00, (byte)'A', (byte)'V', (byte)'0', (byte)'1']),
        new(SignatureKind.MpegProgramStream, [0x00, 0x00, 0x01, 0xBA]),
        new(SignatureKind.MpegVideoStream, [0x00, 0x00, 0x01, 0xB3]),
        new(SignatureKind.Pdf, [(byte)'%', (byte)'P', (byte)'D', (byte)'F']),
        new(SignatureKind.Zip, [(byte)'P', (byte)'K', 0x03, 0x04]),
        new(SignatureKind.Mp3, [(byte)'I', (byte)'D', (byte)'3']),
        new(SignatureKind.AacAdts, [0xFF, 0xF1]),
        new(SignatureKind.Aiff, [(byte)'F', (byte)'O', (byte)'R', (byte)'M']),
        new(SignatureKind.Au, [(byte)'.', (byte)'s', (byte)'n', (byte)'d']),
        new(SignatureKind.Midi, [(byte)'M', (byte)'T', (byte)'h', (byte)'d']),
        new(SignatureKind.SevenZip, [0x37, 0x7A, 0xBC, 0xAF, 0x27, 0x1C]),
        new(SignatureKind.Cab, [(byte)'M', (byte)'S', (byte)'C', (byte)'F']),
        new(SignatureKind.PortableExecutable, [(byte)'M', (byte)'Z']),
        new(SignatureKind.SqliteDatabase, "SQLite format 3\0"u8.ToArray()),
        new(SignatureKind.SqliteWal, [0x37, 0x7F, 0x06, 0x82]),
        new(SignatureKind.SqliteWal, [0x37, 0x7F, 0x06, 0x83]),
        new(SignatureKind.SqliteJournal, [0xD9, 0xD5, 0x05, 0xF9, 0x20, 0xA1, 0x63, 0xD7]),
        new(SignatureKind.Rar, [(byte)'R', (byte)'a', (byte)'r', (byte)'!', 0x1A, 0x07]),
        new(SignatureKind.OleCompound, [0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1])
    ];
}
