CREATE TABLE IF NOT EXISTS MailLogs (
    Id INT NOT NULL AUTO_INCREMENT,
    ToEmail LONGTEXT NOT NULL,
    ToName LONGTEXT NULL,
    Subject LONGTEXT NOT NULL,
    Body LONGTEXT NOT NULL,
    IsSuccess TINYINT(1) NOT NULL DEFAULT 0,
    ErrorMessage LONGTEXT NULL,
    MailType LONGTEXT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (Id)
);
