CREATE TABLE IF NOT EXISTS `Advertisements` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `ProductId` int NULL,
  `ProductCode` varchar(100) CHARACTER SET utf8mb4 NOT NULL DEFAULT 'NSXVERESIYEDEFTERI',
  `SlotCode` varchar(80) CHARACTER SET utf8mb4 NOT NULL DEFAULT 'FREE_BOTTOM_728X90',
  `Title` varchar(180) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `Description` varchar(500) CHARACTER SET utf8mb4 NULL,
  `AltText` varchar(300) CHARACTER SET utf8mb4 NULL,
  `ImagePath` varchar(700) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `TargetUrl` varchar(700) CHARACTER SET utf8mb4 NULL,
  `Width` int NOT NULL DEFAULT 728,
  `Height` int NOT NULL DEFAULT 90,
  `DisplaySeconds` int NOT NULL DEFAULT 10,
  `SortOrder` int NOT NULL DEFAULT 0,
  `Priority` int NOT NULL DEFAULT 0,
  `StartDate` datetime(6) NULL,
  `EndDate` datetime(6) NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT 1,
  `IsDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `TrackClicks` tinyint(1) NOT NULL DEFAULT 1,
  `ImpressionCount` int NOT NULL DEFAULT 0,
  `ClickCount` int NOT NULL DEFAULT 0,
  `LastShownAt` datetime(6) NULL,
  `LastClickedAt` datetime(6) NULL,
  `CreatedAt` datetime(6) NOT NULL,
  `UpdatedAt` datetime(6) NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Advertisements_ProductSlotActive` (`ProductCode`, `SlotCode`, `IsActive`),
  INDEX `IX_Advertisements_DateFilter` (`IsDeleted`, `StartDate`, `EndDate`),
  INDEX `IX_Advertisements_ProductId` (`ProductId`)
) CHARACTER SET=utf8mb4;
